; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[common]
lib_deps = zinggjm/GxEPD2@^1.6.4
           liux-pro/qrcode generator@^1.7.0

[env:esp32dev]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
board_build.partitions = huge_app.csv
build_flags = -DCS_PIN=5 -DBUSY_PIN=4 -DRES_PIN=17 -DDC_PIN=16
lib_deps = ${common.lib_deps}

[env:esp32c3]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
platform = https://github.com/pioarduino/platform-espressif32.git
board = sparkfun_pro_micro_esp32c3
board_build.partitions = huge_app.csv
build_flags = -DCS_PIN=7 -DBUSY_PIN=3 -DRES_PIN=2 -DDC_PIN=5
lib_deps = ${common.lib_deps}

[env:esp32s3]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
platform = https://github.com/pioarduino/platform-espressif32.git
board = waveshare_esp32_s3_zero
board_build.partitions = huge_app.csv
build_flags = -DCS_PIN=10 -DBUSY_PIN=1 -DRES_PIN=2 -DDC_PIN=17
lib_deps = ${common.lib_deps}
