; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[common]
lib_deps = zinggjm/GxEPD2@^1.6.4
           liux-pro/qrcode generator@^1.7.0

[env:esp32dev]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
board_build.partitions = huge_app.csv
build_flags = -DCS_PIN=5 -DBUSY_PIN=4 -DRES_PIN=17 -DDC_PIN=16
lib_deps = ${common.lib_deps}

[env:esp32c3]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
platform = https://github.com/pioarduino/platform-espressif32.git
board = sparkfun_pro_micro_esp32c3
board_build.partitions = huge_app.csv
build_flags = -DCS_PIN=7 -DBUSY_PIN=3 -DRES_PIN=2 -DDC_PIN=5
lib_deps = ${common.lib_deps}

[env:esp32s3]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
platform = https://github.com/pioarduino/platform-espressif32.git
board = waveshare_esp32_s3_zero
board_build.partitions = huge_app.csv
build_flags = -DCS_PIN=10 -DBUSY_PIN=1 -DRES_PIN=2 -DDC_PIN=17 -DARDUINO_USB_CDC_ON_BOOT=1 -DCORE_DEBUG_LEVEL=1
lib_deps = ${common.lib_deps}
custom_sdkconfig = CONFIG_BT_CTRL_MODEM_SLEEP=y
                   CONFIG_BT_CTRL_MODEM_SLEEP_MODE_1=y
                   CONFIG_BT_CTRL_LPCLK_SEL_MAIN_XTAL=n
                   CONFIG_BT_CTRL_LPCLK_SEL_EXT_32K_XTAL=y
                   CONFIG_BT_CTRL_MAIN_XTAL_PU_DURING_LIGHT_SLEEP=y
                   CONFIG_BT_CTRL_SLEEP_MODE_EFF=1
                   CONFIG_BT_CTRL_SLEEP_CLOCK_EFF=2
                   CONFIG_RTC_CLK_SRC_INT_RC=n
                   CONFIG_RTC_CLK_SRC_EXT_CRYS=y
                   CONFIG_RTC_CLK_CAL_CYCLES=3000
                   CONFIG_ESP_PHY_MAX_WIFI_TX_POWER=10
                   CONFIG_ESP_PHY_MAX_TX_POWER=10
                   CONFIG_PM_ENABLE=y
                   CONFIG_PM_DFS_INIT_AUTO=y
                   CONFIG_PM_RTOS_IDLE_OPT=y
                   CONFIG_PM_SLP_DISABLE_GPIO=y
                   CONFIG_PM_LIGHTSLEEP_RTC_OSC_CAL_INTERVAL=1
                   CONFIG_ESP_SYSTEM_RTC_EXT_XTAL=y
                   CONFIG_ESP_SYSTEM_RTC_EXT_XTAL_BOOTSTRAP_CYCLES=0
                   CONFIG_FREERTOS_HZ=1000
                   CONFIG_FREERTOS_USE_TICKLESS_IDLE=y
                   CONFIG_FREERTOS_IDLE_TIME_BEFORE_SLEEP=3
                   CONFIG_ESP32S3_RTC_CLK_SRC_INT_RC=n
                   CONFIG_ESP32S3_RTC_CLK_SRC_EXT_CRYS=y
                   CONFIG_ESP32S3_RTC_CLK_CAL_CYCLES=3000
                   CONFIG_ESP_CONSOLE_USB_CDC=y
custom_component_remove     = espressif/esp_hosted 
                              espressif/esp_wifi_remote 
                              espressif/qrcode 
                              espressif/esp_insights 
                              espressif/esp_diag_data_store 
                              espressif/esp_diagnostics 
                              espressif/esp_rainmaker 
                              espressif/rmaker_common 
