/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/atoms.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EventAdmin, EventAdmin, AUTO)

PB_BIND(EventReferee, EventReferee, AUTO)

PB_BIND(Person, Person, AUTO)

PB_BIND(PersonEx, PersonEx, AUTO)

PB_BIND(Country, Country, AUTO)

PB_BIND(Event, Event, AUTO)

PB_BIND(MyEvent, MyEvent, AUTO)

PB_BIND(GameConfig, GameConfig, 2)

PB_BIND(PlayerInRating, PlayerInRating, AUTO)

PB_BIND(Player, Player, AUTO)

PB_BIND(FinalResultOfSession, FinalResultOfSession, AUTO)

PB_BIND(Penalty, Penalty, AUTO)

PB_BIND(RonResult, RonResult, AUTO)

PB_BIND(MultironWin, MultironWin, AUTO)

PB_BIND(MultironResult, MultironResult, AUTO)

PB_BIND(TsumoResult, TsumoResult, AUTO)

PB_BIND(DrawResult, DrawResult, AUTO)

PB_BIND(AbortResult, AbortResult, AUTO)

PB_BIND(ChomboResult, ChomboResult, AUTO)

PB_BIND(NagashiResult, NagashiResult, AUTO)

PB_BIND(Round, Round, AUTO)

PB_BIND(GameResult, GameResult, AUTO)

PB_BIND(PlayerPlaceInSeries, PlayerPlaceInSeries, AUTO)

PB_BIND(SeriesResult, SeriesResult, AUTO)

PB_BIND(ReplacementPlayer, ReplacementPlayer, AUTO)

PB_BIND(PlayerInSession, PlayerInSession, AUTO)

PB_BIND(RegisteredPlayer, RegisteredPlayer, AUTO)

PB_BIND(SessionHistoryResult, SessionHistoryResult, AUTO)

PB_BIND(SessionHistoryResultTable, SessionHistoryResultTable, AUTO)

PB_BIND(PlacesSummaryItem, PlacesSummaryItem, AUTO)

PB_BIND(PlayerWinSummary, PlayerWinSummary, AUTO)

PB_BIND(HandValueStat, HandValueStat, AUTO)

PB_BIND(YakuStat, YakuStat, AUTO)

PB_BIND(RiichiSummary, RiichiSummary, AUTO)

PB_BIND(DoraSummary, DoraSummary, AUTO)

PB_BIND(IntermediateResultOfSession, IntermediateResultOfSession, AUTO)

PB_BIND(PaymentLogItem, PaymentLogItem, AUTO)

PB_BIND(PaymentLog, PaymentLog, AUTO)

PB_BIND(RoundState, RoundState, 2)

PB_BIND(EventData, EventData, 2)

PB_BIND(TableState, TableState, AUTO)

PB_BIND(Achievement, Achievement, AUTO)

PB_BIND(LocalIdMapping, LocalIdMapping, AUTO)

PB_BIND(TeamMapping, TeamMapping, AUTO)

PB_BIND(PlayerSeating, PlayerSeating, AUTO)

PB_BIND(PlayerSeatingSwiss, PlayerSeatingSwiss, AUTO)

PB_BIND(TableItemSwiss, TableItemSwiss, AUTO)

PB_BIND(PrescriptedTable, PrescriptedTable, AUTO)

PB_BIND(Chombo, Chombo, AUTO)

PB_BIND(SessionState, SessionState, AUTO)

PB_BIND(Uma, Uma, AUTO)

PB_BIND(ComplexUma, ComplexUma, AUTO)

PB_BIND(RulesetConfig, RulesetConfig, 2)

PB_BIND(MajsoulSearchEx, MajsoulSearchEx, AUTO)

PB_BIND(MajsoulPersonMapping, MajsoulPersonMapping, AUTO)

PB_BIND(GenericSuccessResponse, GenericSuccessResponse, AUTO)

PB_BIND(GenericEventPayload, GenericEventPayload, AUTO)

PB_BIND(GenericSessionPayload, GenericSessionPayload, AUTO)
