/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_ATOMS_PB_H_INCLUDED
#define PB_PROTO_ATOMS_PB_H_INCLUDED
#include <pb.h>
#include "proto/nanopb.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _EventType {
	EventType_EVENT_TYPE_UNSPECIFIED = 0,
	EventType_EVENT_TYPE_TOURNAMENT = 1,
	EventType_EVENT_TYPE_LOCAL = 2,
	EventType_EVENT_TYPE_ONLINE = 3
} EventType;

typedef enum _TournamentGamesStatus {
	TournamentGamesStatus_TOURNAMENT_GAMES_STATUS_UNSPECIFIED = 0, /* for non-tournament events */
	TournamentGamesStatus_TOURNAMENT_GAMES_STATUS_SEATING_READY = 1,
	TournamentGamesStatus_TOURNAMENT_GAMES_STATUS_STARTED = 2
} TournamentGamesStatus;

typedef enum _RoundOutcome {
	RoundOutcome_ROUND_OUTCOME_UNSPECIFIED = 0,
	RoundOutcome_ROUND_OUTCOME_RON = 1,
	RoundOutcome_ROUND_OUTCOME_TSUMO = 2,
	RoundOutcome_ROUND_OUTCOME_DRAW = 3,
	RoundOutcome_ROUND_OUTCOME_ABORT = 4,
	RoundOutcome_ROUND_OUTCOME_CHOMBO = 5,
	RoundOutcome_ROUND_OUTCOME_NAGASHI = 6,
	RoundOutcome_ROUND_OUTCOME_MULTIRON = 7
} RoundOutcome;

typedef enum _SessionStatus {
	SessionStatus_SESSION_STATUS_UNSPECIFIED = 0,
	SessionStatus_SESSION_STATUS_INPROGRESS = 1,
	SessionStatus_SESSION_STATUS_PREFINISHED = 2,
	SessionStatus_SESSION_STATUS_FINISHED = 3,
	SessionStatus_SESSION_STATUS_CANCELLED = 4,
	SessionStatus_SESSION_STATUS_PLANNED = 5
} SessionStatus;

typedef enum _UmaType {
	UmaType_UMA_TYPE_UNSPECIFIED = 0,
	UmaType_UMA_TYPE_UMA_SIMPLE = 1,
	UmaType_UMA_TYPE_UMA_COMPLEX = 2
} UmaType;

typedef enum _EndingPolicy {
	EndingPolicy_ENDING_POLICY_EP_UNSPECIFIED = 0,
	EndingPolicy_ENDING_POLICY_EP_ONE_MORE_HAND = 1,
	EndingPolicy_ENDING_POLICY_EP_END_AFTER_HAND = 2
} EndingPolicy;

typedef enum _PlatformType {
	PlatformType_PLATFORM_TYPE_UNSPECIFIED = 0,
	PlatformType_PLATFORM_TYPE_TENHOUNET = 1,
	PlatformType_PLATFORM_TYPE_MAHJONGSOUL = 2
} PlatformType;

/* Struct definitions */
typedef struct _EventAdmin {
	int32_t rule_id;
	int32_t person_id;
	pb_callback_t person_name;
	bool has_avatar;
	pb_callback_t last_update;
} EventAdmin;

typedef struct _EventReferee {
	int32_t rule_id;
	int32_t person_id;
	pb_callback_t person_name;
	bool has_avatar;
	pb_callback_t last_update;
} EventReferee;

typedef struct _Person {
	int32_t id;
	pb_callback_t city;
	pb_callback_t tenhou_id;
	pb_callback_t title;
	bool has_avatar;
	pb_callback_t last_update;
} Person;

typedef struct _PersonEx {
	int32_t id;
	pb_callback_t city;
	pb_callback_t tenhou_id;
	pb_callback_t title;
	pb_callback_t country;
	pb_callback_t email;
	pb_callback_t phone;
	bool has_avatar;
	pb_callback_t last_update;
	pb_callback_t ms_nickname;
	int32_t ms_account_id;
	pb_callback_t telegram_id;
	pb_callback_t notifications;
} PersonEx;

typedef struct _Country {
	pb_callback_t code;
	pb_callback_t name;
} Country;

typedef struct _Event {
	int32_t id;
	pb_callback_t title;
	pb_callback_t description;
	bool finished;
	bool is_listed;
	bool is_rating_shown;
	bool tournament_started;
	EventType type;
	bool is_prescripted;
	bool is_team;
	bool has_series;
	bool with_chips;
	int32_t min_games_count;
	bool achievements_shown;
	bool with_yakitori;
	PlatformType platform_id;
} Event;

typedef struct _MyEvent {
	int32_t id;
	pb_callback_t title;
	pb_callback_t description;
	bool is_online;
} MyEvent;

typedef struct _PlayerInRating {
	int32_t id;
	pb_callback_t title;
	pb_callback_t tenhou_id;
	float rating;
	int32_t chips;
	bool winner_zone;
	float avg_place;
	float avg_score;
	int32_t games_played;
	pb_callback_t team_name;
	bool has_avatar;
	pb_callback_t last_update;
	float penalties_amount;
	int32_t penalties_count;
} PlayerInRating;

typedef struct _Player {
	int32_t id;
	pb_callback_t title;
	pb_callback_t tenhou_id;
	bool has_avatar;
	pb_callback_t last_update;
} Player;

typedef struct _FinalResultOfSession {
	int32_t player_id;
	int32_t score;
	float rating_delta;
	int32_t place;
} FinalResultOfSession;

typedef struct _Penalty {
	int32_t who;
	int32_t amount;
	pb_callback_t reason;
	int32_t assigned_by;
	pb_callback_t created_at;
	bool is_cancelled;
	pb_callback_t cancellation_reason;
	int32_t id;
} Penalty;

typedef struct _RonResult {
	int32_t round_index;
	int32_t honba;
	int32_t winner_id;
	int32_t loser_id;
	int32_t pao_player_id;
	int32_t han;
	int32_t fu;
	pb_callback_t yaku; /* yaku ids */
	pb_callback_t riichi_bets; /* player ids */
	int32_t dora;
	int32_t uradora;
	int32_t kandora;
	int32_t kanuradora;
	bool open_hand;
} RonResult;

typedef struct _MultironWin {
	int32_t winner_id;
	int32_t pao_player_id;
	int32_t han;
	int32_t fu;
	pb_callback_t yaku; /* yaku ids */
	int32_t dora;
	int32_t uradora;
	int32_t kandora;
	int32_t kanuradora;
	bool open_hand;
} MultironWin;

typedef struct _MultironResult {
	int32_t round_index;
	int32_t honba;
	int32_t loser_id;
	int32_t multi_ron; /* count of players who won */
	pb_callback_t wins;
	pb_callback_t riichi_bets; /* player ids */
} MultironResult;

typedef struct _TsumoResult {
	int32_t round_index;
	int32_t honba;
	int32_t winner_id;
	int32_t pao_player_id;
	int32_t han;
	int32_t fu;
	pb_callback_t yaku; /* yaku ids */
	pb_callback_t riichi_bets; /* player ids */
	int32_t dora;
	int32_t uradora;
	int32_t kandora;
	int32_t kanuradora;
	bool open_hand;
} TsumoResult;

typedef struct _DrawResult {
	int32_t round_index;
	int32_t honba;
	pb_callback_t riichi_bets; /* player ids */
	pb_callback_t tempai; /* player ids */
} DrawResult;

typedef struct _AbortResult {
	int32_t round_index;
	int32_t honba;
	pb_callback_t riichi_bets; /* player ids */
} AbortResult;

typedef struct _ChomboResult {
	int32_t round_index;
	int32_t honba;
	int32_t loser_id;
} ChomboResult;

typedef struct _NagashiResult {
	int32_t round_index;
	int32_t honba;
	pb_callback_t riichi_bets; /* player ids */
	pb_callback_t tempai; /* player ids */
	pb_callback_t nagashi; /* player ids */
} NagashiResult;

typedef struct _Round {
	pb_size_t which_outcome;
	union {
		RonResult ron;
		TsumoResult tsumo;
		MultironResult multiron;
		DrawResult draw;
		AbortResult abort;
		ChomboResult chombo;
		NagashiResult nagashi;
	} outcome;
} Round;

typedef struct _GameResult {
	pb_callback_t session_hash;
	pb_callback_t date;
	pb_callback_t replay_link;
	pb_callback_t players;
	pb_callback_t final_results;
	pb_callback_t rounds;
} GameResult;

typedef struct _PlayerPlaceInSeries {
	pb_callback_t session_hash;
	int32_t place;
} PlayerPlaceInSeries;

typedef struct _SeriesResult {
	bool has_player;
	Player player;
	pb_callback_t best_series;
	float best_series_scores;
	int32_t best_series_places;
	pb_callback_t best_series_avg_place; /* formatted numeric string */
	pb_callback_t current_series;
	float current_series_scores;
	int32_t current_series_places;
	pb_callback_t current_series_avg_place; /* formatted numeric string */
} SeriesResult;

typedef struct _ReplacementPlayer {
	int32_t id;
	pb_callback_t title;
	bool has_avatar;
	pb_callback_t last_update;
} ReplacementPlayer;

typedef struct _PlayerInSession {
	int32_t id;
	char title[129];
	int32_t score;
	bool has_replaced_by;
	ReplacementPlayer replaced_by;
	float rating_delta;
	bool has_avatar;
	pb_callback_t last_update;
	bool yakitori;
} PlayerInSession;

typedef struct _RegisteredPlayer {
	int32_t id;
	pb_callback_t title;
	bool has_local_id;
	int32_t local_id;
	pb_callback_t team_name;
	pb_callback_t tenhou_id;
	bool ignore_seating;
	bool has_replaced_by;
	ReplacementPlayer replaced_by;
	bool has_avatar;
	pb_callback_t last_update;
} RegisteredPlayer;

typedef struct _SessionHistoryResult {
	pb_callback_t session_hash;
	int32_t event_id;
	int32_t player_id;
	int32_t score;
	float rating_delta;
	int32_t place;
	pb_callback_t title;
	bool has_avatar;
	pb_callback_t last_update;
} SessionHistoryResult;

typedef struct _SessionHistoryResultTable {
	pb_callback_t tables;
} SessionHistoryResultTable;

typedef struct _PlacesSummaryItem {
	int32_t place;
	int32_t count; /* count of games finished on this particular place */
} PlacesSummaryItem;

typedef struct _PlayerWinSummary {
	int32_t ron;
	int32_t tsumo;
	int32_t chombo;
	int32_t feed;
	int32_t tsumofeed;
	int32_t wins_with_open;
	int32_t wins_with_riichi;
	int32_t wins_with_dama;
	int32_t unforced_feed_to_open;
	int32_t unforced_feed_to_riichi;
	int32_t unforced_feed_to_dama;
	int32_t draw;
	int32_t draw_tempai;
	int32_t points_won;
	int32_t points_lost_ron;
	int32_t points_lost_tsumo;
} PlayerWinSummary;

typedef struct _HandValueStat {
	int32_t han_count;
	int32_t count; /* count of hands with this value */
} HandValueStat;

typedef struct _YakuStat {
	int32_t yaku_id;
	int32_t count; /* count of hands contained this yaku */
} YakuStat;

typedef struct _RiichiSummary {
	int32_t riichi_won;
	int32_t riichi_lost;
	int32_t feed_under_riichi;
} RiichiSummary;

typedef struct _DoraSummary {
	int32_t count;
	float average;
} DoraSummary;

typedef struct _IntermediateResultOfSession {
	int32_t player_id;
	int32_t score;
	int32_t chombo_count;
} IntermediateResultOfSession;

typedef struct _PaymentLogItem {
	bool has_from;
	int32_t from;
	bool has_to;
	int32_t to;
	int32_t amount;
} PaymentLogItem;

typedef struct _PaymentLog {
	pb_callback_t direct;
	pb_callback_t riichi;
	pb_callback_t honba;
} PaymentLog;

typedef struct _RoundState {
	pb_callback_t session_hash;
	int32_t dealer; /* player id */
	int32_t round_index;
	int32_t riichi; /* riichis on table */
	int32_t honba; /* honba on table */
	pb_callback_t riichi_ids; /* player ids */
	pb_callback_t scores; /* scores AFTER payments */
	pb_callback_t scores_delta;
	bool has_payments;
	PaymentLog payments;
	bool has_round;
	Round round;
	RoundOutcome outcome;
} RoundState;

typedef struct _TableState {
	SessionStatus status;
	bool may_definalize;
	pb_callback_t session_hash;
	bool has_table_index;
	int32_t table_index;
	bool has_last_round;
	Round last_round;
	int32_t current_round_index;
	pb_callback_t scores;
	pb_callback_t players;
	bool has_extra_time;
	int32_t extra_time;
} TableState;

typedef struct _Achievement {
	pb_callback_t achievement_id;
	pb_callback_t achievement_data; /* JSON stringified data */
} Achievement;

typedef struct _LocalIdMapping {
	int32_t player_id;
	int32_t local_id;
} LocalIdMapping;

typedef struct _TeamMapping {
	int32_t player_id;
	pb_callback_t team_name;
} TeamMapping;

typedef struct _PlayerSeating {
	int32_t order; /* order at the table */
	int32_t player_id;
	int32_t session_id;
	int32_t table_index;
	float rating;
	pb_callback_t player_title;
	bool has_avatar;
	pb_callback_t last_update;
} PlayerSeating;

typedef struct _PlayerSeatingSwiss {
	int32_t player_id;
	float rating;
} PlayerSeatingSwiss;

typedef struct _TableItemSwiss {
	pb_callback_t players; /* should be 4 elements */
} TableItemSwiss;

typedef struct _PrescriptedTable {
	pb_callback_t players; /* should be 4 elements */
} PrescriptedTable;

typedef struct _Chombo {
	int32_t player_id;
	float amount;
} Chombo;

typedef struct _SessionState {
	int32_t dealer;
	int32_t round_index;
	int32_t riichi_count;
	int32_t honba_count;
	pb_callback_t scores;
	bool finished;
	bool last_hand_started;
	pb_callback_t chombo;
} SessionState;

typedef struct _Uma {
	int32_t place1;
	int32_t place2;
	int32_t place3;
	int32_t place4;
} Uma;

typedef struct _ComplexUma {
	bool has_neg1;
	Uma neg1;
	bool has_neg3;
	Uma neg3;
	bool has_otherwise;
	Uma otherwise;
} ComplexUma;

typedef struct _RulesetConfig {
	bool has_complex_uma;
	ComplexUma complex_uma;
	EndingPolicy ending_policy;
	bool has_uma;
	Uma uma;
	UmaType uma_type;
	bool doubleron_honba_atamahane;
	bool doubleron_riichi_atamahane;
	bool equalize_uma;
	bool extra_chombo_payments;
	bool play_additional_rounds;
	bool riichi_goes_to_winner;
	bool tonpuusen;
	bool with_abortives;
	bool with_atamahane;
	bool with_buttobi;
	bool with_kazoe;
	bool with_kiriage_mangan;
	bool with_kuitan;
	bool with_leading_dealer_game_over;
	bool with_multi_yakumans;
	bool with_nagashi_mangan;
	bool with_winning_dealer_honba_skipped;
	int32_t chips_value;
	int32_t chombo_amount;
	int32_t game_expiration_time;
	int32_t goal_points;
	int32_t max_penalty;
	int32_t min_penalty;
	int32_t oka;
	int32_t penalty_step;
	int32_t replacement_player_fixed_points;
	int32_t replacement_player_override_uma;
	int32_t start_points;
	int32_t start_rating;
	pb_callback_t allowed_yaku;
	pb_callback_t yaku_with_pao;
	bool with_yakitori;
	int32_t yakitori_penalty;
	bool chombo_ends_game;
	int32_t honba_value;
	pb_callback_t double_yakuman;
} RulesetConfig;

typedef struct _GameConfig {
	pb_callback_t ruleset_title;
	pb_callback_t event_title;
	pb_callback_t event_description;
	pb_callback_t event_stat_host;
	bool use_timer;
	bool use_penalty;
	int32_t game_duration; /* minutes */
	pb_callback_t timezone;
	bool is_online;
	bool is_team;
	bool auto_seating;
	bool sync_start;
	bool sync_end;
	bool sort_by_games;
	bool allow_player_append;
	int32_t series_length;
	int32_t min_games_count;
	TournamentGamesStatus games_status;
	bool hide_results;
	bool hide_add_replay_button;
	bool is_prescripted;
	bool is_finished;
	bool has_ruleset_config;
	RulesetConfig ruleset_config;
	int32_t lobby_id;
	bool allow_view_other_tables;
} GameConfig;

typedef struct _EventData {
	bool has_type;
	EventType type; /* required to add, not required for edit */
	pb_callback_t title;
	pb_callback_t description;
	int32_t duration;
	pb_callback_t timezone;
	int32_t lobby_id; /* xxxx for common lobby, 1xxxx for tournament lobby */
	int32_t series_length;
	int32_t min_games;
	bool is_team;
	bool is_prescripted;
	int32_t autostart; /* time until game autostart */
	bool has_ruleset_config;
	RulesetConfig ruleset_config;
	bool is_listed;
	bool is_rating_shown;
	bool achievements_shown;
	bool allow_view_other_tables;
	PlatformType platform_id;
} EventData;

typedef struct _MajsoulSearchEx {
	pb_callback_t nickname;
	int32_t account_id;
} MajsoulSearchEx;

typedef struct _MajsoulPersonMapping {
	int32_t person_id;
	pb_callback_t nickname;
} MajsoulPersonMapping;

typedef struct _GenericSuccessResponse {
	bool success;
} GenericSuccessResponse;

typedef struct _GenericEventPayload {
	int32_t event_id;
} GenericEventPayload;

typedef struct _GenericSessionPayload {
	pb_callback_t session_hash;
} GenericSessionPayload;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _EventType_MIN EventType_EVENT_TYPE_UNSPECIFIED
#define _EventType_MAX EventType_EVENT_TYPE_ONLINE
#define _EventType_ARRAYSIZE ((EventType)(EventType_EVENT_TYPE_ONLINE + 1))

#define _TournamentGamesStatus_MIN TournamentGamesStatus_TOURNAMENT_GAMES_STATUS_UNSPECIFIED
#define _TournamentGamesStatus_MAX TournamentGamesStatus_TOURNAMENT_GAMES_STATUS_STARTED
#define _TournamentGamesStatus_ARRAYSIZE \
	((TournamentGamesStatus)(TournamentGamesStatus_TOURNAMENT_GAMES_STATUS_STARTED + 1))

#define _RoundOutcome_MIN RoundOutcome_ROUND_OUTCOME_UNSPECIFIED
#define _RoundOutcome_MAX RoundOutcome_ROUND_OUTCOME_MULTIRON
#define _RoundOutcome_ARRAYSIZE ((RoundOutcome)(RoundOutcome_ROUND_OUTCOME_MULTIRON + 1))

#define _SessionStatus_MIN SessionStatus_SESSION_STATUS_UNSPECIFIED
#define _SessionStatus_MAX SessionStatus_SESSION_STATUS_PLANNED
#define _SessionStatus_ARRAYSIZE ((SessionStatus)(SessionStatus_SESSION_STATUS_PLANNED + 1))

#define _UmaType_MIN UmaType_UMA_TYPE_UNSPECIFIED
#define _UmaType_MAX UmaType_UMA_TYPE_UMA_COMPLEX
#define _UmaType_ARRAYSIZE ((UmaType)(UmaType_UMA_TYPE_UMA_COMPLEX + 1))

#define _EndingPolicy_MIN EndingPolicy_ENDING_POLICY_EP_UNSPECIFIED
#define _EndingPolicy_MAX EndingPolicy_ENDING_POLICY_EP_END_AFTER_HAND
#define _EndingPolicy_ARRAYSIZE ((EndingPolicy)(EndingPolicy_ENDING_POLICY_EP_END_AFTER_HAND + 1))

#define _PlatformType_MIN PlatformType_PLATFORM_TYPE_UNSPECIFIED
#define _PlatformType_MAX PlatformType_PLATFORM_TYPE_MAHJONGSOUL
#define _PlatformType_ARRAYSIZE ((PlatformType)(PlatformType_PLATFORM_TYPE_MAHJONGSOUL + 1))

#define Event_type_ENUMTYPE EventType
#define Event_platform_id_ENUMTYPE PlatformType

#define GameConfig_games_status_ENUMTYPE TournamentGamesStatus

#define RoundState_outcome_ENUMTYPE RoundOutcome

#define EventData_type_ENUMTYPE EventType
#define EventData_platform_id_ENUMTYPE PlatformType

#define TableState_status_ENUMTYPE SessionStatus

#define RulesetConfig_ending_policy_ENUMTYPE EndingPolicy
#define RulesetConfig_uma_type_ENUMTYPE UmaType

/* Initializer values for message structs */
#define EventAdmin_init_default              \
	{                                    \
		0, 0, { { NULL }, NULL }, 0, \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define EventReferee_init_default            \
	{                                    \
		0, 0, { { NULL }, NULL }, 0, \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define Person_init_default                                                       \
	{                                                                         \
		0, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, 0, \
		{                                                                 \
			{ NULL }, NULL                                            \
		}                                                                 \
	}
#define PersonEx_init_default                                                                                          \
	{                                                                                                              \
		0, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
			{ { NULL }, NULL }, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, { { NULL }, NULL },          \
		{                                                                                                      \
			{ NULL }, NULL                                                                                 \
		}                                                                                                      \
	}
#define Country_init_default           \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define Event_init_default                                                                               \
	{                                                                                                \
		0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, 0, 0, _EventType_MIN, 0, 0, 0, 0, 0, 0, \
		0, _PlatformType_MIN                                                                     \
	}
#define MyEvent_init_default { 0, { { NULL }, NULL }, { { NULL }, NULL }, 0 }
#define GameConfig_init_default       \
	{ { { NULL }, NULL },         \
	  { { NULL }, NULL },         \
	  { { NULL }, NULL },         \
	  { { NULL }, NULL },         \
	  0,                          \
	  0,                          \
	  0,                          \
	  { { NULL }, NULL },         \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  _TournamentGamesStatus_MIN, \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  false,                      \
	  RulesetConfig_init_default, \
	  0,                          \
	  0 }
#define PlayerInRating_init_default \
	{ 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, 0, 0, 0, 0, { { NULL }, NULL }, 0, { { NULL }, NULL }, 0, 0 }
#define Player_init_default                                   \
	{                                                     \
		0, { { NULL }, NULL }, { { NULL }, NULL }, 0, \
		{                                             \
			{ NULL }, NULL                        \
		}                                             \
	}
#define FinalResultOfSession_init_default { 0, 0, 0, 0 }
#define Penalty_init_default { 0, 0, { { NULL }, NULL }, 0, { { NULL }, NULL }, 0, { { NULL }, NULL }, 0 }
#define RonResult_init_default { 0, 0, 0, 0, 0, 0, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, 0, 0, 0 }
#define MultironWin_init_default { 0, 0, 0, 0, { { NULL }, NULL }, 0, 0, 0, 0, 0 }
#define MultironResult_init_default             \
	{                                       \
		0, 0, 0, 0, { { NULL }, NULL }, \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define TsumoResult_init_default { 0, 0, 0, 0, 0, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, 0, 0, 0 }
#define DrawResult_init_default           \
	{                                 \
		0, 0, { { NULL }, NULL }, \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define AbortResult_init_default       \
	{                              \
		0, 0,                  \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define ChomboResult_init_default { 0, 0, 0 }
#define NagashiResult_init_default                            \
	{                                                     \
		0, 0, { { NULL }, NULL }, { { NULL }, NULL }, \
		{                                             \
			{ NULL }, NULL                        \
		}                                             \
	}
#define Round_init_default                     \
	{                                      \
		0,                             \
		{                              \
			RonResult_init_default \
		}                              \
	}
#define GameResult_init_default                                                                                     \
	{                                                                                                           \
		{ { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
		{                                                                                                   \
			{ NULL }, NULL                                                                              \
		}                                                                                                   \
	}
#define PlayerPlaceInSeries_init_default { { { NULL }, NULL }, 0 }
#define SeriesResult_init_default                                                                                   \
	{                                                                                                           \
		false, Player_init_default, { { NULL }, NULL }, 0, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, \
		{                                                                                                   \
			{ NULL }, NULL                                                                              \
		}                                                                                                   \
	}
#define ReplacementPlayer_init_default    \
	{                                 \
		0, { { NULL }, NULL }, 0, \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define PlayerInSession_init_default { 0, "", 0, false, ReplacementPlayer_init_default, 0, 0, { { NULL }, NULL }, 0 }
#define RegisteredPlayer_init_default                                                              \
	{                                                                                          \
		0, { { NULL }, NULL }, false, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, false, \
			ReplacementPlayer_init_default, 0,                                         \
		{                                                                                  \
			{ NULL }, NULL                                                             \
		}                                                                                  \
	}
#define SessionHistoryResult_init_default                                 \
	{                                                                 \
		{ { NULL }, NULL }, 0, 0, 0, 0, 0, { { NULL }, NULL }, 0, \
		{                                                         \
			{ NULL }, NULL                                    \
		}                                                         \
	}
#define SessionHistoryResultTable_init_default \
	{                                      \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define PlacesSummaryItem_init_default { 0, 0 }
#define PlayerWinSummary_init_default { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
#define HandValueStat_init_default { 0, 0 }
#define YakuStat_init_default { 0, 0 }
#define RiichiSummary_init_default { 0, 0, 0 }
#define DoraSummary_init_default { 0, 0 }
#define IntermediateResultOfSession_init_default { 0, 0, 0 }
#define PaymentLogItem_init_default { false, 0, false, 0, 0 }
#define PaymentLog_init_default                         \
	{                                               \
		{ { NULL }, NULL }, { { NULL }, NULL }, \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define RoundState_init_default    \
	{ { { NULL }, NULL },      \
	  0,                       \
	  0,                       \
	  0,                       \
	  0,                       \
	  { { NULL }, NULL },      \
	  { { NULL }, NULL },      \
	  { { NULL }, NULL },      \
	  false,                   \
	  PaymentLog_init_default, \
	  false,                   \
	  Round_init_default,      \
	  _RoundOutcome_MIN }
#define EventData_init_default        \
	{ false,                      \
	  _EventType_MIN,             \
	  { { NULL }, NULL },         \
	  { { NULL }, NULL },         \
	  0,                          \
	  { { NULL }, NULL },         \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  false,                      \
	  RulesetConfig_init_default, \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  _PlatformType_MIN }
#define TableState_init_default \
	{ _SessionStatus_MIN,   \
	  0,                    \
	  { { NULL }, NULL },   \
	  false,                \
	  0,                    \
	  false,                \
	  Round_init_default,   \
	  0,                    \
	  { { NULL }, NULL },   \
	  { { NULL }, NULL },   \
	  false,                \
	  0 }
#define Achievement_init_default       \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define LocalIdMapping_init_default { 0, 0 }
#define TeamMapping_init_default       \
	{                              \
		0,                     \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define PlayerSeating_init_default                    \
	{                                             \
		0, 0, 0, 0, 0, { { NULL }, NULL }, 0, \
		{                                     \
			{ NULL }, NULL                \
		}                                     \
	}
#define PlayerSeatingSwiss_init_default { 0, 0 }
#define TableItemSwiss_init_default    \
	{                              \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define PrescriptedTable_init_default  \
	{                              \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define Chombo_init_default { 0, 0 }
#define SessionState_init_default                     \
	{                                             \
		0, 0, 0, 0, { { NULL }, NULL }, 0, 0, \
		{                                     \
			{ NULL }, NULL                \
		}                                     \
	}
#define Uma_init_default { 0, 0, 0, 0 }
#define ComplexUma_init_default { false, Uma_init_default, false, Uma_init_default, false, Uma_init_default }
#define RulesetConfig_init_default                                                                                     \
	{                                                                                                              \
		false, ComplexUma_init_default, _EndingPolicy_MIN, false, Uma_init_default, _UmaType_MIN, 0, 0, 0, 0,  \
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, { { NULL }, NULL }, \
			{ { NULL }, NULL }, 0, 0, 0, 0,                                                                \
		{                                                                                                      \
			{ NULL }, NULL                                                                                 \
		}                                                                                                      \
	}
#define MajsoulSearchEx_init_default { { { NULL }, NULL }, 0 }
#define MajsoulPersonMapping_init_default \
	{                                 \
		0,                        \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define GenericSuccessResponse_init_default { 0 }
#define GenericEventPayload_init_default { 0 }
#define GenericSessionPayload_init_default \
	{                                  \
		{                          \
			{ NULL }, NULL     \
		}                          \
	}
#define EventAdmin_init_zero                 \
	{                                    \
		0, 0, { { NULL }, NULL }, 0, \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define EventReferee_init_zero               \
	{                                    \
		0, 0, { { NULL }, NULL }, 0, \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define Person_init_zero                                                          \
	{                                                                         \
		0, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, 0, \
		{                                                                 \
			{ NULL }, NULL                                            \
		}                                                                 \
	}
#define PersonEx_init_zero                                                                                             \
	{                                                                                                              \
		0, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
			{ { NULL }, NULL }, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, { { NULL }, NULL },          \
		{                                                                                                      \
			{ NULL }, NULL                                                                                 \
		}                                                                                                      \
	}
#define Country_init_zero              \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define Event_init_zero                                                                                  \
	{                                                                                                \
		0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, 0, 0, _EventType_MIN, 0, 0, 0, 0, 0, 0, \
		0, _PlatformType_MIN                                                                     \
	}
#define MyEvent_init_zero { 0, { { NULL }, NULL }, { { NULL }, NULL }, 0 }
#define GameConfig_init_zero          \
	{ { { NULL }, NULL },         \
	  { { NULL }, NULL },         \
	  { { NULL }, NULL },         \
	  { { NULL }, NULL },         \
	  0,                          \
	  0,                          \
	  0,                          \
	  { { NULL }, NULL },         \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  _TournamentGamesStatus_MIN, \
	  0,                          \
	  0,                          \
	  0,                          \
	  0,                          \
	  false,                      \
	  RulesetConfig_init_zero,    \
	  0,                          \
	  0 }
#define PlayerInRating_init_zero \
	{ 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, 0, 0, 0, 0, { { NULL }, NULL }, 0, { { NULL }, NULL }, 0, 0 }
#define Player_init_zero                                      \
	{                                                     \
		0, { { NULL }, NULL }, { { NULL }, NULL }, 0, \
		{                                             \
			{ NULL }, NULL                        \
		}                                             \
	}
#define FinalResultOfSession_init_zero { 0, 0, 0, 0 }
#define Penalty_init_zero { 0, 0, { { NULL }, NULL }, 0, { { NULL }, NULL }, 0, { { NULL }, NULL }, 0 }
#define RonResult_init_zero { 0, 0, 0, 0, 0, 0, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, 0, 0, 0 }
#define MultironWin_init_zero { 0, 0, 0, 0, { { NULL }, NULL }, 0, 0, 0, 0, 0 }
#define MultironResult_init_zero                \
	{                                       \
		0, 0, 0, 0, { { NULL }, NULL }, \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define TsumoResult_init_zero { 0, 0, 0, 0, 0, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, 0, 0, 0 }
#define DrawResult_init_zero              \
	{                                 \
		0, 0, { { NULL }, NULL }, \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define AbortResult_init_zero          \
	{                              \
		0, 0,                  \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define ChomboResult_init_zero { 0, 0, 0 }
#define NagashiResult_init_zero                               \
	{                                                     \
		0, 0, { { NULL }, NULL }, { { NULL }, NULL }, \
		{                                             \
			{ NULL }, NULL                        \
		}                                             \
	}
#define Round_init_zero                     \
	{                                   \
		0,                          \
		{                           \
			RonResult_init_zero \
		}                           \
	}
#define GameResult_init_zero                                                                                        \
	{                                                                                                           \
		{ { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
		{                                                                                                   \
			{ NULL }, NULL                                                                              \
		}                                                                                                   \
	}
#define PlayerPlaceInSeries_init_zero { { { NULL }, NULL }, 0 }
#define SeriesResult_init_zero                                                                                   \
	{                                                                                                        \
		false, Player_init_zero, { { NULL }, NULL }, 0, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, \
		{                                                                                                \
			{ NULL }, NULL                                                                           \
		}                                                                                                \
	}
#define ReplacementPlayer_init_zero       \
	{                                 \
		0, { { NULL }, NULL }, 0, \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define PlayerInSession_init_zero { 0, "", 0, false, ReplacementPlayer_init_zero, 0, 0, { { NULL }, NULL }, 0 }
#define RegisteredPlayer_init_zero                                                                 \
	{                                                                                          \
		0, { { NULL }, NULL }, false, 0, { { NULL }, NULL }, { { NULL }, NULL }, 0, false, \
			ReplacementPlayer_init_zero, 0,                                            \
		{                                                                                  \
			{ NULL }, NULL                                                             \
		}                                                                                  \
	}
#define SessionHistoryResult_init_zero                                    \
	{                                                                 \
		{ { NULL }, NULL }, 0, 0, 0, 0, 0, { { NULL }, NULL }, 0, \
		{                                                         \
			{ NULL }, NULL                                    \
		}                                                         \
	}
#define SessionHistoryResultTable_init_zero \
	{                                   \
		{                           \
			{ NULL }, NULL      \
		}                           \
	}
#define PlacesSummaryItem_init_zero { 0, 0 }
#define PlayerWinSummary_init_zero { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
#define HandValueStat_init_zero { 0, 0 }
#define YakuStat_init_zero { 0, 0 }
#define RiichiSummary_init_zero { 0, 0, 0 }
#define DoraSummary_init_zero { 0, 0 }
#define IntermediateResultOfSession_init_zero { 0, 0, 0 }
#define PaymentLogItem_init_zero { false, 0, false, 0, 0 }
#define PaymentLog_init_zero                            \
	{                                               \
		{ { NULL }, NULL }, { { NULL }, NULL }, \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define RoundState_init_zero    \
	{ { { NULL }, NULL },   \
	  0,                    \
	  0,                    \
	  0,                    \
	  0,                    \
	  { { NULL }, NULL },   \
	  { { NULL }, NULL },   \
	  { { NULL }, NULL },   \
	  false,                \
	  PaymentLog_init_zero, \
	  false,                \
	  Round_init_zero,      \
	  _RoundOutcome_MIN }
#define EventData_init_zero        \
	{ false,                   \
	  _EventType_MIN,          \
	  { { NULL }, NULL },      \
	  { { NULL }, NULL },      \
	  0,                       \
	  { { NULL }, NULL },      \
	  0,                       \
	  0,                       \
	  0,                       \
	  0,                       \
	  0,                       \
	  0,                       \
	  false,                   \
	  RulesetConfig_init_zero, \
	  0,                       \
	  0,                       \
	  0,                       \
	  0,                       \
	  _PlatformType_MIN }
#define TableState_init_zero  \
	{ _SessionStatus_MIN, \
	  0,                  \
	  { { NULL }, NULL }, \
	  false,              \
	  0,                  \
	  false,              \
	  Round_init_zero,    \
	  0,                  \
	  { { NULL }, NULL }, \
	  { { NULL }, NULL }, \
	  false,              \
	  0 }
#define Achievement_init_zero          \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define LocalIdMapping_init_zero { 0, 0 }
#define TeamMapping_init_zero          \
	{                              \
		0,                     \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define PlayerSeating_init_zero                       \
	{                                             \
		0, 0, 0, 0, 0, { { NULL }, NULL }, 0, \
		{                                     \
			{ NULL }, NULL                \
		}                                     \
	}
#define PlayerSeatingSwiss_init_zero { 0, 0 }
#define TableItemSwiss_init_zero       \
	{                              \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define PrescriptedTable_init_zero     \
	{                              \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define Chombo_init_zero { 0, 0 }
#define SessionState_init_zero                        \
	{                                             \
		0, 0, 0, 0, { { NULL }, NULL }, 0, 0, \
		{                                     \
			{ NULL }, NULL                \
		}                                     \
	}
#define Uma_init_zero { 0, 0, 0, 0 }
#define ComplexUma_init_zero { false, Uma_init_zero, false, Uma_init_zero, false, Uma_init_zero }
#define RulesetConfig_init_zero                                                                                       \
	{                                                                                                             \
		false, ComplexUma_init_zero, _EndingPolicy_MIN, false, Uma_init_zero, _UmaType_MIN, 0, 0, 0, 0, 0, 0, \
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, { { NULL }, NULL },      \
			{ { NULL }, NULL }, 0, 0, 0, 0,                                                               \
		{                                                                                                     \
			{ NULL }, NULL                                                                                \
		}                                                                                                     \
	}
#define MajsoulSearchEx_init_zero { { { NULL }, NULL }, 0 }
#define MajsoulPersonMapping_init_zero \
	{                              \
		0,                     \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define GenericSuccessResponse_init_zero { 0 }
#define GenericEventPayload_init_zero { 0 }
#define GenericSessionPayload_init_zero \
	{                               \
		{                       \
			{ NULL }, NULL  \
		}                       \
	}

/* Field tags (for use in manual encoding/decoding) */
#define EventAdmin_rule_id_tag 1
#define EventAdmin_person_id_tag 2
#define EventAdmin_person_name_tag 3
#define EventAdmin_has_avatar_tag 4
#define EventAdmin_last_update_tag 5
#define EventReferee_rule_id_tag 1
#define EventReferee_person_id_tag 2
#define EventReferee_person_name_tag 3
#define EventReferee_has_avatar_tag 4
#define EventReferee_last_update_tag 5
#define Person_id_tag 1
#define Person_city_tag 2
#define Person_tenhou_id_tag 3
#define Person_title_tag 4
#define Person_has_avatar_tag 5
#define Person_last_update_tag 6
#define PersonEx_id_tag 1
#define PersonEx_city_tag 2
#define PersonEx_tenhou_id_tag 3
#define PersonEx_title_tag 4
#define PersonEx_country_tag 5
#define PersonEx_email_tag 6
#define PersonEx_phone_tag 7
#define PersonEx_has_avatar_tag 9
#define PersonEx_last_update_tag 10
#define PersonEx_ms_nickname_tag 11
#define PersonEx_ms_account_id_tag 12
#define PersonEx_telegram_id_tag 13
#define PersonEx_notifications_tag 14
#define Country_code_tag 1
#define Country_name_tag 2
#define Event_id_tag 1
#define Event_title_tag 2
#define Event_description_tag 3
#define Event_finished_tag 4
#define Event_is_listed_tag 5
#define Event_is_rating_shown_tag 6
#define Event_tournament_started_tag 7
#define Event_type_tag 8
#define Event_is_prescripted_tag 9
#define Event_is_team_tag 10
#define Event_has_series_tag 11
#define Event_with_chips_tag 12
#define Event_min_games_count_tag 13
#define Event_achievements_shown_tag 15
#define Event_with_yakitori_tag 16
#define Event_platform_id_tag 17
#define MyEvent_id_tag 1
#define MyEvent_title_tag 2
#define MyEvent_description_tag 3
#define MyEvent_is_online_tag 4
#define PlayerInRating_id_tag 1
#define PlayerInRating_title_tag 2
#define PlayerInRating_tenhou_id_tag 3
#define PlayerInRating_rating_tag 4
#define PlayerInRating_chips_tag 5
#define PlayerInRating_winner_zone_tag 6
#define PlayerInRating_avg_place_tag 7
#define PlayerInRating_avg_score_tag 8
#define PlayerInRating_games_played_tag 9
#define PlayerInRating_team_name_tag 10
#define PlayerInRating_has_avatar_tag 11
#define PlayerInRating_last_update_tag 12
#define PlayerInRating_penalties_amount_tag 13
#define PlayerInRating_penalties_count_tag 14
#define Player_id_tag 1
#define Player_title_tag 2
#define Player_tenhou_id_tag 3
#define Player_has_avatar_tag 4
#define Player_last_update_tag 5
#define FinalResultOfSession_player_id_tag 1
#define FinalResultOfSession_score_tag 2
#define FinalResultOfSession_rating_delta_tag 3
#define FinalResultOfSession_place_tag 4
#define Penalty_who_tag 1
#define Penalty_amount_tag 2
#define Penalty_reason_tag 3
#define Penalty_assigned_by_tag 4
#define Penalty_created_at_tag 5
#define Penalty_is_cancelled_tag 6
#define Penalty_cancellation_reason_tag 7
#define Penalty_id_tag 8
#define RonResult_round_index_tag 1
#define RonResult_honba_tag 2
#define RonResult_winner_id_tag 3
#define RonResult_loser_id_tag 4
#define RonResult_pao_player_id_tag 5
#define RonResult_han_tag 6
#define RonResult_fu_tag 7
#define RonResult_yaku_tag 8
#define RonResult_riichi_bets_tag 9
#define RonResult_dora_tag 10
#define RonResult_uradora_tag 11
#define RonResult_kandora_tag 12
#define RonResult_kanuradora_tag 13
#define RonResult_open_hand_tag 14
#define MultironWin_winner_id_tag 1
#define MultironWin_pao_player_id_tag 2
#define MultironWin_han_tag 3
#define MultironWin_fu_tag 4
#define MultironWin_yaku_tag 5
#define MultironWin_dora_tag 6
#define MultironWin_uradora_tag 7
#define MultironWin_kandora_tag 8
#define MultironWin_kanuradora_tag 9
#define MultironWin_open_hand_tag 10
#define MultironResult_round_index_tag 1
#define MultironResult_honba_tag 2
#define MultironResult_loser_id_tag 3
#define MultironResult_multi_ron_tag 4
#define MultironResult_wins_tag 5
#define MultironResult_riichi_bets_tag 6
#define TsumoResult_round_index_tag 1
#define TsumoResult_honba_tag 2
#define TsumoResult_winner_id_tag 3
#define TsumoResult_pao_player_id_tag 4
#define TsumoResult_han_tag 5
#define TsumoResult_fu_tag 6
#define TsumoResult_yaku_tag 7
#define TsumoResult_riichi_bets_tag 8
#define TsumoResult_dora_tag 9
#define TsumoResult_uradora_tag 10
#define TsumoResult_kandora_tag 11
#define TsumoResult_kanuradora_tag 12
#define TsumoResult_open_hand_tag 13
#define DrawResult_round_index_tag 1
#define DrawResult_honba_tag 2
#define DrawResult_riichi_bets_tag 3
#define DrawResult_tempai_tag 4
#define AbortResult_round_index_tag 1
#define AbortResult_honba_tag 2
#define AbortResult_riichi_bets_tag 3
#define ChomboResult_round_index_tag 1
#define ChomboResult_honba_tag 2
#define ChomboResult_loser_id_tag 3
#define NagashiResult_round_index_tag 1
#define NagashiResult_honba_tag 2
#define NagashiResult_riichi_bets_tag 3
#define NagashiResult_tempai_tag 4
#define NagashiResult_nagashi_tag 5
#define Round_ron_tag 1
#define Round_tsumo_tag 2
#define Round_multiron_tag 3
#define Round_draw_tag 4
#define Round_abort_tag 5
#define Round_chombo_tag 6
#define Round_nagashi_tag 7
#define GameResult_session_hash_tag 1
#define GameResult_date_tag 2
#define GameResult_replay_link_tag 3
#define GameResult_players_tag 4
#define GameResult_final_results_tag 5
#define GameResult_rounds_tag 7
#define PlayerPlaceInSeries_session_hash_tag 1
#define PlayerPlaceInSeries_place_tag 2
#define SeriesResult_player_tag 1
#define SeriesResult_best_series_tag 2
#define SeriesResult_best_series_scores_tag 3
#define SeriesResult_best_series_places_tag 4
#define SeriesResult_best_series_avg_place_tag 5
#define SeriesResult_current_series_tag 6
#define SeriesResult_current_series_scores_tag 7
#define SeriesResult_current_series_places_tag 8
#define SeriesResult_current_series_avg_place_tag 9
#define ReplacementPlayer_id_tag 1
#define ReplacementPlayer_title_tag 2
#define ReplacementPlayer_has_avatar_tag 3
#define ReplacementPlayer_last_update_tag 4
#define PlayerInSession_id_tag 1
#define PlayerInSession_title_tag 2
#define PlayerInSession_score_tag 3
#define PlayerInSession_replaced_by_tag 4
#define PlayerInSession_rating_delta_tag 5
#define PlayerInSession_has_avatar_tag 6
#define PlayerInSession_last_update_tag 7
#define PlayerInSession_yakitori_tag 8
#define RegisteredPlayer_id_tag 1
#define RegisteredPlayer_title_tag 2
#define RegisteredPlayer_local_id_tag 3
#define RegisteredPlayer_team_name_tag 4
#define RegisteredPlayer_tenhou_id_tag 5
#define RegisteredPlayer_ignore_seating_tag 6
#define RegisteredPlayer_replaced_by_tag 7
#define RegisteredPlayer_has_avatar_tag 8
#define RegisteredPlayer_last_update_tag 9
#define SessionHistoryResult_session_hash_tag 1
#define SessionHistoryResult_event_id_tag 2
#define SessionHistoryResult_player_id_tag 3
#define SessionHistoryResult_score_tag 4
#define SessionHistoryResult_rating_delta_tag 5
#define SessionHistoryResult_place_tag 6
#define SessionHistoryResult_title_tag 7
#define SessionHistoryResult_has_avatar_tag 8
#define SessionHistoryResult_last_update_tag 9
#define SessionHistoryResultTable_tables_tag 1
#define PlacesSummaryItem_place_tag 1
#define PlacesSummaryItem_count_tag 2
#define PlayerWinSummary_ron_tag 1
#define PlayerWinSummary_tsumo_tag 2
#define PlayerWinSummary_chombo_tag 3
#define PlayerWinSummary_feed_tag 4
#define PlayerWinSummary_tsumofeed_tag 5
#define PlayerWinSummary_wins_with_open_tag 6
#define PlayerWinSummary_wins_with_riichi_tag 7
#define PlayerWinSummary_wins_with_dama_tag 8
#define PlayerWinSummary_unforced_feed_to_open_tag 9
#define PlayerWinSummary_unforced_feed_to_riichi_tag 10
#define PlayerWinSummary_unforced_feed_to_dama_tag 11
#define PlayerWinSummary_draw_tag 12
#define PlayerWinSummary_draw_tempai_tag 13
#define PlayerWinSummary_points_won_tag 14
#define PlayerWinSummary_points_lost_ron_tag 15
#define PlayerWinSummary_points_lost_tsumo_tag 16
#define HandValueStat_han_count_tag 1
#define HandValueStat_count_tag 2
#define YakuStat_yaku_id_tag 1
#define YakuStat_count_tag 2
#define RiichiSummary_riichi_won_tag 1
#define RiichiSummary_riichi_lost_tag 2
#define RiichiSummary_feed_under_riichi_tag 3
#define DoraSummary_count_tag 1
#define DoraSummary_average_tag 2
#define IntermediateResultOfSession_player_id_tag 1
#define IntermediateResultOfSession_score_tag 2
#define IntermediateResultOfSession_chombo_count_tag 4
#define PaymentLogItem_from_tag 1
#define PaymentLogItem_to_tag 2
#define PaymentLogItem_amount_tag 3
#define PaymentLog_direct_tag 1
#define PaymentLog_riichi_tag 2
#define PaymentLog_honba_tag 3
#define RoundState_session_hash_tag 1
#define RoundState_dealer_tag 2
#define RoundState_round_index_tag 3
#define RoundState_riichi_tag 4
#define RoundState_honba_tag 5
#define RoundState_riichi_ids_tag 6
#define RoundState_scores_tag 7
#define RoundState_scores_delta_tag 8
#define RoundState_payments_tag 9
#define RoundState_round_tag 10
#define RoundState_outcome_tag 11
#define TableState_status_tag 1
#define TableState_may_definalize_tag 2
#define TableState_session_hash_tag 3
#define TableState_table_index_tag 5
#define TableState_last_round_tag 6
#define TableState_current_round_index_tag 7
#define TableState_scores_tag 8
#define TableState_players_tag 9
#define TableState_extra_time_tag 10
#define Achievement_achievement_id_tag 1
#define Achievement_achievement_data_tag 2
#define LocalIdMapping_player_id_tag 1
#define LocalIdMapping_local_id_tag 2
#define TeamMapping_player_id_tag 1
#define TeamMapping_team_name_tag 2
#define PlayerSeating_order_tag 1
#define PlayerSeating_player_id_tag 2
#define PlayerSeating_session_id_tag 3
#define PlayerSeating_table_index_tag 4
#define PlayerSeating_rating_tag 5
#define PlayerSeating_player_title_tag 6
#define PlayerSeating_has_avatar_tag 7
#define PlayerSeating_last_update_tag 8
#define PlayerSeatingSwiss_player_id_tag 1
#define PlayerSeatingSwiss_rating_tag 2
#define TableItemSwiss_players_tag 1
#define PrescriptedTable_players_tag 1
#define Chombo_player_id_tag 1
#define Chombo_amount_tag 2
#define SessionState_dealer_tag 1
#define SessionState_round_index_tag 2
#define SessionState_riichi_count_tag 3
#define SessionState_honba_count_tag 4
#define SessionState_scores_tag 5
#define SessionState_finished_tag 6
#define SessionState_last_hand_started_tag 8
#define SessionState_chombo_tag 9
#define Uma_place1_tag 1
#define Uma_place2_tag 2
#define Uma_place3_tag 3
#define Uma_place4_tag 4
#define ComplexUma_neg1_tag 1
#define ComplexUma_neg3_tag 2
#define ComplexUma_otherwise_tag 3
#define RulesetConfig_complex_uma_tag 1
#define RulesetConfig_ending_policy_tag 2
#define RulesetConfig_uma_tag 3
#define RulesetConfig_uma_type_tag 4
#define RulesetConfig_doubleron_honba_atamahane_tag 5
#define RulesetConfig_doubleron_riichi_atamahane_tag 6
#define RulesetConfig_equalize_uma_tag 7
#define RulesetConfig_extra_chombo_payments_tag 8
#define RulesetConfig_play_additional_rounds_tag 9
#define RulesetConfig_riichi_goes_to_winner_tag 10
#define RulesetConfig_tonpuusen_tag 11
#define RulesetConfig_with_abortives_tag 12
#define RulesetConfig_with_atamahane_tag 13
#define RulesetConfig_with_buttobi_tag 14
#define RulesetConfig_with_kazoe_tag 15
#define RulesetConfig_with_kiriage_mangan_tag 16
#define RulesetConfig_with_kuitan_tag 17
#define RulesetConfig_with_leading_dealer_game_over_tag 18
#define RulesetConfig_with_multi_yakumans_tag 19
#define RulesetConfig_with_nagashi_mangan_tag 20
#define RulesetConfig_with_winning_dealer_honba_skipped_tag 21
#define RulesetConfig_chips_value_tag 22
#define RulesetConfig_chombo_amount_tag 23
#define RulesetConfig_game_expiration_time_tag 24
#define RulesetConfig_goal_points_tag 25
#define RulesetConfig_max_penalty_tag 26
#define RulesetConfig_min_penalty_tag 27
#define RulesetConfig_oka_tag 28
#define RulesetConfig_penalty_step_tag 29
#define RulesetConfig_replacement_player_fixed_points_tag 30
#define RulesetConfig_replacement_player_override_uma_tag 31
#define RulesetConfig_start_points_tag 32
#define RulesetConfig_start_rating_tag 33
#define RulesetConfig_allowed_yaku_tag 34
#define RulesetConfig_yaku_with_pao_tag 35
#define RulesetConfig_with_yakitori_tag 36
#define RulesetConfig_yakitori_penalty_tag 37
#define RulesetConfig_chombo_ends_game_tag 38
#define RulesetConfig_honba_value_tag 39
#define RulesetConfig_double_yakuman_tag 40
#define GameConfig_ruleset_title_tag 10
#define GameConfig_event_title_tag 26
#define GameConfig_event_description_tag 27
#define GameConfig_event_stat_host_tag 28
#define GameConfig_use_timer_tag 29
#define GameConfig_use_penalty_tag 30
#define GameConfig_game_duration_tag 34
#define GameConfig_timezone_tag 35
#define GameConfig_is_online_tag 36
#define GameConfig_is_team_tag 37
#define GameConfig_auto_seating_tag 38
#define GameConfig_sync_start_tag 39
#define GameConfig_sync_end_tag 40
#define GameConfig_sort_by_games_tag 41
#define GameConfig_allow_player_append_tag 42
#define GameConfig_series_length_tag 45
#define GameConfig_min_games_count_tag 46
#define GameConfig_games_status_tag 47
#define GameConfig_hide_results_tag 48
#define GameConfig_hide_add_replay_button_tag 49
#define GameConfig_is_prescripted_tag 50
#define GameConfig_is_finished_tag 52
#define GameConfig_ruleset_config_tag 53
#define GameConfig_lobby_id_tag 54
#define GameConfig_allow_view_other_tables_tag 55
#define EventData_type_tag 1
#define EventData_title_tag 2
#define EventData_description_tag 3
#define EventData_duration_tag 4
#define EventData_timezone_tag 6
#define EventData_lobby_id_tag 7
#define EventData_series_length_tag 8
#define EventData_min_games_tag 9
#define EventData_is_team_tag 10
#define EventData_is_prescripted_tag 11
#define EventData_autostart_tag 12
#define EventData_ruleset_config_tag 14
#define EventData_is_listed_tag 15
#define EventData_is_rating_shown_tag 16
#define EventData_achievements_shown_tag 17
#define EventData_allow_view_other_tables_tag 18
#define EventData_platform_id_tag 19
#define MajsoulSearchEx_nickname_tag 1
#define MajsoulSearchEx_account_id_tag 2
#define MajsoulPersonMapping_person_id_tag 1
#define MajsoulPersonMapping_nickname_tag 2
#define GenericSuccessResponse_success_tag 1
#define GenericEventPayload_event_id_tag 1
#define GenericSessionPayload_session_hash_tag 1

/* Struct field encoding specification for nanopb */
#define EventAdmin_FIELDLIST(X, a)                       \
	X(a, STATIC, SINGULAR, INT32, rule_id, 1)        \
	X(a, STATIC, SINGULAR, INT32, person_id, 2)      \
	X(a, CALLBACK, SINGULAR, STRING, person_name, 3) \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 4)      \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 5)
#define EventAdmin_CALLBACK pb_default_field_callback
#define EventAdmin_DEFAULT NULL

#define EventReferee_FIELDLIST(X, a)                     \
	X(a, STATIC, SINGULAR, INT32, rule_id, 1)        \
	X(a, STATIC, SINGULAR, INT32, person_id, 2)      \
	X(a, CALLBACK, SINGULAR, STRING, person_name, 3) \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 4)      \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 5)
#define EventReferee_CALLBACK pb_default_field_callback
#define EventReferee_DEFAULT NULL

#define Person_FIELDLIST(X, a)                         \
	X(a, STATIC, SINGULAR, INT32, id, 1)           \
	X(a, CALLBACK, SINGULAR, STRING, city, 2)      \
	X(a, CALLBACK, SINGULAR, STRING, tenhou_id, 3) \
	X(a, CALLBACK, SINGULAR, STRING, title, 4)     \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 5)    \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 6)
#define Person_CALLBACK pb_default_field_callback
#define Person_DEFAULT NULL

#define PersonEx_FIELDLIST(X, a)                          \
	X(a, STATIC, SINGULAR, INT32, id, 1)              \
	X(a, CALLBACK, SINGULAR, STRING, city, 2)         \
	X(a, CALLBACK, SINGULAR, STRING, tenhou_id, 3)    \
	X(a, CALLBACK, SINGULAR, STRING, title, 4)        \
	X(a, CALLBACK, SINGULAR, STRING, country, 5)      \
	X(a, CALLBACK, SINGULAR, STRING, email, 6)        \
	X(a, CALLBACK, SINGULAR, STRING, phone, 7)        \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 9)       \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 10) \
	X(a, CALLBACK, SINGULAR, STRING, ms_nickname, 11) \
	X(a, STATIC, SINGULAR, INT32, ms_account_id, 12)  \
	X(a, CALLBACK, SINGULAR, STRING, telegram_id, 13) \
	X(a, CALLBACK, SINGULAR, STRING, notifications, 14)
#define PersonEx_CALLBACK pb_default_field_callback
#define PersonEx_DEFAULT NULL

#define Country_FIELDLIST(X, a)                   \
	X(a, CALLBACK, SINGULAR, STRING, code, 1) \
	X(a, CALLBACK, SINGULAR, STRING, name, 2)
#define Country_CALLBACK pb_default_field_callback
#define Country_DEFAULT NULL

#define Event_FIELDLIST(X, a)                                \
	X(a, STATIC, SINGULAR, INT32, id, 1)                 \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)           \
	X(a, CALLBACK, SINGULAR, STRING, description, 3)     \
	X(a, STATIC, SINGULAR, BOOL, finished, 4)            \
	X(a, STATIC, SINGULAR, BOOL, is_listed, 5)           \
	X(a, STATIC, SINGULAR, BOOL, is_rating_shown, 6)     \
	X(a, STATIC, SINGULAR, BOOL, tournament_started, 7)  \
	X(a, STATIC, SINGULAR, UENUM, type, 8)               \
	X(a, STATIC, SINGULAR, BOOL, is_prescripted, 9)      \
	X(a, STATIC, SINGULAR, BOOL, is_team, 10)            \
	X(a, STATIC, SINGULAR, BOOL, has_series, 11)         \
	X(a, STATIC, SINGULAR, BOOL, with_chips, 12)         \
	X(a, STATIC, SINGULAR, INT32, min_games_count, 13)   \
	X(a, STATIC, SINGULAR, BOOL, achievements_shown, 15) \
	X(a, STATIC, SINGULAR, BOOL, with_yakitori, 16)      \
	X(a, STATIC, SINGULAR, UENUM, platform_id, 17)
#define Event_CALLBACK pb_default_field_callback
#define Event_DEFAULT NULL

#define MyEvent_FIELDLIST(X, a)                          \
	X(a, STATIC, SINGULAR, INT32, id, 1)             \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)       \
	X(a, CALLBACK, SINGULAR, STRING, description, 3) \
	X(a, STATIC, SINGULAR, BOOL, is_online, 4)
#define MyEvent_CALLBACK pb_default_field_callback
#define MyEvent_DEFAULT NULL

#define GameConfig_FIELDLIST(X, a)                               \
	X(a, CALLBACK, SINGULAR, STRING, ruleset_title, 10)      \
	X(a, CALLBACK, SINGULAR, STRING, event_title, 26)        \
	X(a, CALLBACK, SINGULAR, STRING, event_description, 27)  \
	X(a, CALLBACK, SINGULAR, STRING, event_stat_host, 28)    \
	X(a, STATIC, SINGULAR, BOOL, use_timer, 29)              \
	X(a, STATIC, SINGULAR, BOOL, use_penalty, 30)            \
	X(a, STATIC, SINGULAR, INT32, game_duration, 34)         \
	X(a, CALLBACK, SINGULAR, STRING, timezone, 35)           \
	X(a, STATIC, SINGULAR, BOOL, is_online, 36)              \
	X(a, STATIC, SINGULAR, BOOL, is_team, 37)                \
	X(a, STATIC, SINGULAR, BOOL, auto_seating, 38)           \
	X(a, STATIC, SINGULAR, BOOL, sync_start, 39)             \
	X(a, STATIC, SINGULAR, BOOL, sync_end, 40)               \
	X(a, STATIC, SINGULAR, BOOL, sort_by_games, 41)          \
	X(a, STATIC, SINGULAR, BOOL, allow_player_append, 42)    \
	X(a, STATIC, SINGULAR, INT32, series_length, 45)         \
	X(a, STATIC, SINGULAR, INT32, min_games_count, 46)       \
	X(a, STATIC, SINGULAR, UENUM, games_status, 47)          \
	X(a, STATIC, SINGULAR, BOOL, hide_results, 48)           \
	X(a, STATIC, SINGULAR, BOOL, hide_add_replay_button, 49) \
	X(a, STATIC, SINGULAR, BOOL, is_prescripted, 50)         \
	X(a, STATIC, SINGULAR, BOOL, is_finished, 52)            \
	X(a, STATIC, OPTIONAL, MESSAGE, ruleset_config, 53)      \
	X(a, STATIC, SINGULAR, INT32, lobby_id, 54)              \
	X(a, STATIC, SINGULAR, BOOL, allow_view_other_tables, 55)
#define GameConfig_CALLBACK pb_default_field_callback
#define GameConfig_DEFAULT NULL
#define GameConfig_ruleset_config_MSGTYPE RulesetConfig

#define PlayerInRating_FIELDLIST(X, a)                      \
	X(a, STATIC, SINGULAR, INT32, id, 1)                \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)          \
	X(a, CALLBACK, SINGULAR, STRING, tenhou_id, 3)      \
	X(a, STATIC, SINGULAR, FLOAT, rating, 4)            \
	X(a, STATIC, SINGULAR, INT32, chips, 5)             \
	X(a, STATIC, SINGULAR, BOOL, winner_zone, 6)        \
	X(a, STATIC, SINGULAR, FLOAT, avg_place, 7)         \
	X(a, STATIC, SINGULAR, FLOAT, avg_score, 8)         \
	X(a, STATIC, SINGULAR, INT32, games_played, 9)      \
	X(a, CALLBACK, OPTIONAL, STRING, team_name, 10)     \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 11)        \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 12)   \
	X(a, STATIC, SINGULAR, FLOAT, penalties_amount, 13) \
	X(a, STATIC, SINGULAR, INT32, penalties_count, 14)
#define PlayerInRating_CALLBACK pb_default_field_callback
#define PlayerInRating_DEFAULT NULL

#define Player_FIELDLIST(X, a)                         \
	X(a, STATIC, SINGULAR, INT32, id, 1)           \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)     \
	X(a, CALLBACK, SINGULAR, STRING, tenhou_id, 3) \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 4)    \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 5)
#define Player_CALLBACK pb_default_field_callback
#define Player_DEFAULT NULL

#define FinalResultOfSession_FIELDLIST(X, a)           \
	X(a, STATIC, SINGULAR, INT32, player_id, 1)    \
	X(a, STATIC, SINGULAR, INT32, score, 2)        \
	X(a, STATIC, SINGULAR, FLOAT, rating_delta, 3) \
	X(a, STATIC, SINGULAR, INT32, place, 4)
#define FinalResultOfSession_CALLBACK NULL
#define FinalResultOfSession_DEFAULT NULL

#define Penalty_FIELDLIST(X, a)                                  \
	X(a, STATIC, SINGULAR, INT32, who, 1)                    \
	X(a, STATIC, SINGULAR, INT32, amount, 2)                 \
	X(a, CALLBACK, OPTIONAL, STRING, reason, 3)              \
	X(a, STATIC, SINGULAR, INT32, assigned_by, 4)            \
	X(a, CALLBACK, SINGULAR, STRING, created_at, 5)          \
	X(a, STATIC, SINGULAR, BOOL, is_cancelled, 6)            \
	X(a, CALLBACK, OPTIONAL, STRING, cancellation_reason, 7) \
	X(a, STATIC, SINGULAR, INT32, id, 8)
#define Penalty_CALLBACK pb_default_field_callback
#define Penalty_DEFAULT NULL

#define RonResult_FIELDLIST(X, a)                       \
	X(a, STATIC, SINGULAR, INT32, round_index, 1)   \
	X(a, STATIC, SINGULAR, INT32, honba, 2)         \
	X(a, STATIC, SINGULAR, INT32, winner_id, 3)     \
	X(a, STATIC, SINGULAR, INT32, loser_id, 4)      \
	X(a, STATIC, SINGULAR, INT32, pao_player_id, 5) \
	X(a, STATIC, SINGULAR, INT32, han, 6)           \
	X(a, STATIC, SINGULAR, INT32, fu, 7)            \
	X(a, CALLBACK, REPEATED, INT32, yaku, 8)        \
	X(a, CALLBACK, REPEATED, INT32, riichi_bets, 9) \
	X(a, STATIC, SINGULAR, INT32, dora, 10)         \
	X(a, STATIC, SINGULAR, INT32, uradora, 11)      \
	X(a, STATIC, SINGULAR, INT32, kandora, 12)      \
	X(a, STATIC, SINGULAR, INT32, kanuradora, 13)   \
	X(a, STATIC, SINGULAR, BOOL, open_hand, 14)
#define RonResult_CALLBACK pb_default_field_callback
#define RonResult_DEFAULT NULL

#define MultironWin_FIELDLIST(X, a)                     \
	X(a, STATIC, SINGULAR, INT32, winner_id, 1)     \
	X(a, STATIC, SINGULAR, INT32, pao_player_id, 2) \
	X(a, STATIC, SINGULAR, INT32, han, 3)           \
	X(a, STATIC, SINGULAR, INT32, fu, 4)            \
	X(a, CALLBACK, REPEATED, INT32, yaku, 5)        \
	X(a, STATIC, SINGULAR, INT32, dora, 6)          \
	X(a, STATIC, SINGULAR, INT32, uradora, 7)       \
	X(a, STATIC, SINGULAR, INT32, kandora, 8)       \
	X(a, STATIC, SINGULAR, INT32, kanuradora, 9)    \
	X(a, STATIC, SINGULAR, BOOL, open_hand, 10)
#define MultironWin_CALLBACK pb_default_field_callback
#define MultironWin_DEFAULT NULL

#define MultironResult_FIELDLIST(X, a)                \
	X(a, STATIC, SINGULAR, INT32, round_index, 1) \
	X(a, STATIC, SINGULAR, INT32, honba, 2)       \
	X(a, STATIC, SINGULAR, INT32, loser_id, 3)    \
	X(a, STATIC, SINGULAR, INT32, multi_ron, 4)   \
	X(a, CALLBACK, REPEATED, MESSAGE, wins, 5)    \
	X(a, CALLBACK, REPEATED, INT32, riichi_bets, 6)
#define MultironResult_CALLBACK pb_default_field_callback
#define MultironResult_DEFAULT NULL
#define MultironResult_wins_MSGTYPE MultironWin

#define TsumoResult_FIELDLIST(X, a)                     \
	X(a, STATIC, SINGULAR, INT32, round_index, 1)   \
	X(a, STATIC, SINGULAR, INT32, honba, 2)         \
	X(a, STATIC, SINGULAR, INT32, winner_id, 3)     \
	X(a, STATIC, SINGULAR, INT32, pao_player_id, 4) \
	X(a, STATIC, SINGULAR, INT32, han, 5)           \
	X(a, STATIC, SINGULAR, INT32, fu, 6)            \
	X(a, CALLBACK, REPEATED, INT32, yaku, 7)        \
	X(a, CALLBACK, REPEATED, INT32, riichi_bets, 8) \
	X(a, STATIC, SINGULAR, INT32, dora, 9)          \
	X(a, STATIC, SINGULAR, INT32, uradora, 10)      \
	X(a, STATIC, SINGULAR, INT32, kandora, 11)      \
	X(a, STATIC, SINGULAR, INT32, kanuradora, 12)   \
	X(a, STATIC, SINGULAR, BOOL, open_hand, 13)
#define TsumoResult_CALLBACK pb_default_field_callback
#define TsumoResult_DEFAULT NULL

#define DrawResult_FIELDLIST(X, a)                      \
	X(a, STATIC, SINGULAR, INT32, round_index, 1)   \
	X(a, STATIC, SINGULAR, INT32, honba, 2)         \
	X(a, CALLBACK, REPEATED, INT32, riichi_bets, 3) \
	X(a, CALLBACK, REPEATED, INT32, tempai, 4)
#define DrawResult_CALLBACK pb_default_field_callback
#define DrawResult_DEFAULT NULL

#define AbortResult_FIELDLIST(X, a)                   \
	X(a, STATIC, SINGULAR, INT32, round_index, 1) \
	X(a, STATIC, SINGULAR, INT32, honba, 2)       \
	X(a, CALLBACK, REPEATED, INT32, riichi_bets, 3)
#define AbortResult_CALLBACK pb_default_field_callback
#define AbortResult_DEFAULT NULL

#define ChomboResult_FIELDLIST(X, a)                  \
	X(a, STATIC, SINGULAR, INT32, round_index, 1) \
	X(a, STATIC, SINGULAR, INT32, honba, 2)       \
	X(a, STATIC, SINGULAR, INT32, loser_id, 3)
#define ChomboResult_CALLBACK NULL
#define ChomboResult_DEFAULT NULL

#define NagashiResult_FIELDLIST(X, a)                   \
	X(a, STATIC, SINGULAR, INT32, round_index, 1)   \
	X(a, STATIC, SINGULAR, INT32, honba, 2)         \
	X(a, CALLBACK, REPEATED, INT32, riichi_bets, 3) \
	X(a, CALLBACK, REPEATED, INT32, tempai, 4)      \
	X(a, CALLBACK, REPEATED, INT32, nagashi, 5)
#define NagashiResult_CALLBACK pb_default_field_callback
#define NagashiResult_DEFAULT NULL

#define Round_FIELDLIST(X, a)                                                  \
	X(a, STATIC, ONEOF, MESSAGE, (outcome, ron, outcome.ron), 1)           \
	X(a, STATIC, ONEOF, MESSAGE, (outcome, tsumo, outcome.tsumo), 2)       \
	X(a, STATIC, ONEOF, MESSAGE, (outcome, multiron, outcome.multiron), 3) \
	X(a, STATIC, ONEOF, MESSAGE, (outcome, draw, outcome.draw), 4)         \
	X(a, STATIC, ONEOF, MESSAGE, (outcome, abort, outcome.abort), 5)       \
	X(a, STATIC, ONEOF, MESSAGE, (outcome, chombo, outcome.chombo), 6)     \
	X(a, STATIC, ONEOF, MESSAGE, (outcome, nagashi, outcome.nagashi), 7)
#define Round_CALLBACK NULL
#define Round_DEFAULT NULL
#define Round_outcome_ron_MSGTYPE RonResult
#define Round_outcome_tsumo_MSGTYPE TsumoResult
#define Round_outcome_multiron_MSGTYPE MultironResult
#define Round_outcome_draw_MSGTYPE DrawResult
#define Round_outcome_abort_MSGTYPE AbortResult
#define Round_outcome_chombo_MSGTYPE ChomboResult
#define Round_outcome_nagashi_MSGTYPE NagashiResult

#define GameResult_FIELDLIST(X, a)                          \
	X(a, CALLBACK, SINGULAR, STRING, session_hash, 1)   \
	X(a, CALLBACK, OPTIONAL, STRING, date, 2)           \
	X(a, CALLBACK, SINGULAR, STRING, replay_link, 3)    \
	X(a, CALLBACK, REPEATED, INT32, players, 4)         \
	X(a, CALLBACK, REPEATED, MESSAGE, final_results, 5) \
	X(a, CALLBACK, REPEATED, MESSAGE, rounds, 7)
#define GameResult_CALLBACK pb_default_field_callback
#define GameResult_DEFAULT NULL
#define GameResult_final_results_MSGTYPE FinalResultOfSession
#define GameResult_rounds_MSGTYPE Round

#define PlayerPlaceInSeries_FIELDLIST(X, a)               \
	X(a, CALLBACK, SINGULAR, STRING, session_hash, 1) \
	X(a, STATIC, SINGULAR, INT32, place, 2)
#define PlayerPlaceInSeries_CALLBACK pb_default_field_callback
#define PlayerPlaceInSeries_DEFAULT NULL

#define SeriesResult_FIELDLIST(X, a)                               \
	X(a, STATIC, OPTIONAL, MESSAGE, player, 1)                 \
	X(a, CALLBACK, REPEATED, MESSAGE, best_series, 2)          \
	X(a, STATIC, SINGULAR, FLOAT, best_series_scores, 3)       \
	X(a, STATIC, SINGULAR, INT32, best_series_places, 4)       \
	X(a, CALLBACK, SINGULAR, STRING, best_series_avg_place, 5) \
	X(a, CALLBACK, REPEATED, MESSAGE, current_series, 6)       \
	X(a, STATIC, SINGULAR, FLOAT, current_series_scores, 7)    \
	X(a, STATIC, SINGULAR, INT32, current_series_places, 8)    \
	X(a, CALLBACK, SINGULAR, STRING, current_series_avg_place, 9)
#define SeriesResult_CALLBACK pb_default_field_callback
#define SeriesResult_DEFAULT NULL
#define SeriesResult_player_MSGTYPE Player
#define SeriesResult_best_series_MSGTYPE PlayerPlaceInSeries
#define SeriesResult_current_series_MSGTYPE PlayerPlaceInSeries

#define ReplacementPlayer_FIELDLIST(X, a)           \
	X(a, STATIC, SINGULAR, INT32, id, 1)        \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)  \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 3) \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 4)
#define ReplacementPlayer_CALLBACK pb_default_field_callback
#define ReplacementPlayer_DEFAULT NULL

#define PlayerInSession_FIELDLIST(X, a)                  \
	X(a, STATIC, SINGULAR, INT32, id, 1)             \
	X(a, STATIC, SINGULAR, STRING, title, 2)         \
	X(a, STATIC, SINGULAR, INT32, score, 3)          \
	X(a, STATIC, OPTIONAL, MESSAGE, replaced_by, 4)  \
	X(a, STATIC, SINGULAR, FLOAT, rating_delta, 5)   \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 6)      \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 7) \
	X(a, STATIC, SINGULAR, BOOL, yakitori, 8)
#define PlayerInSession_CALLBACK pb_default_field_callback
#define PlayerInSession_DEFAULT NULL
#define PlayerInSession_replaced_by_MSGTYPE ReplacementPlayer

#define RegisteredPlayer_FIELDLIST(X, a)                \
	X(a, STATIC, SINGULAR, INT32, id, 1)            \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)      \
	X(a, STATIC, OPTIONAL, INT32, local_id, 3)      \
	X(a, CALLBACK, OPTIONAL, STRING, team_name, 4)  \
	X(a, CALLBACK, SINGULAR, STRING, tenhou_id, 5)  \
	X(a, STATIC, SINGULAR, BOOL, ignore_seating, 6) \
	X(a, STATIC, OPTIONAL, MESSAGE, replaced_by, 7) \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 8)     \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 9)
#define RegisteredPlayer_CALLBACK pb_default_field_callback
#define RegisteredPlayer_DEFAULT NULL
#define RegisteredPlayer_replaced_by_MSGTYPE ReplacementPlayer

#define SessionHistoryResult_FIELDLIST(X, a)              \
	X(a, CALLBACK, SINGULAR, STRING, session_hash, 1) \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)        \
	X(a, STATIC, SINGULAR, INT32, player_id, 3)       \
	X(a, STATIC, SINGULAR, INT32, score, 4)           \
	X(a, STATIC, SINGULAR, FLOAT, rating_delta, 5)    \
	X(a, STATIC, SINGULAR, INT32, place, 6)           \
	X(a, CALLBACK, SINGULAR, STRING, title, 7)        \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 8)       \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 9)
#define SessionHistoryResult_CALLBACK pb_default_field_callback
#define SessionHistoryResult_DEFAULT NULL

#define SessionHistoryResultTable_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, tables, 1)
#define SessionHistoryResultTable_CALLBACK pb_default_field_callback
#define SessionHistoryResultTable_DEFAULT NULL
#define SessionHistoryResultTable_tables_MSGTYPE SessionHistoryResult

#define PlacesSummaryItem_FIELDLIST(X, a)       \
	X(a, STATIC, SINGULAR, INT32, place, 1) \
	X(a, STATIC, SINGULAR, INT32, count, 2)
#define PlacesSummaryItem_CALLBACK NULL
#define PlacesSummaryItem_DEFAULT NULL

#define PlayerWinSummary_FIELDLIST(X, a)                           \
	X(a, STATIC, SINGULAR, INT32, ron, 1)                      \
	X(a, STATIC, SINGULAR, INT32, tsumo, 2)                    \
	X(a, STATIC, SINGULAR, INT32, chombo, 3)                   \
	X(a, STATIC, SINGULAR, INT32, feed, 4)                     \
	X(a, STATIC, SINGULAR, INT32, tsumofeed, 5)                \
	X(a, STATIC, SINGULAR, INT32, wins_with_open, 6)           \
	X(a, STATIC, SINGULAR, INT32, wins_with_riichi, 7)         \
	X(a, STATIC, SINGULAR, INT32, wins_with_dama, 8)           \
	X(a, STATIC, SINGULAR, INT32, unforced_feed_to_open, 9)    \
	X(a, STATIC, SINGULAR, INT32, unforced_feed_to_riichi, 10) \
	X(a, STATIC, SINGULAR, INT32, unforced_feed_to_dama, 11)   \
	X(a, STATIC, SINGULAR, INT32, draw, 12)                    \
	X(a, STATIC, SINGULAR, INT32, draw_tempai, 13)             \
	X(a, STATIC, SINGULAR, INT32, points_won, 14)              \
	X(a, STATIC, SINGULAR, INT32, points_lost_ron, 15)         \
	X(a, STATIC, SINGULAR, INT32, points_lost_tsumo, 16)
#define PlayerWinSummary_CALLBACK NULL
#define PlayerWinSummary_DEFAULT NULL

#define HandValueStat_FIELDLIST(X, a)               \
	X(a, STATIC, SINGULAR, INT32, han_count, 1) \
	X(a, STATIC, SINGULAR, INT32, count, 2)
#define HandValueStat_CALLBACK NULL
#define HandValueStat_DEFAULT NULL

#define YakuStat_FIELDLIST(X, a)                  \
	X(a, STATIC, SINGULAR, INT32, yaku_id, 1) \
	X(a, STATIC, SINGULAR, INT32, count, 2)
#define YakuStat_CALLBACK NULL
#define YakuStat_DEFAULT NULL

#define RiichiSummary_FIELDLIST(X, a)                 \
	X(a, STATIC, SINGULAR, INT32, riichi_won, 1)  \
	X(a, STATIC, SINGULAR, INT32, riichi_lost, 2) \
	X(a, STATIC, SINGULAR, INT32, feed_under_riichi, 3)
#define RiichiSummary_CALLBACK NULL
#define RiichiSummary_DEFAULT NULL

#define DoraSummary_FIELDLIST(X, a)             \
	X(a, STATIC, SINGULAR, INT32, count, 1) \
	X(a, STATIC, SINGULAR, FLOAT, average, 2)
#define DoraSummary_CALLBACK NULL
#define DoraSummary_DEFAULT NULL

#define IntermediateResultOfSession_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, player_id, 1) \
	X(a, STATIC, SINGULAR, INT32, score, 2)     \
	X(a, STATIC, SINGULAR, INT32, chombo_count, 4)
#define IntermediateResultOfSession_CALLBACK NULL
#define IntermediateResultOfSession_DEFAULT NULL

#define PaymentLogItem_FIELDLIST(X, a)         \
	X(a, STATIC, OPTIONAL, INT32, from, 1) \
	X(a, STATIC, OPTIONAL, INT32, to, 2)   \
	X(a, STATIC, SINGULAR, INT32, amount, 3)
#define PaymentLogItem_CALLBACK NULL
#define PaymentLogItem_DEFAULT NULL

#define PaymentLog_FIELDLIST(X, a)                   \
	X(a, CALLBACK, REPEATED, MESSAGE, direct, 1) \
	X(a, CALLBACK, REPEATED, MESSAGE, riichi, 2) \
	X(a, CALLBACK, REPEATED, MESSAGE, honba, 3)
#define PaymentLog_CALLBACK pb_default_field_callback
#define PaymentLog_DEFAULT NULL
#define PaymentLog_direct_MSGTYPE PaymentLogItem
#define PaymentLog_riichi_MSGTYPE PaymentLogItem
#define PaymentLog_honba_MSGTYPE PaymentLogItem

#define RoundState_FIELDLIST(X, a)                         \
	X(a, CALLBACK, SINGULAR, STRING, session_hash, 1)  \
	X(a, STATIC, SINGULAR, INT32, dealer, 2)           \
	X(a, STATIC, SINGULAR, INT32, round_index, 3)      \
	X(a, STATIC, SINGULAR, INT32, riichi, 4)           \
	X(a, STATIC, SINGULAR, INT32, honba, 5)            \
	X(a, CALLBACK, REPEATED, INT32, riichi_ids, 6)     \
	X(a, CALLBACK, REPEATED, MESSAGE, scores, 7)       \
	X(a, CALLBACK, REPEATED, MESSAGE, scores_delta, 8) \
	X(a, STATIC, OPTIONAL, MESSAGE, payments, 9)       \
	X(a, STATIC, OPTIONAL, MESSAGE, round, 10)         \
	X(a, STATIC, SINGULAR, UENUM, outcome, 11)
#define RoundState_CALLBACK pb_default_field_callback
#define RoundState_DEFAULT NULL
#define RoundState_scores_MSGTYPE IntermediateResultOfSession
#define RoundState_scores_delta_MSGTYPE IntermediateResultOfSession
#define RoundState_payments_MSGTYPE PaymentLog
#define RoundState_round_MSGTYPE Round

#define EventData_FIELDLIST(X, a)                                 \
	X(a, STATIC, OPTIONAL, UENUM, type, 1)                    \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)                \
	X(a, CALLBACK, SINGULAR, STRING, description, 3)          \
	X(a, STATIC, SINGULAR, INT32, duration, 4)                \
	X(a, CALLBACK, SINGULAR, STRING, timezone, 6)             \
	X(a, STATIC, SINGULAR, INT32, lobby_id, 7)                \
	X(a, STATIC, SINGULAR, INT32, series_length, 8)           \
	X(a, STATIC, SINGULAR, INT32, min_games, 9)               \
	X(a, STATIC, SINGULAR, BOOL, is_team, 10)                 \
	X(a, STATIC, SINGULAR, BOOL, is_prescripted, 11)          \
	X(a, STATIC, SINGULAR, INT32, autostart, 12)              \
	X(a, STATIC, OPTIONAL, MESSAGE, ruleset_config, 14)       \
	X(a, STATIC, SINGULAR, BOOL, is_listed, 15)               \
	X(a, STATIC, SINGULAR, BOOL, is_rating_shown, 16)         \
	X(a, STATIC, SINGULAR, BOOL, achievements_shown, 17)      \
	X(a, STATIC, SINGULAR, BOOL, allow_view_other_tables, 18) \
	X(a, STATIC, SINGULAR, UENUM, platform_id, 19)
#define EventData_CALLBACK pb_default_field_callback
#define EventData_DEFAULT NULL
#define EventData_ruleset_config_MSGTYPE RulesetConfig

#define TableState_FIELDLIST(X, a)                            \
	X(a, STATIC, SINGULAR, UENUM, status, 1)              \
	X(a, STATIC, SINGULAR, BOOL, may_definalize, 2)       \
	X(a, CALLBACK, SINGULAR, STRING, session_hash, 3)     \
	X(a, STATIC, OPTIONAL, INT32, table_index, 5)         \
	X(a, STATIC, OPTIONAL, MESSAGE, last_round, 6)        \
	X(a, STATIC, SINGULAR, INT32, current_round_index, 7) \
	X(a, CALLBACK, REPEATED, MESSAGE, scores, 8)          \
	X(a, CALLBACK, REPEATED, MESSAGE, players, 9)         \
	X(a, STATIC, OPTIONAL, INT32, extra_time, 10)
#define TableState_CALLBACK pb_default_field_callback
#define TableState_DEFAULT NULL
#define TableState_last_round_MSGTYPE Round
#define TableState_scores_MSGTYPE IntermediateResultOfSession
#define TableState_players_MSGTYPE RegisteredPlayer

#define Achievement_FIELDLIST(X, a)                         \
	X(a, CALLBACK, SINGULAR, STRING, achievement_id, 1) \
	X(a, CALLBACK, SINGULAR, STRING, achievement_data, 2)
#define Achievement_CALLBACK pb_default_field_callback
#define Achievement_DEFAULT NULL

#define LocalIdMapping_FIELDLIST(X, a)              \
	X(a, STATIC, SINGULAR, INT32, player_id, 1) \
	X(a, STATIC, SINGULAR, INT32, local_id, 2)
#define LocalIdMapping_CALLBACK NULL
#define LocalIdMapping_DEFAULT NULL

#define TeamMapping_FIELDLIST(X, a)                 \
	X(a, STATIC, SINGULAR, INT32, player_id, 1) \
	X(a, CALLBACK, SINGULAR, STRING, team_name, 2)
#define TeamMapping_CALLBACK pb_default_field_callback
#define TeamMapping_DEFAULT NULL

#define PlayerSeating_FIELDLIST(X, a)                     \
	X(a, STATIC, SINGULAR, INT32, order, 1)           \
	X(a, STATIC, SINGULAR, INT32, player_id, 2)       \
	X(a, STATIC, SINGULAR, INT32, session_id, 3)      \
	X(a, STATIC, SINGULAR, INT32, table_index, 4)     \
	X(a, STATIC, SINGULAR, FLOAT, rating, 5)          \
	X(a, CALLBACK, SINGULAR, STRING, player_title, 6) \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 7)       \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 8)
#define PlayerSeating_CALLBACK pb_default_field_callback
#define PlayerSeating_DEFAULT NULL

#define PlayerSeatingSwiss_FIELDLIST(X, a)          \
	X(a, STATIC, SINGULAR, INT32, player_id, 1) \
	X(a, STATIC, SINGULAR, FLOAT, rating, 2)
#define PlayerSeatingSwiss_CALLBACK NULL
#define PlayerSeatingSwiss_DEFAULT NULL

#define TableItemSwiss_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, players, 1)
#define TableItemSwiss_CALLBACK pb_default_field_callback
#define TableItemSwiss_DEFAULT NULL
#define TableItemSwiss_players_MSGTYPE PlayerSeatingSwiss

#define PrescriptedTable_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, players, 1)
#define PrescriptedTable_CALLBACK pb_default_field_callback
#define PrescriptedTable_DEFAULT NULL
#define PrescriptedTable_players_MSGTYPE RegisteredPlayer

#define Chombo_FIELDLIST(X, a)                      \
	X(a, STATIC, SINGULAR, INT32, player_id, 1) \
	X(a, STATIC, SINGULAR, FLOAT, amount, 2)
#define Chombo_CALLBACK NULL
#define Chombo_DEFAULT NULL

#define SessionState_FIELDLIST(X, a)                       \
	X(a, STATIC, SINGULAR, INT32, dealer, 1)           \
	X(a, STATIC, SINGULAR, INT32, round_index, 2)      \
	X(a, STATIC, SINGULAR, INT32, riichi_count, 3)     \
	X(a, STATIC, SINGULAR, INT32, honba_count, 4)      \
	X(a, CALLBACK, REPEATED, MESSAGE, scores, 5)       \
	X(a, STATIC, SINGULAR, BOOL, finished, 6)          \
	X(a, STATIC, SINGULAR, BOOL, last_hand_started, 8) \
	X(a, CALLBACK, REPEATED, MESSAGE, chombo, 9)
#define SessionState_CALLBACK pb_default_field_callback
#define SessionState_DEFAULT NULL
#define SessionState_scores_MSGTYPE IntermediateResultOfSession
#define SessionState_chombo_MSGTYPE Chombo

#define Uma_FIELDLIST(X, a)                      \
	X(a, STATIC, SINGULAR, INT32, place1, 1) \
	X(a, STATIC, SINGULAR, INT32, place2, 2) \
	X(a, STATIC, SINGULAR, INT32, place3, 3) \
	X(a, STATIC, SINGULAR, INT32, place4, 4)
#define Uma_CALLBACK NULL
#define Uma_DEFAULT NULL

#define ComplexUma_FIELDLIST(X, a)               \
	X(a, STATIC, OPTIONAL, MESSAGE, neg1, 1) \
	X(a, STATIC, OPTIONAL, MESSAGE, neg3, 2) \
	X(a, STATIC, OPTIONAL, MESSAGE, otherwise, 3)
#define ComplexUma_CALLBACK NULL
#define ComplexUma_DEFAULT NULL
#define ComplexUma_neg1_MSGTYPE Uma
#define ComplexUma_neg3_MSGTYPE Uma
#define ComplexUma_otherwise_MSGTYPE Uma

#define RulesetConfig_FIELDLIST(X, a)                                       \
	X(a, STATIC, OPTIONAL, MESSAGE, complex_uma, 1)                     \
	X(a, STATIC, SINGULAR, UENUM, ending_policy, 2)                     \
	X(a, STATIC, OPTIONAL, MESSAGE, uma, 3)                             \
	X(a, STATIC, SINGULAR, UENUM, uma_type, 4)                          \
	X(a, STATIC, SINGULAR, BOOL, doubleron_honba_atamahane, 5)          \
	X(a, STATIC, SINGULAR, BOOL, doubleron_riichi_atamahane, 6)         \
	X(a, STATIC, SINGULAR, BOOL, equalize_uma, 7)                       \
	X(a, STATIC, SINGULAR, BOOL, extra_chombo_payments, 8)              \
	X(a, STATIC, SINGULAR, BOOL, play_additional_rounds, 9)             \
	X(a, STATIC, SINGULAR, BOOL, riichi_goes_to_winner, 10)             \
	X(a, STATIC, SINGULAR, BOOL, tonpuusen, 11)                         \
	X(a, STATIC, SINGULAR, BOOL, with_abortives, 12)                    \
	X(a, STATIC, SINGULAR, BOOL, with_atamahane, 13)                    \
	X(a, STATIC, SINGULAR, BOOL, with_buttobi, 14)                      \
	X(a, STATIC, SINGULAR, BOOL, with_kazoe, 15)                        \
	X(a, STATIC, SINGULAR, BOOL, with_kiriage_mangan, 16)               \
	X(a, STATIC, SINGULAR, BOOL, with_kuitan, 17)                       \
	X(a, STATIC, SINGULAR, BOOL, with_leading_dealer_game_over, 18)     \
	X(a, STATIC, SINGULAR, BOOL, with_multi_yakumans, 19)               \
	X(a, STATIC, SINGULAR, BOOL, with_nagashi_mangan, 20)               \
	X(a, STATIC, SINGULAR, BOOL, with_winning_dealer_honba_skipped, 21) \
	X(a, STATIC, SINGULAR, INT32, chips_value, 22)                      \
	X(a, STATIC, SINGULAR, INT32, chombo_amount, 23)                    \
	X(a, STATIC, SINGULAR, INT32, game_expiration_time, 24)             \
	X(a, STATIC, SINGULAR, INT32, goal_points, 25)                      \
	X(a, STATIC, SINGULAR, INT32, max_penalty, 26)                      \
	X(a, STATIC, SINGULAR, INT32, min_penalty, 27)                      \
	X(a, STATIC, SINGULAR, INT32, oka, 28)                              \
	X(a, STATIC, SINGULAR, INT32, penalty_step, 29)                     \
	X(a, STATIC, SINGULAR, INT32, replacement_player_fixed_points, 30)  \
	X(a, STATIC, SINGULAR, INT32, replacement_player_override_uma, 31)  \
	X(a, STATIC, SINGULAR, INT32, start_points, 32)                     \
	X(a, STATIC, SINGULAR, INT32, start_rating, 33)                     \
	X(a, CALLBACK, REPEATED, INT32, allowed_yaku, 34)                   \
	X(a, CALLBACK, REPEATED, INT32, yaku_with_pao, 35)                  \
	X(a, STATIC, SINGULAR, BOOL, with_yakitori, 36)                     \
	X(a, STATIC, SINGULAR, INT32, yakitori_penalty, 37)                 \
	X(a, STATIC, SINGULAR, BOOL, chombo_ends_game, 38)                  \
	X(a, STATIC, SINGULAR, INT32, honba_value, 39)                      \
	X(a, CALLBACK, REPEATED, INT32, double_yakuman, 40)
#define RulesetConfig_CALLBACK pb_default_field_callback
#define RulesetConfig_DEFAULT NULL
#define RulesetConfig_complex_uma_MSGTYPE ComplexUma
#define RulesetConfig_uma_MSGTYPE Uma

#define MajsoulSearchEx_FIELDLIST(X, a)               \
	X(a, CALLBACK, SINGULAR, STRING, nickname, 1) \
	X(a, STATIC, SINGULAR, INT32, account_id, 2)
#define MajsoulSearchEx_CALLBACK pb_default_field_callback
#define MajsoulSearchEx_DEFAULT NULL

#define MajsoulPersonMapping_FIELDLIST(X, a)        \
	X(a, STATIC, SINGULAR, INT32, person_id, 1) \
	X(a, CALLBACK, SINGULAR, STRING, nickname, 2)
#define MajsoulPersonMapping_CALLBACK pb_default_field_callback
#define MajsoulPersonMapping_DEFAULT NULL

#define GenericSuccessResponse_FIELDLIST(X, a) X(a, STATIC, SINGULAR, BOOL, success, 1)
#define GenericSuccessResponse_CALLBACK NULL
#define GenericSuccessResponse_DEFAULT NULL

#define GenericEventPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, event_id, 1)
#define GenericEventPayload_CALLBACK NULL
#define GenericEventPayload_DEFAULT NULL

#define GenericSessionPayload_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, session_hash, 1)
#define GenericSessionPayload_CALLBACK pb_default_field_callback
#define GenericSessionPayload_DEFAULT NULL

extern const pb_msgdesc_t EventAdmin_msg;
extern const pb_msgdesc_t EventReferee_msg;
extern const pb_msgdesc_t Person_msg;
extern const pb_msgdesc_t PersonEx_msg;
extern const pb_msgdesc_t Country_msg;
extern const pb_msgdesc_t Event_msg;
extern const pb_msgdesc_t MyEvent_msg;
extern const pb_msgdesc_t GameConfig_msg;
extern const pb_msgdesc_t PlayerInRating_msg;
extern const pb_msgdesc_t Player_msg;
extern const pb_msgdesc_t FinalResultOfSession_msg;
extern const pb_msgdesc_t Penalty_msg;
extern const pb_msgdesc_t RonResult_msg;
extern const pb_msgdesc_t MultironWin_msg;
extern const pb_msgdesc_t MultironResult_msg;
extern const pb_msgdesc_t TsumoResult_msg;
extern const pb_msgdesc_t DrawResult_msg;
extern const pb_msgdesc_t AbortResult_msg;
extern const pb_msgdesc_t ChomboResult_msg;
extern const pb_msgdesc_t NagashiResult_msg;
extern const pb_msgdesc_t Round_msg;
extern const pb_msgdesc_t GameResult_msg;
extern const pb_msgdesc_t PlayerPlaceInSeries_msg;
extern const pb_msgdesc_t SeriesResult_msg;
extern const pb_msgdesc_t ReplacementPlayer_msg;
extern const pb_msgdesc_t PlayerInSession_msg;
extern const pb_msgdesc_t RegisteredPlayer_msg;
extern const pb_msgdesc_t SessionHistoryResult_msg;
extern const pb_msgdesc_t SessionHistoryResultTable_msg;
extern const pb_msgdesc_t PlacesSummaryItem_msg;
extern const pb_msgdesc_t PlayerWinSummary_msg;
extern const pb_msgdesc_t HandValueStat_msg;
extern const pb_msgdesc_t YakuStat_msg;
extern const pb_msgdesc_t RiichiSummary_msg;
extern const pb_msgdesc_t DoraSummary_msg;
extern const pb_msgdesc_t IntermediateResultOfSession_msg;
extern const pb_msgdesc_t PaymentLogItem_msg;
extern const pb_msgdesc_t PaymentLog_msg;
extern const pb_msgdesc_t RoundState_msg;
extern const pb_msgdesc_t EventData_msg;
extern const pb_msgdesc_t TableState_msg;
extern const pb_msgdesc_t Achievement_msg;
extern const pb_msgdesc_t LocalIdMapping_msg;
extern const pb_msgdesc_t TeamMapping_msg;
extern const pb_msgdesc_t PlayerSeating_msg;
extern const pb_msgdesc_t PlayerSeatingSwiss_msg;
extern const pb_msgdesc_t TableItemSwiss_msg;
extern const pb_msgdesc_t PrescriptedTable_msg;
extern const pb_msgdesc_t Chombo_msg;
extern const pb_msgdesc_t SessionState_msg;
extern const pb_msgdesc_t Uma_msg;
extern const pb_msgdesc_t ComplexUma_msg;
extern const pb_msgdesc_t RulesetConfig_msg;
extern const pb_msgdesc_t MajsoulSearchEx_msg;
extern const pb_msgdesc_t MajsoulPersonMapping_msg;
extern const pb_msgdesc_t GenericSuccessResponse_msg;
extern const pb_msgdesc_t GenericEventPayload_msg;
extern const pb_msgdesc_t GenericSessionPayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EventAdmin_fields &EventAdmin_msg
#define EventReferee_fields &EventReferee_msg
#define Person_fields &Person_msg
#define PersonEx_fields &PersonEx_msg
#define Country_fields &Country_msg
#define Event_fields &Event_msg
#define MyEvent_fields &MyEvent_msg
#define GameConfig_fields &GameConfig_msg
#define PlayerInRating_fields &PlayerInRating_msg
#define Player_fields &Player_msg
#define FinalResultOfSession_fields &FinalResultOfSession_msg
#define Penalty_fields &Penalty_msg
#define RonResult_fields &RonResult_msg
#define MultironWin_fields &MultironWin_msg
#define MultironResult_fields &MultironResult_msg
#define TsumoResult_fields &TsumoResult_msg
#define DrawResult_fields &DrawResult_msg
#define AbortResult_fields &AbortResult_msg
#define ChomboResult_fields &ChomboResult_msg
#define NagashiResult_fields &NagashiResult_msg
#define Round_fields &Round_msg
#define GameResult_fields &GameResult_msg
#define PlayerPlaceInSeries_fields &PlayerPlaceInSeries_msg
#define SeriesResult_fields &SeriesResult_msg
#define ReplacementPlayer_fields &ReplacementPlayer_msg
#define PlayerInSession_fields &PlayerInSession_msg
#define RegisteredPlayer_fields &RegisteredPlayer_msg
#define SessionHistoryResult_fields &SessionHistoryResult_msg
#define SessionHistoryResultTable_fields &SessionHistoryResultTable_msg
#define PlacesSummaryItem_fields &PlacesSummaryItem_msg
#define PlayerWinSummary_fields &PlayerWinSummary_msg
#define HandValueStat_fields &HandValueStat_msg
#define YakuStat_fields &YakuStat_msg
#define RiichiSummary_fields &RiichiSummary_msg
#define DoraSummary_fields &DoraSummary_msg
#define IntermediateResultOfSession_fields &IntermediateResultOfSession_msg
#define PaymentLogItem_fields &PaymentLogItem_msg
#define PaymentLog_fields &PaymentLog_msg
#define RoundState_fields &RoundState_msg
#define EventData_fields &EventData_msg
#define TableState_fields &TableState_msg
#define Achievement_fields &Achievement_msg
#define LocalIdMapping_fields &LocalIdMapping_msg
#define TeamMapping_fields &TeamMapping_msg
#define PlayerSeating_fields &PlayerSeating_msg
#define PlayerSeatingSwiss_fields &PlayerSeatingSwiss_msg
#define TableItemSwiss_fields &TableItemSwiss_msg
#define PrescriptedTable_fields &PrescriptedTable_msg
#define Chombo_fields &Chombo_msg
#define SessionState_fields &SessionState_msg
#define Uma_fields &Uma_msg
#define ComplexUma_fields &ComplexUma_msg
#define RulesetConfig_fields &RulesetConfig_msg
#define MajsoulSearchEx_fields &MajsoulSearchEx_msg
#define MajsoulPersonMapping_fields &MajsoulPersonMapping_msg
#define GenericSuccessResponse_fields &GenericSuccessResponse_msg
#define GenericEventPayload_fields &GenericEventPayload_msg
#define GenericSessionPayload_fields &GenericSessionPayload_msg

/* Maximum encoded size of messages (where known) */
/* EventAdmin_size depends on runtime parameters */
/* EventReferee_size depends on runtime parameters */
/* Person_size depends on runtime parameters */
/* PersonEx_size depends on runtime parameters */
/* Country_size depends on runtime parameters */
/* Event_size depends on runtime parameters */
/* MyEvent_size depends on runtime parameters */
/* GameConfig_size depends on runtime parameters */
/* PlayerInRating_size depends on runtime parameters */
/* Player_size depends on runtime parameters */
/* Penalty_size depends on runtime parameters */
/* RonResult_size depends on runtime parameters */
/* MultironWin_size depends on runtime parameters */
/* MultironResult_size depends on runtime parameters */
/* TsumoResult_size depends on runtime parameters */
/* DrawResult_size depends on runtime parameters */
/* AbortResult_size depends on runtime parameters */
/* NagashiResult_size depends on runtime parameters */
/* Round_size depends on runtime parameters */
/* GameResult_size depends on runtime parameters */
/* PlayerPlaceInSeries_size depends on runtime parameters */
/* SeriesResult_size depends on runtime parameters */
/* ReplacementPlayer_size depends on runtime parameters */
/* PlayerInSession_size depends on runtime parameters */
/* RegisteredPlayer_size depends on runtime parameters */
/* SessionHistoryResult_size depends on runtime parameters */
/* SessionHistoryResultTable_size depends on runtime parameters */
/* PaymentLog_size depends on runtime parameters */
/* RoundState_size depends on runtime parameters */
/* EventData_size depends on runtime parameters */
/* TableState_size depends on runtime parameters */
/* Achievement_size depends on runtime parameters */
/* TeamMapping_size depends on runtime parameters */
/* PlayerSeating_size depends on runtime parameters */
/* TableItemSwiss_size depends on runtime parameters */
/* PrescriptedTable_size depends on runtime parameters */
/* SessionState_size depends on runtime parameters */
/* RulesetConfig_size depends on runtime parameters */
/* MajsoulSearchEx_size depends on runtime parameters */
/* MajsoulPersonMapping_size depends on runtime parameters */
/* GenericSessionPayload_size depends on runtime parameters */
#define ChomboResult_size 33
#define Chombo_size 16
#define ComplexUma_size 138
#define DoraSummary_size 16
#define FinalResultOfSession_size 38
#define GenericEventPayload_size 11
#define GenericSuccessResponse_size 2
#define HandValueStat_size 22
#define IntermediateResultOfSession_size 33
#define LocalIdMapping_size 22
#define PROTO_ATOMS_PB_H_MAX_SIZE PlayerWinSummary_size
#define PaymentLogItem_size 33
#define PlacesSummaryItem_size 22
#define PlayerSeatingSwiss_size 16
#define PlayerWinSummary_size 177
#define RiichiSummary_size 33
#define Uma_size 44
#define YakuStat_size 22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
