/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/frey.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AuthRequestRegistrationPayload, AuthRequestRegistrationPayload, AUTO)

PB_BIND(AuthRequestRegistrationResponse, AuthRequestRegistrationResponse, AUTO)

PB_BIND(AuthApproveRegistrationPayload, AuthApproveRegistrationPayload, AUTO)

PB_BIND(AuthApproveRegistrationResponse, AuthApproveRegistrationResponse, AUTO)

PB_BIND(AuthAuthorizePayload, AuthAuthorizePayload, AUTO)

PB_BIND(AuthAuthorizeResponse, AuthAuthorizeResponse, AUTO)

PB_BIND(AuthQuickAuthorizePayload, AuthQuickAuthorizePayload, AUTO)

PB_BIND(AuthQuickAuthorizeResponse, AuthQuickAuthorizeResponse, AUTO)

PB_BIND(AuthMePayload, AuthMePayload, AUTO)

PB_BIND(AuthMeResponse, AuthMeResponse, AUTO)

PB_BIND(AuthChangePasswordPayload, AuthChangePasswordPayload, AUTO)

PB_BIND(AuthChangePasswordResponse, AuthChangePasswordResponse, AUTO)

PB_BIND(AuthRequestResetPasswordPayload, AuthRequestResetPasswordPayload, AUTO)

PB_BIND(AuthRequestResetPasswordResponse, AuthRequestResetPasswordResponse, AUTO)

PB_BIND(AuthApproveResetPasswordPayload, AuthApproveResetPasswordPayload, AUTO)

PB_BIND(AuthApproveResetPasswordResponse, AuthApproveResetPasswordResponse, AUTO)

PB_BIND(AccessGetEventAdminsPayload, AccessGetEventAdminsPayload, AUTO)

PB_BIND(AccessGetEventAdminsResponse, AccessGetEventAdminsResponse, AUTO)

PB_BIND(AccessGetEventRefereesPayload, AccessGetEventRefereesPayload, AUTO)

PB_BIND(AccessGetEventRefereesResponse, AccessGetEventRefereesResponse, AUTO)

PB_BIND(AccessGetSuperadminFlagPayload, AccessGetSuperadminFlagPayload, AUTO)

PB_BIND(AccessGetSuperadminFlagResponse, AccessGetSuperadminFlagResponse, AUTO)

PB_BIND(AccessGetOwnedEventIdsPayload, AccessGetOwnedEventIdsPayload, AUTO)

PB_BIND(AccessGetOwnedEventIdsResponse, AccessGetOwnedEventIdsResponse, AUTO)

PB_BIND(AccessAddRuleForPersonPayload, AccessAddRuleForPersonPayload, AUTO)

PB_BIND(AccessAddRuleForPersonResponse, AccessAddRuleForPersonResponse, AUTO)

PB_BIND(AccessDeleteRuleForPersonPayload, AccessDeleteRuleForPersonPayload, AUTO)

PB_BIND(PersonsCreateAccountPayload, PersonsCreateAccountPayload, AUTO)

PB_BIND(PersonsCreateAccountResponse, PersonsCreateAccountResponse, AUTO)

PB_BIND(PersonsUpdatePersonalInfoPayload, PersonsUpdatePersonalInfoPayload, AUTO)

PB_BIND(PersonsGetPersonalInfoPayload, PersonsGetPersonalInfoPayload, AUTO)

PB_BIND(PersonsGetPersonalInfoResponse, PersonsGetPersonalInfoResponse, AUTO)

PB_BIND(PersonsFindByTenhouIdsPayload, PersonsFindByTenhouIdsPayload, AUTO)

PB_BIND(PersonsFindByMajsoulIdsPayload, PersonsFindByMajsoulIdsPayload, AUTO)

PB_BIND(PersonsFindByTenhouIdsResponse, PersonsFindByTenhouIdsResponse, AUTO)

PB_BIND(PersonsFindByTitlePayload, PersonsFindByTitlePayload, AUTO)

PB_BIND(PersonsFindByTitleResponse, PersonsFindByTitleResponse, AUTO)

PB_BIND(DepersonalizePayload, DepersonalizePayload, AUTO)

PB_BIND(PersonsGetMajsoulNicknamesPayload, PersonsGetMajsoulNicknamesPayload, AUTO)

PB_BIND(PersonsGetMajsoulNicknamesResponse, PersonsGetMajsoulNicknamesResponse, AUTO)

PB_BIND(PersonsGetNotificationsSettingsPayload, PersonsGetNotificationsSettingsPayload, AUTO)

PB_BIND(PersonsGetNotificationsSettingsResponse, PersonsGetNotificationsSettingsResponse, AUTO)

PB_BIND(PersonsSetNotificationsSettingsPayload, PersonsSetNotificationsSettingsPayload, AUTO)
