/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_FREY_PB_H_INCLUDED
#define PB_PROTO_FREY_PB_H_INCLUDED
#include <pb.h>
#include "proto/atoms.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AuthRequestRegistrationPayload {
	pb_callback_t email;
	pb_callback_t title;
	pb_callback_t password;
} AuthRequestRegistrationPayload;

typedef struct _AuthRequestRegistrationResponse {
	pb_callback_t approval_code;
} AuthRequestRegistrationResponse;

typedef struct _AuthApproveRegistrationPayload {
	pb_callback_t approval_code;
} AuthApproveRegistrationPayload;

typedef struct _AuthApproveRegistrationResponse {
	int32_t person_id;
} AuthApproveRegistrationResponse;

typedef struct _AuthAuthorizePayload {
	pb_callback_t email;
	pb_callback_t password;
} AuthAuthorizePayload;

typedef struct _AuthAuthorizeResponse {
	int32_t person_id;
	pb_callback_t auth_token;
} AuthAuthorizeResponse;

typedef struct _AuthQuickAuthorizePayload {
	int32_t person_id;
	pb_callback_t auth_token;
} AuthQuickAuthorizePayload;

typedef struct _AuthQuickAuthorizeResponse {
	bool auth_success;
} AuthQuickAuthorizeResponse;

typedef struct _AuthMePayload {
	char dummy_field;
} AuthMePayload;

typedef struct _AuthMeResponse {
	int32_t person_id;
	pb_callback_t country;
	pb_callback_t city;
	pb_callback_t email;
	pb_callback_t phone;
	pb_callback_t tenhou_id;
	pb_callback_t title;
	bool has_avatar;
	pb_callback_t last_update;
} AuthMeResponse;

typedef struct _AuthChangePasswordPayload {
	pb_callback_t email;
	pb_callback_t password;
	pb_callback_t new_password;
} AuthChangePasswordPayload;

typedef struct _AuthChangePasswordResponse {
	pb_callback_t auth_token;
} AuthChangePasswordResponse;

typedef struct _AuthRequestResetPasswordPayload {
	pb_callback_t email;
} AuthRequestResetPasswordPayload;

typedef struct _AuthRequestResetPasswordResponse {
	pb_callback_t reset_token;
} AuthRequestResetPasswordResponse;

typedef struct _AuthApproveResetPasswordPayload {
	pb_callback_t email;
	pb_callback_t reset_token;
} AuthApproveResetPasswordPayload;

typedef struct _AuthApproveResetPasswordResponse {
	pb_callback_t new_tmp_password;
} AuthApproveResetPasswordResponse;

typedef struct _AccessGetEventAdminsPayload {
	int32_t event_id;
} AccessGetEventAdminsPayload;

typedef struct _AccessGetEventAdminsResponse {
	pb_callback_t admins;
} AccessGetEventAdminsResponse;

typedef struct _AccessGetEventRefereesPayload {
	int32_t event_id;
} AccessGetEventRefereesPayload;

typedef struct _AccessGetEventRefereesResponse {
	pb_callback_t referees;
} AccessGetEventRefereesResponse;

typedef struct _AccessGetSuperadminFlagPayload {
	int32_t person_id;
} AccessGetSuperadminFlagPayload;

typedef struct _AccessGetSuperadminFlagResponse {
	bool is_admin;
} AccessGetSuperadminFlagResponse;

typedef struct _AccessGetOwnedEventIdsPayload {
	int32_t person_id;
} AccessGetOwnedEventIdsPayload;

typedef struct _AccessGetOwnedEventIdsResponse {
	pb_callback_t event_ids;
} AccessGetOwnedEventIdsResponse;

typedef struct _AccessAddRuleForPersonPayload {
	pb_callback_t rule_name;
	int32_t rule_value;
	int32_t person_id;
	int32_t event_id;
} AccessAddRuleForPersonPayload;

typedef struct _AccessAddRuleForPersonResponse {
	int32_t rule_id;
} AccessAddRuleForPersonResponse;

typedef struct _AccessDeleteRuleForPersonPayload {
	int32_t rule_id;
} AccessDeleteRuleForPersonPayload;

typedef struct _PersonsCreateAccountPayload {
	pb_callback_t email;
	pb_callback_t password;
	pb_callback_t title;
	pb_callback_t city;
	pb_callback_t phone;
	pb_callback_t tenhou_id;
	pb_callback_t country;
} PersonsCreateAccountPayload;

typedef struct _PersonsCreateAccountResponse {
	int32_t person_id;
} PersonsCreateAccountResponse;

typedef struct _PersonsUpdatePersonalInfoPayload {
	int32_t id;
	pb_callback_t title;
	pb_callback_t country;
	pb_callback_t city;
	pb_callback_t email;
	pb_callback_t phone;
	pb_callback_t tenhou_id;
	bool has_avatar;
	pb_callback_t avatar_data;
	pb_callback_t ms_nickname;
	bool has_ms_friend_id;
	int32_t ms_friend_id;
	bool has_ms_account_id;
	int32_t ms_account_id;
} PersonsUpdatePersonalInfoPayload;

typedef struct _PersonsGetPersonalInfoPayload {
	pb_callback_t ids;
} PersonsGetPersonalInfoPayload;

typedef struct _PersonsGetPersonalInfoResponse {
	pb_callback_t people;
} PersonsGetPersonalInfoResponse;

typedef struct _PersonsFindByTenhouIdsPayload {
	pb_callback_t ids;
} PersonsFindByTenhouIdsPayload;

typedef struct _PersonsFindByMajsoulIdsPayload {
	pb_callback_t ids;
} PersonsFindByMajsoulIdsPayload;

typedef struct _PersonsFindByTenhouIdsResponse {
	pb_callback_t people;
} PersonsFindByTenhouIdsResponse;

typedef struct _PersonsFindByTitlePayload {
	pb_callback_t query;
} PersonsFindByTitlePayload;

typedef struct _PersonsFindByTitleResponse {
	pb_callback_t people;
} PersonsFindByTitleResponse;

typedef struct _DepersonalizePayload {
	char dummy_field;
} DepersonalizePayload;

typedef struct _PersonsGetMajsoulNicknamesPayload {
	pb_callback_t ids;
} PersonsGetMajsoulNicknamesPayload;

typedef struct _PersonsGetMajsoulNicknamesResponse {
	pb_callback_t mapping;
} PersonsGetMajsoulNicknamesResponse;

typedef struct _PersonsGetNotificationsSettingsPayload {
	int32_t person_id;
} PersonsGetNotificationsSettingsPayload;

typedef struct _PersonsGetNotificationsSettingsResponse {
	pb_callback_t telegram_id;
	pb_callback_t notifications;
} PersonsGetNotificationsSettingsResponse;

typedef struct _PersonsSetNotificationsSettingsPayload {
	int32_t person_id;
	pb_callback_t telegram_id;
	pb_callback_t notifications;
} PersonsSetNotificationsSettingsPayload;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AuthRequestRegistrationPayload_init_default     \
	{                                               \
		{ { NULL }, NULL }, { { NULL }, NULL }, \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define AuthRequestRegistrationResponse_init_default \
	{                                            \
		{                                    \
			{ NULL }, NULL               \
		}                                    \
	}
#define AuthApproveRegistrationPayload_init_default \
	{                                           \
		{                                   \
			{ NULL }, NULL              \
		}                                   \
	}
#define AuthApproveRegistrationResponse_init_default { 0 }
#define AuthAuthorizePayload_init_default \
	{                                 \
		{ { NULL }, NULL },       \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define AuthAuthorizeResponse_init_default \
	{                                  \
		0,                         \
		{                          \
			{ NULL }, NULL     \
		}                          \
	}
#define AuthQuickAuthorizePayload_init_default \
	{                                      \
		0,                             \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define AuthQuickAuthorizeResponse_init_default { 0 }
#define AuthMePayload_init_default { 0 }
#define AuthMeResponse_init_default                                                                                    \
	{                                                                                                              \
		0, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
			{ { NULL }, NULL }, 0,                                                                         \
		{                                                                                                      \
			{ NULL }, NULL                                                                                 \
		}                                                                                                      \
	}
#define AuthChangePasswordPayload_init_default          \
	{                                               \
		{ { NULL }, NULL }, { { NULL }, NULL }, \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define AuthChangePasswordResponse_init_default \
	{                                       \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define AuthRequestResetPasswordPayload_init_default \
	{                                            \
		{                                    \
			{ NULL }, NULL               \
		}                                    \
	}
#define AuthRequestResetPasswordResponse_init_default \
	{                                             \
		{                                     \
			{ NULL }, NULL                \
		}                                     \
	}
#define AuthApproveResetPasswordPayload_init_default \
	{                                            \
		{ { NULL }, NULL },                  \
		{                                    \
			{ NULL }, NULL               \
		}                                    \
	}
#define AuthApproveResetPasswordResponse_init_default \
	{                                             \
		{                                     \
			{ NULL }, NULL                \
		}                                     \
	}
#define AccessGetEventAdminsPayload_init_default { 0 }
#define AccessGetEventAdminsResponse_init_default \
	{                                         \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define AccessGetEventRefereesPayload_init_default { 0 }
#define AccessGetEventRefereesResponse_init_default \
	{                                           \
		{                                   \
			{ NULL }, NULL              \
		}                                   \
	}
#define AccessGetSuperadminFlagPayload_init_default { 0 }
#define AccessGetSuperadminFlagResponse_init_default { 0 }
#define AccessGetOwnedEventIdsPayload_init_default { 0 }
#define AccessGetOwnedEventIdsResponse_init_default \
	{                                           \
		{                                   \
			{ NULL }, NULL              \
		}                                   \
	}
#define AccessAddRuleForPersonPayload_init_default { { { NULL }, NULL }, 0, 0, 0 }
#define AccessAddRuleForPersonResponse_init_default { 0 }
#define AccessDeleteRuleForPersonPayload_init_default { 0 }
#define PersonsCreateAccountPayload_init_default                                                                    \
	{                                                                                                           \
		{ { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
			{ { NULL }, NULL },                                                                         \
		{                                                                                                   \
			{ NULL }, NULL                                                                              \
		}                                                                                                   \
	}
#define PersonsCreateAccountResponse_init_default { 0 }
#define PersonsUpdatePersonalInfoPayload_init_default \
	{ 0,                                          \
	  { { NULL }, NULL },                         \
	  { { NULL }, NULL },                         \
	  { { NULL }, NULL },                         \
	  { { NULL }, NULL },                         \
	  { { NULL }, NULL },                         \
	  { { NULL }, NULL },                         \
	  0,                                          \
	  { { NULL }, NULL },                         \
	  { { NULL }, NULL },                         \
	  false,                                      \
	  0,                                          \
	  false,                                      \
	  0 }
#define PersonsGetPersonalInfoPayload_init_default \
	{                                          \
		{                                  \
			{ NULL }, NULL             \
		}                                  \
	}
#define PersonsGetPersonalInfoResponse_init_default \
	{                                           \
		{                                   \
			{ NULL }, NULL              \
		}                                   \
	}
#define PersonsFindByTenhouIdsPayload_init_default \
	{                                          \
		{                                  \
			{ NULL }, NULL             \
		}                                  \
	}
#define PersonsFindByMajsoulIdsPayload_init_default \
	{                                           \
		{                                   \
			{ NULL }, NULL              \
		}                                   \
	}
#define PersonsFindByTenhouIdsResponse_init_default \
	{                                           \
		{                                   \
			{ NULL }, NULL              \
		}                                   \
	}
#define PersonsFindByTitlePayload_init_default \
	{                                      \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define PersonsFindByTitleResponse_init_default \
	{                                       \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define DepersonalizePayload_init_default { 0 }
#define PersonsGetMajsoulNicknamesPayload_init_default \
	{                                              \
		{                                      \
			{ NULL }, NULL                 \
		}                                      \
	}
#define PersonsGetMajsoulNicknamesResponse_init_default \
	{                                               \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define PersonsGetNotificationsSettingsPayload_init_default { 0 }
#define PersonsGetNotificationsSettingsResponse_init_default \
	{                                                    \
		{ { NULL }, NULL },                          \
		{                                            \
			{ NULL }, NULL                       \
		}                                            \
	}
#define PersonsSetNotificationsSettingsPayload_init_default \
	{                                                   \
		0, { { NULL }, NULL },                      \
		{                                           \
			{ NULL }, NULL                      \
		}                                           \
	}
#define AuthRequestRegistrationPayload_init_zero        \
	{                                               \
		{ { NULL }, NULL }, { { NULL }, NULL }, \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define AuthRequestRegistrationResponse_init_zero \
	{                                         \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define AuthApproveRegistrationPayload_init_zero \
	{                                        \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define AuthApproveRegistrationResponse_init_zero { 0 }
#define AuthAuthorizePayload_init_zero \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define AuthAuthorizeResponse_init_zero \
	{                               \
		0,                      \
		{                       \
			{ NULL }, NULL  \
		}                       \
	}
#define AuthQuickAuthorizePayload_init_zero \
	{                                   \
		0,                          \
		{                           \
			{ NULL }, NULL      \
		}                           \
	}
#define AuthQuickAuthorizeResponse_init_zero { 0 }
#define AuthMePayload_init_zero { 0 }
#define AuthMeResponse_init_zero                                                                                       \
	{                                                                                                              \
		0, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
			{ { NULL }, NULL }, 0,                                                                         \
		{                                                                                                      \
			{ NULL }, NULL                                                                                 \
		}                                                                                                      \
	}
#define AuthChangePasswordPayload_init_zero             \
	{                                               \
		{ { NULL }, NULL }, { { NULL }, NULL }, \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define AuthChangePasswordResponse_init_zero \
	{                                    \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define AuthRequestResetPasswordPayload_init_zero \
	{                                         \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define AuthRequestResetPasswordResponse_init_zero \
	{                                          \
		{                                  \
			{ NULL }, NULL             \
		}                                  \
	}
#define AuthApproveResetPasswordPayload_init_zero \
	{                                         \
		{ { NULL }, NULL },               \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define AuthApproveResetPasswordResponse_init_zero \
	{                                          \
		{                                  \
			{ NULL }, NULL             \
		}                                  \
	}
#define AccessGetEventAdminsPayload_init_zero { 0 }
#define AccessGetEventAdminsResponse_init_zero \
	{                                      \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define AccessGetEventRefereesPayload_init_zero { 0 }
#define AccessGetEventRefereesResponse_init_zero \
	{                                        \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define AccessGetSuperadminFlagPayload_init_zero { 0 }
#define AccessGetSuperadminFlagResponse_init_zero { 0 }
#define AccessGetOwnedEventIdsPayload_init_zero { 0 }
#define AccessGetOwnedEventIdsResponse_init_zero \
	{                                        \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define AccessAddRuleForPersonPayload_init_zero { { { NULL }, NULL }, 0, 0, 0 }
#define AccessAddRuleForPersonResponse_init_zero { 0 }
#define AccessDeleteRuleForPersonPayload_init_zero { 0 }
#define PersonsCreateAccountPayload_init_zero                                                                       \
	{                                                                                                           \
		{ { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
			{ { NULL }, NULL },                                                                         \
		{                                                                                                   \
			{ NULL }, NULL                                                                              \
		}                                                                                                   \
	}
#define PersonsCreateAccountResponse_init_zero { 0 }
#define PersonsUpdatePersonalInfoPayload_init_zero \
	{ 0,                                       \
	  { { NULL }, NULL },                      \
	  { { NULL }, NULL },                      \
	  { { NULL }, NULL },                      \
	  { { NULL }, NULL },                      \
	  { { NULL }, NULL },                      \
	  { { NULL }, NULL },                      \
	  0,                                       \
	  { { NULL }, NULL },                      \
	  { { NULL }, NULL },                      \
	  false,                                   \
	  0,                                       \
	  false,                                   \
	  0 }
#define PersonsGetPersonalInfoPayload_init_zero \
	{                                       \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define PersonsGetPersonalInfoResponse_init_zero \
	{                                        \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define PersonsFindByTenhouIdsPayload_init_zero \
	{                                       \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define PersonsFindByMajsoulIdsPayload_init_zero \
	{                                        \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define PersonsFindByTenhouIdsResponse_init_zero \
	{                                        \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define PersonsFindByTitlePayload_init_zero \
	{                                   \
		{                           \
			{ NULL }, NULL      \
		}                           \
	}
#define PersonsFindByTitleResponse_init_zero \
	{                                    \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define DepersonalizePayload_init_zero { 0 }
#define PersonsGetMajsoulNicknamesPayload_init_zero \
	{                                           \
		{                                   \
			{ NULL }, NULL              \
		}                                   \
	}
#define PersonsGetMajsoulNicknamesResponse_init_zero \
	{                                            \
		{                                    \
			{ NULL }, NULL               \
		}                                    \
	}
#define PersonsGetNotificationsSettingsPayload_init_zero { 0 }
#define PersonsGetNotificationsSettingsResponse_init_zero \
	{                                                 \
		{ { NULL }, NULL },                       \
		{                                         \
			{ NULL }, NULL                    \
		}                                         \
	}
#define PersonsSetNotificationsSettingsPayload_init_zero \
	{                                                \
		0, { { NULL }, NULL },                   \
		{                                        \
			{ NULL }, NULL                   \
		}                                        \
	}

/* Field tags (for use in manual encoding/decoding) */
#define AuthRequestRegistrationPayload_email_tag 1
#define AuthRequestRegistrationPayload_title_tag 2
#define AuthRequestRegistrationPayload_password_tag 3
#define AuthRequestRegistrationResponse_approval_code_tag 1
#define AuthApproveRegistrationPayload_approval_code_tag 1
#define AuthApproveRegistrationResponse_person_id_tag 1
#define AuthAuthorizePayload_email_tag 1
#define AuthAuthorizePayload_password_tag 2
#define AuthAuthorizeResponse_person_id_tag 1
#define AuthAuthorizeResponse_auth_token_tag 2
#define AuthQuickAuthorizePayload_person_id_tag 1
#define AuthQuickAuthorizePayload_auth_token_tag 2
#define AuthQuickAuthorizeResponse_auth_success_tag 1
#define AuthMeResponse_person_id_tag 1
#define AuthMeResponse_country_tag 2
#define AuthMeResponse_city_tag 3
#define AuthMeResponse_email_tag 4
#define AuthMeResponse_phone_tag 5
#define AuthMeResponse_tenhou_id_tag 6
#define AuthMeResponse_title_tag 7
#define AuthMeResponse_has_avatar_tag 9
#define AuthMeResponse_last_update_tag 10
#define AuthChangePasswordPayload_email_tag 1
#define AuthChangePasswordPayload_password_tag 2
#define AuthChangePasswordPayload_new_password_tag 3
#define AuthChangePasswordResponse_auth_token_tag 1
#define AuthRequestResetPasswordPayload_email_tag 1
#define AuthRequestResetPasswordResponse_reset_token_tag 1
#define AuthApproveResetPasswordPayload_email_tag 1
#define AuthApproveResetPasswordPayload_reset_token_tag 2
#define AuthApproveResetPasswordResponse_new_tmp_password_tag 1
#define AccessGetEventAdminsPayload_event_id_tag 1
#define AccessGetEventAdminsResponse_admins_tag 1
#define AccessGetEventRefereesPayload_event_id_tag 1
#define AccessGetEventRefereesResponse_referees_tag 1
#define AccessGetSuperadminFlagPayload_person_id_tag 1
#define AccessGetSuperadminFlagResponse_is_admin_tag 1
#define AccessGetOwnedEventIdsPayload_person_id_tag 1
#define AccessGetOwnedEventIdsResponse_event_ids_tag 1
#define AccessAddRuleForPersonPayload_rule_name_tag 1
#define AccessAddRuleForPersonPayload_rule_value_tag 2
#define AccessAddRuleForPersonPayload_person_id_tag 3
#define AccessAddRuleForPersonPayload_event_id_tag 4
#define AccessAddRuleForPersonResponse_rule_id_tag 1
#define AccessDeleteRuleForPersonPayload_rule_id_tag 1
#define PersonsCreateAccountPayload_email_tag 1
#define PersonsCreateAccountPayload_password_tag 2
#define PersonsCreateAccountPayload_title_tag 3
#define PersonsCreateAccountPayload_city_tag 4
#define PersonsCreateAccountPayload_phone_tag 5
#define PersonsCreateAccountPayload_tenhou_id_tag 6
#define PersonsCreateAccountPayload_country_tag 7
#define PersonsCreateAccountResponse_person_id_tag 1
#define PersonsUpdatePersonalInfoPayload_id_tag 1
#define PersonsUpdatePersonalInfoPayload_title_tag 2
#define PersonsUpdatePersonalInfoPayload_country_tag 3
#define PersonsUpdatePersonalInfoPayload_city_tag 4
#define PersonsUpdatePersonalInfoPayload_email_tag 5
#define PersonsUpdatePersonalInfoPayload_phone_tag 6
#define PersonsUpdatePersonalInfoPayload_tenhou_id_tag 7
#define PersonsUpdatePersonalInfoPayload_has_avatar_tag 8
#define PersonsUpdatePersonalInfoPayload_avatar_data_tag 9
#define PersonsUpdatePersonalInfoPayload_ms_nickname_tag 10
#define PersonsUpdatePersonalInfoPayload_ms_friend_id_tag 11
#define PersonsUpdatePersonalInfoPayload_ms_account_id_tag 12
#define PersonsGetPersonalInfoPayload_ids_tag 1
#define PersonsGetPersonalInfoResponse_people_tag 1
#define PersonsFindByTenhouIdsPayload_ids_tag 1
#define PersonsFindByMajsoulIdsPayload_ids_tag 1
#define PersonsFindByTenhouIdsResponse_people_tag 1
#define PersonsFindByTitlePayload_query_tag 1
#define PersonsFindByTitleResponse_people_tag 1
#define PersonsGetMajsoulNicknamesPayload_ids_tag 1
#define PersonsGetMajsoulNicknamesResponse_mapping_tag 1
#define PersonsGetNotificationsSettingsPayload_person_id_tag 1
#define PersonsGetNotificationsSettingsResponse_telegram_id_tag 1
#define PersonsGetNotificationsSettingsResponse_notifications_tag 2
#define PersonsSetNotificationsSettingsPayload_person_id_tag 1
#define PersonsSetNotificationsSettingsPayload_telegram_id_tag 2
#define PersonsSetNotificationsSettingsPayload_notifications_tag 3

/* Struct field encoding specification for nanopb */
#define AuthRequestRegistrationPayload_FIELDLIST(X, a) \
	X(a, CALLBACK, SINGULAR, STRING, email, 1)     \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)     \
	X(a, CALLBACK, SINGULAR, STRING, password, 3)
#define AuthRequestRegistrationPayload_CALLBACK pb_default_field_callback
#define AuthRequestRegistrationPayload_DEFAULT NULL

#define AuthRequestRegistrationResponse_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, approval_code, 1)
#define AuthRequestRegistrationResponse_CALLBACK pb_default_field_callback
#define AuthRequestRegistrationResponse_DEFAULT NULL

#define AuthApproveRegistrationPayload_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, approval_code, 1)
#define AuthApproveRegistrationPayload_CALLBACK pb_default_field_callback
#define AuthApproveRegistrationPayload_DEFAULT NULL

#define AuthApproveRegistrationResponse_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, person_id, 1)
#define AuthApproveRegistrationResponse_CALLBACK NULL
#define AuthApproveRegistrationResponse_DEFAULT NULL

#define AuthAuthorizePayload_FIELDLIST(X, a)       \
	X(a, CALLBACK, SINGULAR, STRING, email, 1) \
	X(a, CALLBACK, SINGULAR, STRING, password, 2)
#define AuthAuthorizePayload_CALLBACK pb_default_field_callback
#define AuthAuthorizePayload_DEFAULT NULL

#define AuthAuthorizeResponse_FIELDLIST(X, a)       \
	X(a, STATIC, SINGULAR, INT32, person_id, 1) \
	X(a, CALLBACK, SINGULAR, STRING, auth_token, 2)
#define AuthAuthorizeResponse_CALLBACK pb_default_field_callback
#define AuthAuthorizeResponse_DEFAULT NULL

#define AuthQuickAuthorizePayload_FIELDLIST(X, a)   \
	X(a, STATIC, SINGULAR, INT32, person_id, 1) \
	X(a, CALLBACK, SINGULAR, STRING, auth_token, 2)
#define AuthQuickAuthorizePayload_CALLBACK pb_default_field_callback
#define AuthQuickAuthorizePayload_DEFAULT NULL

#define AuthQuickAuthorizeResponse_FIELDLIST(X, a) X(a, STATIC, SINGULAR, BOOL, auth_success, 1)
#define AuthQuickAuthorizeResponse_CALLBACK NULL
#define AuthQuickAuthorizeResponse_DEFAULT NULL

#define AuthMePayload_FIELDLIST(X, a)

#define AuthMePayload_CALLBACK NULL
#define AuthMePayload_DEFAULT NULL

#define AuthMeResponse_FIELDLIST(X, a)                 \
	X(a, STATIC, SINGULAR, INT32, person_id, 1)    \
	X(a, CALLBACK, SINGULAR, STRING, country, 2)   \
	X(a, CALLBACK, SINGULAR, STRING, city, 3)      \
	X(a, CALLBACK, SINGULAR, STRING, email, 4)     \
	X(a, CALLBACK, SINGULAR, STRING, phone, 5)     \
	X(a, CALLBACK, SINGULAR, STRING, tenhou_id, 6) \
	X(a, CALLBACK, SINGULAR, STRING, title, 7)     \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 9)    \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 10)
#define AuthMeResponse_CALLBACK pb_default_field_callback
#define AuthMeResponse_DEFAULT NULL

#define AuthChangePasswordPayload_FIELDLIST(X, a)     \
	X(a, CALLBACK, SINGULAR, STRING, email, 1)    \
	X(a, CALLBACK, SINGULAR, STRING, password, 2) \
	X(a, CALLBACK, SINGULAR, STRING, new_password, 3)
#define AuthChangePasswordPayload_CALLBACK pb_default_field_callback
#define AuthChangePasswordPayload_DEFAULT NULL

#define AuthChangePasswordResponse_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, auth_token, 1)
#define AuthChangePasswordResponse_CALLBACK pb_default_field_callback
#define AuthChangePasswordResponse_DEFAULT NULL

#define AuthRequestResetPasswordPayload_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, email, 1)
#define AuthRequestResetPasswordPayload_CALLBACK pb_default_field_callback
#define AuthRequestResetPasswordPayload_DEFAULT NULL

#define AuthRequestResetPasswordResponse_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, reset_token, 1)
#define AuthRequestResetPasswordResponse_CALLBACK pb_default_field_callback
#define AuthRequestResetPasswordResponse_DEFAULT NULL

#define AuthApproveResetPasswordPayload_FIELDLIST(X, a) \
	X(a, CALLBACK, SINGULAR, STRING, email, 1)      \
	X(a, CALLBACK, SINGULAR, STRING, reset_token, 2)
#define AuthApproveResetPasswordPayload_CALLBACK pb_default_field_callback
#define AuthApproveResetPasswordPayload_DEFAULT NULL

#define AuthApproveResetPasswordResponse_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, new_tmp_password, 1)
#define AuthApproveResetPasswordResponse_CALLBACK pb_default_field_callback
#define AuthApproveResetPasswordResponse_DEFAULT NULL

#define AccessGetEventAdminsPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, event_id, 1)
#define AccessGetEventAdminsPayload_CALLBACK NULL
#define AccessGetEventAdminsPayload_DEFAULT NULL

#define AccessGetEventAdminsResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, admins, 1)
#define AccessGetEventAdminsResponse_CALLBACK pb_default_field_callback
#define AccessGetEventAdminsResponse_DEFAULT NULL
#define AccessGetEventAdminsResponse_admins_MSGTYPE EventAdmin

#define AccessGetEventRefereesPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, event_id, 1)
#define AccessGetEventRefereesPayload_CALLBACK NULL
#define AccessGetEventRefereesPayload_DEFAULT NULL

#define AccessGetEventRefereesResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, referees, 1)
#define AccessGetEventRefereesResponse_CALLBACK pb_default_field_callback
#define AccessGetEventRefereesResponse_DEFAULT NULL
#define AccessGetEventRefereesResponse_referees_MSGTYPE EventReferee

#define AccessGetSuperadminFlagPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, person_id, 1)
#define AccessGetSuperadminFlagPayload_CALLBACK NULL
#define AccessGetSuperadminFlagPayload_DEFAULT NULL

#define AccessGetSuperadminFlagResponse_FIELDLIST(X, a) X(a, STATIC, SINGULAR, BOOL, is_admin, 1)
#define AccessGetSuperadminFlagResponse_CALLBACK NULL
#define AccessGetSuperadminFlagResponse_DEFAULT NULL

#define AccessGetOwnedEventIdsPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, person_id, 1)
#define AccessGetOwnedEventIdsPayload_CALLBACK NULL
#define AccessGetOwnedEventIdsPayload_DEFAULT NULL

#define AccessGetOwnedEventIdsResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, INT32, event_ids, 1)
#define AccessGetOwnedEventIdsResponse_CALLBACK pb_default_field_callback
#define AccessGetOwnedEventIdsResponse_DEFAULT NULL

#define AccessAddRuleForPersonPayload_FIELDLIST(X, a)  \
	X(a, CALLBACK, SINGULAR, STRING, rule_name, 1) \
	X(a, STATIC, SINGULAR, INT32, rule_value, 2)   \
	X(a, STATIC, SINGULAR, INT32, person_id, 3)    \
	X(a, STATIC, SINGULAR, INT32, event_id, 4)
#define AccessAddRuleForPersonPayload_CALLBACK pb_default_field_callback
#define AccessAddRuleForPersonPayload_DEFAULT NULL

#define AccessAddRuleForPersonResponse_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, rule_id, 1)
#define AccessAddRuleForPersonResponse_CALLBACK NULL
#define AccessAddRuleForPersonResponse_DEFAULT NULL

#define AccessDeleteRuleForPersonPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, rule_id, 1)
#define AccessDeleteRuleForPersonPayload_CALLBACK NULL
#define AccessDeleteRuleForPersonPayload_DEFAULT NULL

#define PersonsCreateAccountPayload_FIELDLIST(X, a)    \
	X(a, CALLBACK, SINGULAR, STRING, email, 1)     \
	X(a, CALLBACK, SINGULAR, STRING, password, 2)  \
	X(a, CALLBACK, SINGULAR, STRING, title, 3)     \
	X(a, CALLBACK, SINGULAR, STRING, city, 4)      \
	X(a, CALLBACK, SINGULAR, STRING, phone, 5)     \
	X(a, CALLBACK, SINGULAR, STRING, tenhou_id, 6) \
	X(a, CALLBACK, SINGULAR, STRING, country, 7)
#define PersonsCreateAccountPayload_CALLBACK pb_default_field_callback
#define PersonsCreateAccountPayload_DEFAULT NULL

#define PersonsCreateAccountResponse_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, person_id, 1)
#define PersonsCreateAccountResponse_CALLBACK NULL
#define PersonsCreateAccountResponse_DEFAULT NULL

#define PersonsUpdatePersonalInfoPayload_FIELDLIST(X, a)  \
	X(a, STATIC, SINGULAR, INT32, id, 1)              \
	X(a, CALLBACK, SINGULAR, STRING, title, 2)        \
	X(a, CALLBACK, SINGULAR, STRING, country, 3)      \
	X(a, CALLBACK, SINGULAR, STRING, city, 4)         \
	X(a, CALLBACK, SINGULAR, STRING, email, 5)        \
	X(a, CALLBACK, SINGULAR, STRING, phone, 6)        \
	X(a, CALLBACK, SINGULAR, STRING, tenhou_id, 7)    \
	X(a, STATIC, SINGULAR, BOOL, has_avatar, 8)       \
	X(a, CALLBACK, SINGULAR, STRING, avatar_data, 9)  \
	X(a, CALLBACK, OPTIONAL, STRING, ms_nickname, 10) \
	X(a, STATIC, OPTIONAL, INT32, ms_friend_id, 11)   \
	X(a, STATIC, OPTIONAL, INT32, ms_account_id, 12)
#define PersonsUpdatePersonalInfoPayload_CALLBACK pb_default_field_callback
#define PersonsUpdatePersonalInfoPayload_DEFAULT NULL

#define PersonsGetPersonalInfoPayload_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, INT32, ids, 1)
#define PersonsGetPersonalInfoPayload_CALLBACK pb_default_field_callback
#define PersonsGetPersonalInfoPayload_DEFAULT NULL

#define PersonsGetPersonalInfoResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, people, 1)
#define PersonsGetPersonalInfoResponse_CALLBACK pb_default_field_callback
#define PersonsGetPersonalInfoResponse_DEFAULT NULL
#define PersonsGetPersonalInfoResponse_people_MSGTYPE PersonEx

#define PersonsFindByTenhouIdsPayload_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, STRING, ids, 1)
#define PersonsFindByTenhouIdsPayload_CALLBACK pb_default_field_callback
#define PersonsFindByTenhouIdsPayload_DEFAULT NULL

#define PersonsFindByMajsoulIdsPayload_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, ids, 1)
#define PersonsFindByMajsoulIdsPayload_CALLBACK pb_default_field_callback
#define PersonsFindByMajsoulIdsPayload_DEFAULT NULL
#define PersonsFindByMajsoulIdsPayload_ids_MSGTYPE MajsoulSearchEx

#define PersonsFindByTenhouIdsResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, people, 1)
#define PersonsFindByTenhouIdsResponse_CALLBACK pb_default_field_callback
#define PersonsFindByTenhouIdsResponse_DEFAULT NULL
#define PersonsFindByTenhouIdsResponse_people_MSGTYPE PersonEx

#define PersonsFindByTitlePayload_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, STRING, query, 1)
#define PersonsFindByTitlePayload_CALLBACK pb_default_field_callback
#define PersonsFindByTitlePayload_DEFAULT NULL

#define PersonsFindByTitleResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, people, 1)
#define PersonsFindByTitleResponse_CALLBACK pb_default_field_callback
#define PersonsFindByTitleResponse_DEFAULT NULL
#define PersonsFindByTitleResponse_people_MSGTYPE Person

#define DepersonalizePayload_FIELDLIST(X, a)

#define DepersonalizePayload_CALLBACK NULL
#define DepersonalizePayload_DEFAULT NULL

#define PersonsGetMajsoulNicknamesPayload_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, INT32, ids, 1)
#define PersonsGetMajsoulNicknamesPayload_CALLBACK pb_default_field_callback
#define PersonsGetMajsoulNicknamesPayload_DEFAULT NULL

#define PersonsGetMajsoulNicknamesResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, mapping, 1)
#define PersonsGetMajsoulNicknamesResponse_CALLBACK pb_default_field_callback
#define PersonsGetMajsoulNicknamesResponse_DEFAULT NULL
#define PersonsGetMajsoulNicknamesResponse_mapping_MSGTYPE MajsoulPersonMapping

#define PersonsGetNotificationsSettingsPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, person_id, 1)
#define PersonsGetNotificationsSettingsPayload_CALLBACK NULL
#define PersonsGetNotificationsSettingsPayload_DEFAULT NULL

#define PersonsGetNotificationsSettingsResponse_FIELDLIST(X, a) \
	X(a, CALLBACK, SINGULAR, STRING, telegram_id, 1)        \
	X(a, CALLBACK, SINGULAR, STRING, notifications, 2)
#define PersonsGetNotificationsSettingsResponse_CALLBACK pb_default_field_callback
#define PersonsGetNotificationsSettingsResponse_DEFAULT NULL

#define PersonsSetNotificationsSettingsPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, person_id, 1)            \
	X(a, CALLBACK, SINGULAR, STRING, telegram_id, 2)       \
	X(a, CALLBACK, SINGULAR, STRING, notifications, 3)
#define PersonsSetNotificationsSettingsPayload_CALLBACK pb_default_field_callback
#define PersonsSetNotificationsSettingsPayload_DEFAULT NULL

extern const pb_msgdesc_t AuthRequestRegistrationPayload_msg;
extern const pb_msgdesc_t AuthRequestRegistrationResponse_msg;
extern const pb_msgdesc_t AuthApproveRegistrationPayload_msg;
extern const pb_msgdesc_t AuthApproveRegistrationResponse_msg;
extern const pb_msgdesc_t AuthAuthorizePayload_msg;
extern const pb_msgdesc_t AuthAuthorizeResponse_msg;
extern const pb_msgdesc_t AuthQuickAuthorizePayload_msg;
extern const pb_msgdesc_t AuthQuickAuthorizeResponse_msg;
extern const pb_msgdesc_t AuthMePayload_msg;
extern const pb_msgdesc_t AuthMeResponse_msg;
extern const pb_msgdesc_t AuthChangePasswordPayload_msg;
extern const pb_msgdesc_t AuthChangePasswordResponse_msg;
extern const pb_msgdesc_t AuthRequestResetPasswordPayload_msg;
extern const pb_msgdesc_t AuthRequestResetPasswordResponse_msg;
extern const pb_msgdesc_t AuthApproveResetPasswordPayload_msg;
extern const pb_msgdesc_t AuthApproveResetPasswordResponse_msg;
extern const pb_msgdesc_t AccessGetEventAdminsPayload_msg;
extern const pb_msgdesc_t AccessGetEventAdminsResponse_msg;
extern const pb_msgdesc_t AccessGetEventRefereesPayload_msg;
extern const pb_msgdesc_t AccessGetEventRefereesResponse_msg;
extern const pb_msgdesc_t AccessGetSuperadminFlagPayload_msg;
extern const pb_msgdesc_t AccessGetSuperadminFlagResponse_msg;
extern const pb_msgdesc_t AccessGetOwnedEventIdsPayload_msg;
extern const pb_msgdesc_t AccessGetOwnedEventIdsResponse_msg;
extern const pb_msgdesc_t AccessAddRuleForPersonPayload_msg;
extern const pb_msgdesc_t AccessAddRuleForPersonResponse_msg;
extern const pb_msgdesc_t AccessDeleteRuleForPersonPayload_msg;
extern const pb_msgdesc_t PersonsCreateAccountPayload_msg;
extern const pb_msgdesc_t PersonsCreateAccountResponse_msg;
extern const pb_msgdesc_t PersonsUpdatePersonalInfoPayload_msg;
extern const pb_msgdesc_t PersonsGetPersonalInfoPayload_msg;
extern const pb_msgdesc_t PersonsGetPersonalInfoResponse_msg;
extern const pb_msgdesc_t PersonsFindByTenhouIdsPayload_msg;
extern const pb_msgdesc_t PersonsFindByMajsoulIdsPayload_msg;
extern const pb_msgdesc_t PersonsFindByTenhouIdsResponse_msg;
extern const pb_msgdesc_t PersonsFindByTitlePayload_msg;
extern const pb_msgdesc_t PersonsFindByTitleResponse_msg;
extern const pb_msgdesc_t DepersonalizePayload_msg;
extern const pb_msgdesc_t PersonsGetMajsoulNicknamesPayload_msg;
extern const pb_msgdesc_t PersonsGetMajsoulNicknamesResponse_msg;
extern const pb_msgdesc_t PersonsGetNotificationsSettingsPayload_msg;
extern const pb_msgdesc_t PersonsGetNotificationsSettingsResponse_msg;
extern const pb_msgdesc_t PersonsSetNotificationsSettingsPayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AuthRequestRegistrationPayload_fields &AuthRequestRegistrationPayload_msg
#define AuthRequestRegistrationResponse_fields &AuthRequestRegistrationResponse_msg
#define AuthApproveRegistrationPayload_fields &AuthApproveRegistrationPayload_msg
#define AuthApproveRegistrationResponse_fields &AuthApproveRegistrationResponse_msg
#define AuthAuthorizePayload_fields &AuthAuthorizePayload_msg
#define AuthAuthorizeResponse_fields &AuthAuthorizeResponse_msg
#define AuthQuickAuthorizePayload_fields &AuthQuickAuthorizePayload_msg
#define AuthQuickAuthorizeResponse_fields &AuthQuickAuthorizeResponse_msg
#define AuthMePayload_fields &AuthMePayload_msg
#define AuthMeResponse_fields &AuthMeResponse_msg
#define AuthChangePasswordPayload_fields &AuthChangePasswordPayload_msg
#define AuthChangePasswordResponse_fields &AuthChangePasswordResponse_msg
#define AuthRequestResetPasswordPayload_fields &AuthRequestResetPasswordPayload_msg
#define AuthRequestResetPasswordResponse_fields &AuthRequestResetPasswordResponse_msg
#define AuthApproveResetPasswordPayload_fields &AuthApproveResetPasswordPayload_msg
#define AuthApproveResetPasswordResponse_fields &AuthApproveResetPasswordResponse_msg
#define AccessGetEventAdminsPayload_fields &AccessGetEventAdminsPayload_msg
#define AccessGetEventAdminsResponse_fields &AccessGetEventAdminsResponse_msg
#define AccessGetEventRefereesPayload_fields &AccessGetEventRefereesPayload_msg
#define AccessGetEventRefereesResponse_fields &AccessGetEventRefereesResponse_msg
#define AccessGetSuperadminFlagPayload_fields &AccessGetSuperadminFlagPayload_msg
#define AccessGetSuperadminFlagResponse_fields &AccessGetSuperadminFlagResponse_msg
#define AccessGetOwnedEventIdsPayload_fields &AccessGetOwnedEventIdsPayload_msg
#define AccessGetOwnedEventIdsResponse_fields &AccessGetOwnedEventIdsResponse_msg
#define AccessAddRuleForPersonPayload_fields &AccessAddRuleForPersonPayload_msg
#define AccessAddRuleForPersonResponse_fields &AccessAddRuleForPersonResponse_msg
#define AccessDeleteRuleForPersonPayload_fields &AccessDeleteRuleForPersonPayload_msg
#define PersonsCreateAccountPayload_fields &PersonsCreateAccountPayload_msg
#define PersonsCreateAccountResponse_fields &PersonsCreateAccountResponse_msg
#define PersonsUpdatePersonalInfoPayload_fields &PersonsUpdatePersonalInfoPayload_msg
#define PersonsGetPersonalInfoPayload_fields &PersonsGetPersonalInfoPayload_msg
#define PersonsGetPersonalInfoResponse_fields &PersonsGetPersonalInfoResponse_msg
#define PersonsFindByTenhouIdsPayload_fields &PersonsFindByTenhouIdsPayload_msg
#define PersonsFindByMajsoulIdsPayload_fields &PersonsFindByMajsoulIdsPayload_msg
#define PersonsFindByTenhouIdsResponse_fields &PersonsFindByTenhouIdsResponse_msg
#define PersonsFindByTitlePayload_fields &PersonsFindByTitlePayload_msg
#define PersonsFindByTitleResponse_fields &PersonsFindByTitleResponse_msg
#define DepersonalizePayload_fields &DepersonalizePayload_msg
#define PersonsGetMajsoulNicknamesPayload_fields &PersonsGetMajsoulNicknamesPayload_msg
#define PersonsGetMajsoulNicknamesResponse_fields &PersonsGetMajsoulNicknamesResponse_msg
#define PersonsGetNotificationsSettingsPayload_fields &PersonsGetNotificationsSettingsPayload_msg
#define PersonsGetNotificationsSettingsResponse_fields &PersonsGetNotificationsSettingsResponse_msg
#define PersonsSetNotificationsSettingsPayload_fields &PersonsSetNotificationsSettingsPayload_msg

/* Maximum encoded size of messages (where known) */
/* AuthRequestRegistrationPayload_size depends on runtime parameters */
/* AuthRequestRegistrationResponse_size depends on runtime parameters */
/* AuthApproveRegistrationPayload_size depends on runtime parameters */
/* AuthAuthorizePayload_size depends on runtime parameters */
/* AuthAuthorizeResponse_size depends on runtime parameters */
/* AuthQuickAuthorizePayload_size depends on runtime parameters */
/* AuthMeResponse_size depends on runtime parameters */
/* AuthChangePasswordPayload_size depends on runtime parameters */
/* AuthChangePasswordResponse_size depends on runtime parameters */
/* AuthRequestResetPasswordPayload_size depends on runtime parameters */
/* AuthRequestResetPasswordResponse_size depends on runtime parameters */
/* AuthApproveResetPasswordPayload_size depends on runtime parameters */
/* AuthApproveResetPasswordResponse_size depends on runtime parameters */
/* AccessGetEventAdminsResponse_size depends on runtime parameters */
/* AccessGetEventRefereesResponse_size depends on runtime parameters */
/* AccessGetOwnedEventIdsResponse_size depends on runtime parameters */
/* AccessAddRuleForPersonPayload_size depends on runtime parameters */
/* PersonsCreateAccountPayload_size depends on runtime parameters */
/* PersonsUpdatePersonalInfoPayload_size depends on runtime parameters */
/* PersonsGetPersonalInfoPayload_size depends on runtime parameters */
/* PersonsGetPersonalInfoResponse_size depends on runtime parameters */
/* PersonsFindByTenhouIdsPayload_size depends on runtime parameters */
/* PersonsFindByMajsoulIdsPayload_size depends on runtime parameters */
/* PersonsFindByTenhouIdsResponse_size depends on runtime parameters */
/* PersonsFindByTitlePayload_size depends on runtime parameters */
/* PersonsFindByTitleResponse_size depends on runtime parameters */
/* PersonsGetMajsoulNicknamesPayload_size depends on runtime parameters */
/* PersonsGetMajsoulNicknamesResponse_size depends on runtime parameters */
/* PersonsGetNotificationsSettingsResponse_size depends on runtime parameters */
/* PersonsSetNotificationsSettingsPayload_size depends on runtime parameters */
#define AccessAddRuleForPersonResponse_size 11
#define AccessDeleteRuleForPersonPayload_size 11
#define AccessGetEventAdminsPayload_size 11
#define AccessGetEventRefereesPayload_size 11
#define AccessGetOwnedEventIdsPayload_size 11
#define AccessGetSuperadminFlagPayload_size 11
#define AccessGetSuperadminFlagResponse_size 2
#define AuthApproveRegistrationResponse_size 11
#define AuthMePayload_size 0
#define AuthQuickAuthorizeResponse_size 2
#define DepersonalizePayload_size 0
#define PROTO_FREY_PB_H_MAX_SIZE AuthApproveRegistrationResponse_size
#define PersonsCreateAccountResponse_size 11
#define PersonsGetNotificationsSettingsPayload_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
