/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_HUGIN_PB_H_INCLUDED
#define PB_PROTO_HUGIN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _GetLastDayPayload {
	char dummy_field;
} GetLastDayPayload;

typedef struct _GetLastDayResponse {
	pb_callback_t data;
} GetLastDayResponse;

typedef struct _GetLastMonthPayload {
	char dummy_field;
} GetLastMonthPayload;

typedef struct _GetLastMonthResponse {
	pb_callback_t data;
} GetLastMonthResponse;

typedef struct _GetLastYearPayload {
	char dummy_field;
} GetLastYearPayload;

typedef struct _GetLastYearResponse {
	pb_callback_t data;
} GetLastYearResponse;

typedef struct _HuginData {
	pb_callback_t datetime;
	int32_t event_count;
	int32_t uniq_count;
	pb_callback_t site_id;
	pb_callback_t country;
	pb_callback_t city;
	pb_callback_t browser;
	pb_callback_t os;
	pb_callback_t device;
	pb_callback_t screen;
	pb_callback_t language;
	pb_callback_t event_type;
	pb_callback_t hostname;
} HuginData;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GetLastDayPayload_init_default { 0 }
#define GetLastDayResponse_init_default \
	{                               \
		{                       \
			{ NULL }, NULL  \
		}                       \
	}
#define GetLastMonthPayload_init_default { 0 }
#define GetLastMonthResponse_init_default \
	{                                 \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define GetLastYearPayload_init_default { 0 }
#define GetLastYearResponse_init_default \
	{                                \
		{                        \
			{ NULL }, NULL   \
		}                        \
	}
#define HuginData_init_default                                                                          \
	{                                                                                               \
		{ { NULL }, NULL }, 0, 0, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL },   \
			{ { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
			{ { NULL }, NULL }, { { NULL }, NULL },                                         \
		{                                                                                       \
			{ NULL }, NULL                                                                  \
		}                                                                                       \
	}
#define GetLastDayPayload_init_zero { 0 }
#define GetLastDayResponse_init_zero   \
	{                              \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define GetLastMonthPayload_init_zero { 0 }
#define GetLastMonthResponse_init_zero \
	{                              \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define GetLastYearPayload_init_zero { 0 }
#define GetLastYearResponse_init_zero  \
	{                              \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define HuginData_init_zero                                                                             \
	{                                                                                               \
		{ { NULL }, NULL }, 0, 0, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL },   \
			{ { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, \
			{ { NULL }, NULL }, { { NULL }, NULL },                                         \
		{                                                                                       \
			{ NULL }, NULL                                                                  \
		}                                                                                       \
	}

/* Field tags (for use in manual encoding/decoding) */
#define GetLastDayResponse_data_tag 1
#define GetLastMonthResponse_data_tag 1
#define GetLastYearResponse_data_tag 1
#define HuginData_datetime_tag 1
#define HuginData_event_count_tag 2
#define HuginData_uniq_count_tag 3
#define HuginData_site_id_tag 4
#define HuginData_country_tag 5
#define HuginData_city_tag 6
#define HuginData_browser_tag 7
#define HuginData_os_tag 8
#define HuginData_device_tag 9
#define HuginData_screen_tag 10
#define HuginData_language_tag 11
#define HuginData_event_type_tag 12
#define HuginData_hostname_tag 13

/* Struct field encoding specification for nanopb */
#define GetLastDayPayload_FIELDLIST(X, a)

#define GetLastDayPayload_CALLBACK NULL
#define GetLastDayPayload_DEFAULT NULL

#define GetLastDayResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, data, 1)
#define GetLastDayResponse_CALLBACK pb_default_field_callback
#define GetLastDayResponse_DEFAULT NULL
#define GetLastDayResponse_data_MSGTYPE HuginData

#define GetLastMonthPayload_FIELDLIST(X, a)

#define GetLastMonthPayload_CALLBACK NULL
#define GetLastMonthPayload_DEFAULT NULL

#define GetLastMonthResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, data, 1)
#define GetLastMonthResponse_CALLBACK pb_default_field_callback
#define GetLastMonthResponse_DEFAULT NULL
#define GetLastMonthResponse_data_MSGTYPE HuginData

#define GetLastYearPayload_FIELDLIST(X, a)

#define GetLastYearPayload_CALLBACK NULL
#define GetLastYearPayload_DEFAULT NULL

#define GetLastYearResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, data, 1)
#define GetLastYearResponse_CALLBACK pb_default_field_callback
#define GetLastYearResponse_DEFAULT NULL
#define GetLastYearResponse_data_MSGTYPE HuginData

#define HuginData_FIELDLIST(X, a)                        \
	X(a, CALLBACK, SINGULAR, STRING, datetime, 1)    \
	X(a, STATIC, SINGULAR, INT32, event_count, 2)    \
	X(a, STATIC, SINGULAR, INT32, uniq_count, 3)     \
	X(a, CALLBACK, SINGULAR, STRING, site_id, 4)     \
	X(a, CALLBACK, SINGULAR, STRING, country, 5)     \
	X(a, CALLBACK, SINGULAR, STRING, city, 6)        \
	X(a, CALLBACK, SINGULAR, STRING, browser, 7)     \
	X(a, CALLBACK, SINGULAR, STRING, os, 8)          \
	X(a, CALLBACK, SINGULAR, STRING, device, 9)      \
	X(a, CALLBACK, SINGULAR, STRING, screen, 10)     \
	X(a, CALLBACK, SINGULAR, STRING, language, 11)   \
	X(a, CALLBACK, SINGULAR, STRING, event_type, 12) \
	X(a, CALLBACK, SINGULAR, STRING, hostname, 13)
#define HuginData_CALLBACK pb_default_field_callback
#define HuginData_DEFAULT NULL

extern const pb_msgdesc_t GetLastDayPayload_msg;
extern const pb_msgdesc_t GetLastDayResponse_msg;
extern const pb_msgdesc_t GetLastMonthPayload_msg;
extern const pb_msgdesc_t GetLastMonthResponse_msg;
extern const pb_msgdesc_t GetLastYearPayload_msg;
extern const pb_msgdesc_t GetLastYearResponse_msg;
extern const pb_msgdesc_t HuginData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GetLastDayPayload_fields &GetLastDayPayload_msg
#define GetLastDayResponse_fields &GetLastDayResponse_msg
#define GetLastMonthPayload_fields &GetLastMonthPayload_msg
#define GetLastMonthResponse_fields &GetLastMonthResponse_msg
#define GetLastYearPayload_fields &GetLastYearPayload_msg
#define GetLastYearResponse_fields &GetLastYearResponse_msg
#define HuginData_fields &HuginData_msg

/* Maximum encoded size of messages (where known) */
/* GetLastDayResponse_size depends on runtime parameters */
/* GetLastMonthResponse_size depends on runtime parameters */
/* GetLastYearResponse_size depends on runtime parameters */
/* HuginData_size depends on runtime parameters */
#define GetLastDayPayload_size 0
#define GetLastMonthPayload_size 0
#define GetLastYearPayload_size 0
#define PROTO_HUGIN_PB_H_MAX_SIZE GetLastDayPayload_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
