/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/hugin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GetLastDayPayload, GetLastDayPayload, AUTO)

PB_BIND(GetLastDayResponse, GetLastDayResponse, AUTO)

PB_BIND(GetLastMonthPayload, GetLastMonthPayload, AUTO)

PB_BIND(GetLastMonthResponse, GetLastMonthResponse, AUTO)

PB_BIND(GetLastYearPayload, GetLastYearPayload, AUTO)

PB_BIND(GetLastYearResponse, GetLastYearResponse, AUTO)

PB_BIND(HuginData, HuginData, AUTO)
