/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/mimir.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EventsGetRulesetsPayload, EventsGetRulesetsPayload, AUTO)

PB_BIND(EventsGetRulesetsResponse, EventsGetRulesetsResponse, AUTO)

PB_BIND(EventsGetEventsPayload, EventsGetEventsPayload, AUTO)

PB_BIND(EventsGetEventsResponse, EventsGetEventsResponse, AUTO)

PB_BIND(EventsGetEventsByIdPayload, EventsGetEventsByIdPayload, AUTO)

PB_BIND(EventsGetEventsByIdResponse, EventsGetEventsByIdResponse, AUTO)

PB_BIND(PlayersGetMyEventsPayload, PlayersGetMyEventsPayload, AUTO)

PB_BIND(PlayersGetMyEventsResponse, PlayersGetMyEventsResponse, AUTO)

PB_BIND(EventsGetRatingTablePayload, EventsGetRatingTablePayload, AUTO)

PB_BIND(EventsGetRatingTableResponse, EventsGetRatingTableResponse, AUTO)

PB_BIND(EventsGetLastGamesPayload, EventsGetLastGamesPayload, AUTO)

PB_BIND(EventsGetLastGamesResponse, EventsGetLastGamesResponse, AUTO)

PB_BIND(EventsGetGameResponse, EventsGetGameResponse, AUTO)

PB_BIND(EventsGetGamesSeriesResponse, EventsGetGamesSeriesResponse, AUTO)

PB_BIND(PlayersGetCurrentSessionsPayload, PlayersGetCurrentSessionsPayload, AUTO)

PB_BIND(CurrentSession, CurrentSession, 2)

PB_BIND(PlayersGetCurrentSessionsResponse, PlayersGetCurrentSessionsResponse, AUTO)

PB_BIND(EventsGetAllRegisteredPlayersPayload, EventsGetAllRegisteredPlayersPayload, AUTO)

PB_BIND(EventsGetAllRegisteredPlayersResponse, EventsGetAllRegisteredPlayersResponse, AUTO)

PB_BIND(EventsGetTimerStateResponse, EventsGetTimerStateResponse, AUTO)

PB_BIND(GamesGetSessionOverviewResponse, GamesGetSessionOverviewResponse, 2)

PB_BIND(PlayersGetPlayerStatsPayload, PlayersGetPlayerStatsPayload, AUTO)

PB_BIND(PlayersGetPlayerStatsResponse, PlayersGetPlayerStatsResponse, 2)

PB_BIND(GamesAddRoundPayload, GamesAddRoundPayload, AUTO)

PB_BIND(GamesAddRoundResponse, GamesAddRoundResponse, AUTO)

PB_BIND(GamesPreviewRoundPayload, GamesPreviewRoundPayload, AUTO)

PB_BIND(GamesPreviewRoundResponse, GamesPreviewRoundResponse, 2)

PB_BIND(GamesAddOnlineReplayPayload, GamesAddOnlineReplayPayload, AUTO)

PB_BIND(GamesAddOnlineReplayResponse, GamesAddOnlineReplayResponse, AUTO)

PB_BIND(PlayersGetLastResultsPayload, PlayersGetLastResultsPayload, AUTO)

PB_BIND(PlayersGetLastResultsResponse, PlayersGetLastResultsResponse, AUTO)

PB_BIND(PlayersGetLastRoundPayload, PlayersGetLastRoundPayload, AUTO)

PB_BIND(PlayersGetLastRoundResponse, PlayersGetLastRoundResponse, 2)

PB_BIND(PlayersGetAllRoundsResponse, PlayersGetAllRoundsResponse, AUTO)

PB_BIND(PlayersGetLastRoundByHashResponse, PlayersGetLastRoundByHashResponse, 2)

PB_BIND(EventsGetEventForEditPayload, EventsGetEventForEditPayload, AUTO)

PB_BIND(EventsGetEventForEditResponse, EventsGetEventForEditResponse, 2)

PB_BIND(EventsUpdateEventPayload, EventsUpdateEventPayload, 2)

PB_BIND(EventsGetTablesStatePayload, EventsGetTablesStatePayload, AUTO)

PB_BIND(EventsGetTablesStateResponse, EventsGetTablesStateResponse, AUTO)

PB_BIND(EventsRegisterPlayerPayload, EventsRegisterPlayerPayload, AUTO)

PB_BIND(EventsUnregisterPlayerPayload, EventsUnregisterPlayerPayload, AUTO)

PB_BIND(EventsUpdatePlayerSeatingFlagPayload, EventsUpdatePlayerSeatingFlagPayload, AUTO)

PB_BIND(EventsGetAchievementsPayload, EventsGetAchievementsPayload, AUTO)

PB_BIND(EventsGetAchievementsResponse, EventsGetAchievementsResponse, AUTO)

PB_BIND(EventsUpdatePlayersLocalIdsPayload, EventsUpdatePlayersLocalIdsPayload, AUTO)

PB_BIND(EventsUpdatePlayerReplacementPayload, EventsUpdatePlayerReplacementPayload, AUTO)

PB_BIND(EventsUpdatePlayersTeamsPayload, EventsUpdatePlayersTeamsPayload, AUTO)

PB_BIND(GamesStartGamePayload, GamesStartGamePayload, AUTO)

PB_BIND(GamesDropLastRoundPayload, GamesDropLastRoundPayload, AUTO)

PB_BIND(GamesAddPenaltyPayload, GamesAddPenaltyPayload, AUTO)

PB_BIND(GamesAddPenaltyGamePayload, GamesAddPenaltyGamePayload, AUTO)

PB_BIND(PlayersGetPlayerPayload, PlayersGetPlayerPayload, AUTO)

PB_BIND(PlayersGetPlayerResponse, PlayersGetPlayerResponse, AUTO)

PB_BIND(EventsGetCurrentSeatingResponse, EventsGetCurrentSeatingResponse, AUTO)

PB_BIND(SeatingMakeShuffledSeatingPayload, SeatingMakeShuffledSeatingPayload, AUTO)

PB_BIND(SeatingGenerateSwissSeatingPayload, SeatingGenerateSwissSeatingPayload, AUTO)

PB_BIND(SeatingGenerateSwissSeatingResponse, SeatingGenerateSwissSeatingResponse, AUTO)

PB_BIND(SeatingMakeIntervalSeatingPayload, SeatingMakeIntervalSeatingPayload, AUTO)

PB_BIND(SeatingMakePrescriptedSeatingPayload, SeatingMakePrescriptedSeatingPayload, AUTO)

PB_BIND(SeatingGetNextPrescriptedSeatingResponse, SeatingGetNextPrescriptedSeatingResponse, AUTO)

PB_BIND(EventsGetPrescriptedEventConfigResponse, EventsGetPrescriptedEventConfigResponse, AUTO)

PB_BIND(EventsUpdatePrescriptedEventConfigPayload, EventsUpdatePrescriptedEventConfigPayload, AUTO)

PB_BIND(EventsGetStartingTimerResponse, EventsGetStartingTimerResponse, AUTO)

PB_BIND(ClearStatCachePayload, ClearStatCachePayload, AUTO)

PB_BIND(TypedGamesAddOnlineReplayPayload, TypedGamesAddOnlineReplayPayload, AUTO)

PB_BIND(CallRefereePayload, CallRefereePayload, AUTO)

PB_BIND(PenaltiesResponse, PenaltiesResponse, AUTO)

PB_BIND(CancelPenaltyPayload, CancelPenaltyPayload, AUTO)

PB_BIND(AddExtraTimePayload, AddExtraTimePayload, AUTO)

PB_BIND(GetCurrentStatePayload, GetCurrentStatePayload, AUTO)

PB_BIND(GetCurrentStateResponse, GetCurrentStateResponse, 4)

PB_BIND(ChomboResponse, ChomboResponse, AUTO)
