/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_MIMIR_PB_H_INCLUDED
#define PB_PROTO_MIMIR_PB_H_INCLUDED
#include <pb.h>
#include "proto/nanopb.pb.h"
#include "proto/atoms.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _EventsGetRulesetsPayload {
	char dummy_field;
} EventsGetRulesetsPayload;

typedef struct _EventsGetRulesetsResponse {
	pb_callback_t rulesets;
	pb_callback_t ruleset_ids;
	pb_callback_t ruleset_titles;
} EventsGetRulesetsResponse;

typedef struct _EventsGetEventsPayload {
	int32_t limit;
	int32_t offset;
	bool filter_unlisted;
	pb_callback_t filter;
} EventsGetEventsPayload;

typedef struct _EventsGetEventsResponse {
	int32_t total;
	pb_callback_t events;
} EventsGetEventsResponse;

typedef struct _EventsGetEventsByIdPayload {
	pb_callback_t ids;
} EventsGetEventsByIdPayload;

typedef struct _EventsGetEventsByIdResponse {
	pb_callback_t events;
} EventsGetEventsByIdResponse;

typedef struct _PlayersGetMyEventsPayload {
	char dummy_field;
} PlayersGetMyEventsPayload;

typedef struct _PlayersGetMyEventsResponse {
	pb_callback_t events;
} PlayersGetMyEventsResponse;

typedef struct _EventsGetRatingTablePayload {
	pb_callback_t event_id_list;
	pb_callback_t order_by;
	pb_callback_t order;
	bool has_only_min_games;
	bool only_min_games;
} EventsGetRatingTablePayload;

typedef struct _EventsGetRatingTableResponse {
	pb_callback_t list;
} EventsGetRatingTableResponse;

typedef struct _EventsGetLastGamesPayload {
	pb_callback_t event_id_list;
	int32_t limit;
	int32_t offset;
	pb_callback_t order_by;
	pb_callback_t order;
} EventsGetLastGamesPayload;

typedef struct _EventsGetLastGamesResponse {
	pb_callback_t games;
	pb_callback_t players;
	int32_t total_games;
} EventsGetLastGamesResponse;

typedef struct _EventsGetGameResponse {
	bool has_game;
	GameResult game;
	pb_callback_t players;
} EventsGetGameResponse;

typedef struct _EventsGetGamesSeriesResponse {
	pb_callback_t results;
} EventsGetGamesSeriesResponse;

typedef struct _PlayersGetCurrentSessionsPayload {
	int32_t player_id;
	int32_t event_id;
} PlayersGetCurrentSessionsPayload;

typedef struct _PlayersGetCurrentSessionsResponse {
	pb_callback_t sessions;
} PlayersGetCurrentSessionsResponse;

typedef struct _EventsGetAllRegisteredPlayersPayload {
	pb_callback_t event_ids;
} EventsGetAllRegisteredPlayersPayload;

typedef struct _EventsGetAllRegisteredPlayersResponse {
	pb_callback_t players;
} EventsGetAllRegisteredPlayersResponse;

typedef struct _EventsGetTimerStateResponse {
	bool started;
	bool finished;
	int32_t time_remaining;
	bool waiting_for_timer;
	bool have_autostart;
	bool autostart_timer;
	int32_t hide_seating_after;
} EventsGetTimerStateResponse;

typedef struct _CurrentSession {
	char session_hash[129];
	char status[129];
	bool has_table_index;
	int32_t table_index;
	pb_size_t players_count;
	PlayerInSession players[4];
	bool has_timer_state;
	EventsGetTimerStateResponse timer_state;
} CurrentSession;

typedef struct _GamesGetSessionOverviewResponse {
	int32_t id;
	int32_t event_id;
	bool has_table_index;
	int32_t table_index;
	pb_size_t players_count;
	PlayerInSession players[4];
	bool has_state;
	SessionState state;
	bool has_timer_state;
	EventsGetTimerStateResponse timer_state;
} GamesGetSessionOverviewResponse;

typedef struct _PlayersGetPlayerStatsPayload {
	int32_t player_id;
	pb_callback_t event_id_list;
} PlayersGetPlayerStatsPayload;

typedef struct _PlayersGetPlayerStatsResponse {
	pb_callback_t rating_history;
	pb_callback_t score_history;
	pb_callback_t players_info;
	pb_callback_t places_summary;
	int32_t total_played_games;
	int32_t total_played_rounds;
	bool has_win_summary;
	PlayerWinSummary win_summary;
	pb_callback_t hands_value_summary;
	pb_callback_t yaku_summary;
	bool has_riichi_summary;
	RiichiSummary riichi_summary;
	bool has_dora_stat;
	DoraSummary dora_stat;
	pb_callback_t last_update;
} PlayersGetPlayerStatsResponse;

typedef struct _GamesAddRoundPayload {
	pb_callback_t session_hash;
	bool has_round_data;
	Round round_data;
} GamesAddRoundPayload;

typedef struct _GamesAddRoundResponse {
	pb_callback_t scores;
	/* current round number */
	int32_t round;
	int32_t honba;
	/* on the table from previous round */
	int32_t riichi_bets;
	/* if game has been finished prematurely (e.g. by timeout) */
	bool prematurely_finished;
	/* True if round has just changed useful to determine if current
 4e or 4s is first one, no matter what honba count is. (Possible
 situation: draw in 3s or 3e, so first 4e or 4s has honba). */
	bool round_just_changed;
	bool is_finished;
	/* True if ending policy is "oneMoreHand" AND this hand was started. */
	bool last_hand_started;
	/* Outcome of previously recorded round. Useful to determine if
 certain rules should be applied in current case, e.g., agariyame
 should not be applied on chombo or abortive draw. */
	bool has_last_outcome;
	RoundOutcome last_outcome;
} GamesAddRoundResponse;

typedef struct _GamesPreviewRoundPayload {
	pb_callback_t session_hash;
	bool has_round_data;
	Round round_data;
} GamesPreviewRoundPayload;

typedef struct _GamesPreviewRoundResponse {
	bool has_state;
	RoundState state;
} GamesPreviewRoundResponse;

typedef struct _GamesAddOnlineReplayPayload {
	int32_t event_id;
	pb_callback_t link;
} GamesAddOnlineReplayPayload;

typedef struct _GamesAddOnlineReplayResponse {
	bool has_game;
	GameResult game;
	pb_callback_t players;
} GamesAddOnlineReplayResponse;

typedef struct _PlayersGetLastResultsPayload {
	int32_t player_id;
	int32_t event_id;
} PlayersGetLastResultsPayload;

typedef struct _PlayersGetLastResultsResponse {
	pb_callback_t results;
} PlayersGetLastResultsResponse;

typedef struct _PlayersGetLastRoundPayload {
	int32_t player_id;
	int32_t event_id;
} PlayersGetLastRoundPayload;

typedef struct _PlayersGetLastRoundResponse {
	bool has_round;
	RoundState round;
} PlayersGetLastRoundResponse;

typedef struct _PlayersGetAllRoundsResponse {
	pb_callback_t rounds;
} PlayersGetAllRoundsResponse;

typedef struct _PlayersGetLastRoundByHashResponse {
	bool has_round;
	RoundState round;
} PlayersGetLastRoundByHashResponse;

typedef struct _EventsGetEventForEditPayload {
	int32_t id;
} EventsGetEventForEditPayload;

typedef struct _EventsGetEventForEditResponse {
	int32_t id;
	bool has_event;
	EventData event;
	bool finished;
} EventsGetEventForEditResponse;

typedef struct _EventsUpdateEventPayload {
	int32_t id;
	bool has_event;
	EventData event;
} EventsUpdateEventPayload;

typedef struct _EventsGetTablesStatePayload {
	int32_t event_id;
	bool omit_last_round;
} EventsGetTablesStatePayload;

typedef struct _EventsGetTablesStateResponse {
	pb_callback_t tables;
} EventsGetTablesStateResponse;

typedef struct _EventsRegisterPlayerPayload {
	int32_t player_id;
	int32_t event_id;
} EventsRegisterPlayerPayload;

typedef struct _EventsUnregisterPlayerPayload {
	int32_t player_id;
	int32_t event_id;
} EventsUnregisterPlayerPayload;

typedef struct _EventsUpdatePlayerSeatingFlagPayload {
	int32_t player_id;
	int32_t event_id;
	bool ignore_seating;
} EventsUpdatePlayerSeatingFlagPayload;

typedef struct _EventsGetAchievementsPayload {
	pb_callback_t achievements_list;
	int32_t event_id;
} EventsGetAchievementsPayload;

typedef struct _EventsGetAchievementsResponse {
	pb_callback_t achievements;
	pb_callback_t last_update;
} EventsGetAchievementsResponse;

typedef struct _EventsUpdatePlayersLocalIdsPayload {
	int32_t event_id;
	pb_callback_t ids_to_local_ids;
} EventsUpdatePlayersLocalIdsPayload;

typedef struct _EventsUpdatePlayerReplacementPayload {
	int32_t player_id;
	int32_t event_id;
	int32_t replacement_id;
} EventsUpdatePlayerReplacementPayload;

typedef struct _EventsUpdatePlayersTeamsPayload {
	int32_t event_id;
	pb_callback_t ids_to_team_names;
} EventsUpdatePlayersTeamsPayload;

typedef struct _GamesStartGamePayload {
	int32_t event_id;
	pb_callback_t players; /* ids list, e-s-w-n */
} GamesStartGamePayload;

typedef struct _GamesDropLastRoundPayload {
	pb_callback_t session_hash;
	pb_callback_t intermediate_results;
} GamesDropLastRoundPayload;

typedef struct _GamesAddPenaltyPayload {
	int32_t event_id;
	int32_t player_id;
	int32_t amount;
	pb_callback_t reason;
} GamesAddPenaltyPayload;

typedef struct _GamesAddPenaltyGamePayload {
	int32_t event_id;
	pb_callback_t players; /* ids, e-s-w-n */
} GamesAddPenaltyGamePayload;

typedef struct _PlayersGetPlayerPayload {
	int32_t id;
} PlayersGetPlayerPayload;

typedef struct _PlayersGetPlayerResponse {
	bool has_players;
	Player players;
} PlayersGetPlayerResponse;

typedef struct _EventsGetCurrentSeatingResponse {
	pb_callback_t seating;
} EventsGetCurrentSeatingResponse;

typedef struct _SeatingMakeShuffledSeatingPayload {
	int32_t event_id;
	int32_t groups_count;
	int32_t seed; /* randomness factor */
} SeatingMakeShuffledSeatingPayload;

typedef struct _SeatingGenerateSwissSeatingPayload {
	int32_t event_id;
	bool substitute_replacement_players;
} SeatingGenerateSwissSeatingPayload;

typedef struct _SeatingGenerateSwissSeatingResponse {
	pb_callback_t tables;
} SeatingGenerateSwissSeatingResponse;

typedef struct _SeatingMakeIntervalSeatingPayload {
	int32_t event_id;
	int32_t step;
} SeatingMakeIntervalSeatingPayload;

typedef struct _SeatingMakePrescriptedSeatingPayload {
	int32_t event_id;
	bool randomize_at_tables;
} SeatingMakePrescriptedSeatingPayload;

typedef struct _SeatingGetNextPrescriptedSeatingResponse {
	pb_callback_t tables;
} SeatingGetNextPrescriptedSeatingResponse;

typedef struct _EventsGetPrescriptedEventConfigResponse {
	int32_t event_id;
	int32_t next_session_index;
	pb_callback_t prescript;
	pb_callback_t errors;
} EventsGetPrescriptedEventConfigResponse;

typedef struct _EventsUpdatePrescriptedEventConfigPayload {
	int32_t event_id;
	int32_t next_session_index;
	pb_callback_t prescript;
} EventsUpdatePrescriptedEventConfigPayload;

typedef struct _EventsGetStartingTimerResponse {
	int32_t timer; /* seconds to start */
} EventsGetStartingTimerResponse;

typedef struct _ClearStatCachePayload {
	int32_t player_id;
} ClearStatCachePayload;

typedef struct _TypedGamesAddOnlineReplayPayload {
	int32_t event_id;
	int32_t platform_id;
	int32_t content_type;
	int32_t log_timestamp;
	pb_callback_t replay_hash;
	pb_callback_t content;
} TypedGamesAddOnlineReplayPayload;

typedef struct _CallRefereePayload {
	int32_t table_index;
	int32_t event_id;
} CallRefereePayload;

typedef struct _PenaltiesResponse {
	pb_callback_t penalties;
	pb_callback_t referees;
} PenaltiesResponse;

typedef struct _CancelPenaltyPayload {
	int32_t penalty_id;
	pb_callback_t reason;
} CancelPenaltyPayload;

typedef struct _AddExtraTimePayload {
	pb_callback_t session_hash_list;
	int32_t extra_time;
} AddExtraTimePayload;

typedef struct _GetCurrentStatePayload {
	int32_t event_id;
	int32_t player_id;
} GetCurrentStatePayload;

typedef struct _GetCurrentStateResponse {
	pb_size_t sessions_count;
	CurrentSession sessions[4];
	bool has_config;
	GameConfig config;
} GetCurrentStateResponse;

typedef struct _ChomboResponse {
	pb_callback_t chombos;
	pb_callback_t players;
} ChomboResponse;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define EventsGetRulesetsPayload_init_default { 0 }
#define EventsGetRulesetsResponse_init_default          \
	{                                               \
		{ { NULL }, NULL }, { { NULL }, NULL }, \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define EventsGetEventsPayload_init_default \
	{                                   \
		0, 0, 0,                    \
		{                           \
			{ NULL }, NULL      \
		}                           \
	}
#define EventsGetEventsResponse_init_default \
	{                                    \
		0,                           \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define EventsGetEventsByIdPayload_init_default \
	{                                       \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define EventsGetEventsByIdResponse_init_default \
	{                                        \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define PlayersGetMyEventsPayload_init_default { 0 }
#define PlayersGetMyEventsResponse_init_default \
	{                                       \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define EventsGetRatingTablePayload_init_default \
	{ { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, false, 0 }
#define EventsGetRatingTableResponse_init_default \
	{                                         \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define EventsGetLastGamesPayload_init_default                \
	{                                                     \
		{ { NULL }, NULL }, 0, 0, { { NULL }, NULL }, \
		{                                             \
			{ NULL }, NULL                        \
		}                                             \
	}
#define EventsGetLastGamesResponse_init_default { { { NULL }, NULL }, { { NULL }, NULL }, 0 }
#define EventsGetGameResponse_init_default      \
	{                                       \
		false, GameResult_init_default, \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define EventsGetGamesSeriesResponse_init_default \
	{                                         \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define PlayersGetCurrentSessionsPayload_init_default { 0, 0 }
#define CurrentSession_init_default                                                                   \
	{ "",                                                                                         \
	  "",                                                                                         \
	  false,                                                                                      \
	  0,                                                                                          \
	  0,                                                                                          \
	  { PlayerInSession_init_default, PlayerInSession_init_default, PlayerInSession_init_default, \
	    PlayerInSession_init_default },                                                           \
	  false,                                                                                      \
	  EventsGetTimerStateResponse_init_default }
#define PlayersGetCurrentSessionsResponse_init_default \
	{                                              \
		{                                      \
			{ NULL }, NULL                 \
		}                                      \
	}
#define EventsGetAllRegisteredPlayersPayload_init_default \
	{                                                 \
		{                                         \
			{ NULL }, NULL                    \
		}                                         \
	}
#define EventsGetAllRegisteredPlayersResponse_init_default \
	{                                                  \
		{                                          \
			{ NULL }, NULL                     \
		}                                          \
	}
#define EventsGetTimerStateResponse_init_default { 0, 0, 0, 0, 0, 0, 0 }
#define GamesGetSessionOverviewResponse_init_default                                                  \
	{ 0,                                                                                          \
	  0,                                                                                          \
	  false,                                                                                      \
	  0,                                                                                          \
	  0,                                                                                          \
	  { PlayerInSession_init_default, PlayerInSession_init_default, PlayerInSession_init_default, \
	    PlayerInSession_init_default },                                                           \
	  false,                                                                                      \
	  SessionState_init_default,                                                                  \
	  false,                                                                                      \
	  EventsGetTimerStateResponse_init_default }
#define PlayersGetPlayerStatsPayload_init_default \
	{                                         \
		0,                                \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define PlayersGetPlayerStatsResponse_init_default                                                           \
	{                                                                                                    \
		{ { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, false, \
			PlayerWinSummary_init_default, { { NULL }, NULL }, { { NULL }, NULL }, false,        \
			RiichiSummary_init_default, false, DoraSummary_init_default,                         \
		{                                                                                            \
			{ NULL }, NULL                                                                       \
		}                                                                                            \
	}
#define GamesAddRoundPayload_init_default { { { NULL }, NULL }, false, Round_init_default }
#define GamesAddRoundResponse_init_default { { { NULL }, NULL }, 0, 0, 0, 0, 0, 0, 0, false, _RoundOutcome_MIN }
#define GamesPreviewRoundPayload_init_default { { { NULL }, NULL }, false, Round_init_default }
#define GamesPreviewRoundResponse_init_default { false, RoundState_init_default }
#define GamesAddOnlineReplayPayload_init_default \
	{                                        \
		0,                               \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define GamesAddOnlineReplayResponse_init_default \
	{                                         \
		false, GameResult_init_default,   \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define PlayersGetLastResultsPayload_init_default { 0, 0 }
#define PlayersGetLastResultsResponse_init_default \
	{                                          \
		{                                  \
			{ NULL }, NULL             \
		}                                  \
	}
#define PlayersGetLastRoundPayload_init_default { 0, 0 }
#define PlayersGetLastRoundResponse_init_default { false, RoundState_init_default }
#define PlayersGetAllRoundsResponse_init_default \
	{                                        \
		{                                \
			{ NULL }, NULL           \
		}                                \
	}
#define PlayersGetLastRoundByHashResponse_init_default { false, RoundState_init_default }
#define EventsGetEventForEditPayload_init_default { 0 }
#define EventsGetEventForEditResponse_init_default { 0, false, EventData_init_default, 0 }
#define EventsUpdateEventPayload_init_default { 0, false, EventData_init_default }
#define EventsGetTablesStatePayload_init_default { 0, 0 }
#define EventsGetTablesStateResponse_init_default \
	{                                         \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define EventsRegisterPlayerPayload_init_default { 0, 0 }
#define EventsUnregisterPlayerPayload_init_default { 0, 0 }
#define EventsUpdatePlayerSeatingFlagPayload_init_default { 0, 0, 0 }
#define EventsGetAchievementsPayload_init_default { { { NULL }, NULL }, 0 }
#define EventsGetAchievementsResponse_init_default \
	{                                          \
		{ { NULL }, NULL },                \
		{                                  \
			{ NULL }, NULL             \
		}                                  \
	}
#define EventsUpdatePlayersLocalIdsPayload_init_default \
	{                                               \
		0,                                      \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define EventsUpdatePlayerReplacementPayload_init_default { 0, 0, 0 }
#define EventsUpdatePlayersTeamsPayload_init_default \
	{                                            \
		0,                                   \
		{                                    \
			{ NULL }, NULL               \
		}                                    \
	}
#define GamesStartGamePayload_init_default \
	{                                  \
		0,                         \
		{                          \
			{ NULL }, NULL     \
		}                          \
	}
#define GamesDropLastRoundPayload_init_default \
	{                                      \
		{ { NULL }, NULL },            \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define GamesAddPenaltyPayload_init_default \
	{                                   \
		0, 0, 0,                    \
		{                           \
			{ NULL }, NULL      \
		}                           \
	}
#define GamesAddPenaltyGamePayload_init_default \
	{                                       \
		0,                              \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define PlayersGetPlayerPayload_init_default { 0 }
#define PlayersGetPlayerResponse_init_default { false, Player_init_default }
#define EventsGetCurrentSeatingResponse_init_default \
	{                                            \
		{                                    \
			{ NULL }, NULL               \
		}                                    \
	}
#define SeatingMakeShuffledSeatingPayload_init_default { 0, 0, 0 }
#define SeatingGenerateSwissSeatingPayload_init_default { 0, 0 }
#define SeatingGenerateSwissSeatingResponse_init_default \
	{                                                \
		{                                        \
			{ NULL }, NULL                   \
		}                                        \
	}
#define SeatingMakeIntervalSeatingPayload_init_default { 0, 0 }
#define SeatingMakePrescriptedSeatingPayload_init_default { 0, 0 }
#define SeatingGetNextPrescriptedSeatingResponse_init_default \
	{                                                     \
		{                                             \
			{ NULL }, NULL                        \
		}                                             \
	}
#define EventsGetPrescriptedEventConfigResponse_init_default \
	{                                                    \
		0, 0, { { NULL }, NULL },                    \
		{                                            \
			{ NULL }, NULL                       \
		}                                            \
	}
#define EventsUpdatePrescriptedEventConfigPayload_init_default \
	{                                                      \
		0, 0,                                          \
		{                                              \
			{ NULL }, NULL                         \
		}                                              \
	}
#define EventsGetStartingTimerResponse_init_default { 0 }
#define ClearStatCachePayload_init_default { 0 }
#define TypedGamesAddOnlineReplayPayload_init_default \
	{                                             \
		0, 0, 0, 0, { { NULL }, NULL },       \
		{                                     \
			{ NULL }, NULL                \
		}                                     \
	}
#define CallRefereePayload_init_default { 0, 0 }
#define PenaltiesResponse_init_default \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define CancelPenaltyPayload_init_default \
	{                                 \
		0,                        \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define AddExtraTimePayload_init_default { { { NULL }, NULL }, 0 }
#define GetCurrentStatePayload_init_default { 0, 0 }
#define GetCurrentStateResponse_init_default                                                       \
	{ 0,                                                                                       \
	  { CurrentSession_init_default, CurrentSession_init_default, CurrentSession_init_default, \
	    CurrentSession_init_default },                                                         \
	  false,                                                                                   \
	  GameConfig_init_default }
#define ChomboResponse_init_default    \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define EventsGetRulesetsPayload_init_zero { 0 }
#define EventsGetRulesetsResponse_init_zero             \
	{                                               \
		{ { NULL }, NULL }, { { NULL }, NULL }, \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define EventsGetEventsPayload_init_zero \
	{                                \
		0, 0, 0,                 \
		{                        \
			{ NULL }, NULL   \
		}                        \
	}
#define EventsGetEventsResponse_init_zero \
	{                                 \
		0,                        \
		{                         \
			{ NULL }, NULL    \
		}                         \
	}
#define EventsGetEventsByIdPayload_init_zero \
	{                                    \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define EventsGetEventsByIdResponse_init_zero \
	{                                     \
		{                             \
			{ NULL }, NULL        \
		}                             \
	}
#define PlayersGetMyEventsPayload_init_zero { 0 }
#define PlayersGetMyEventsResponse_init_zero \
	{                                    \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define EventsGetRatingTablePayload_init_zero { { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, false, 0 }
#define EventsGetRatingTableResponse_init_zero \
	{                                      \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define EventsGetLastGamesPayload_init_zero                   \
	{                                                     \
		{ { NULL }, NULL }, 0, 0, { { NULL }, NULL }, \
		{                                             \
			{ NULL }, NULL                        \
		}                                             \
	}
#define EventsGetLastGamesResponse_init_zero { { { NULL }, NULL }, { { NULL }, NULL }, 0 }
#define EventsGetGameResponse_init_zero      \
	{                                    \
		false, GameResult_init_zero, \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define EventsGetGamesSeriesResponse_init_zero \
	{                                      \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define PlayersGetCurrentSessionsPayload_init_zero { 0, 0 }
#define CurrentSession_init_zero                                                                                          \
	{ "",                                                                                                             \
	  "",                                                                                                             \
	  false,                                                                                                          \
	  0,                                                                                                              \
	  0,                                                                                                              \
	  { PlayerInSession_init_zero, PlayerInSession_init_zero, PlayerInSession_init_zero, PlayerInSession_init_zero }, \
	  false,                                                                                                          \
	  EventsGetTimerStateResponse_init_zero }
#define PlayersGetCurrentSessionsResponse_init_zero \
	{                                           \
		{                                   \
			{ NULL }, NULL              \
		}                                   \
	}
#define EventsGetAllRegisteredPlayersPayload_init_zero \
	{                                              \
		{                                      \
			{ NULL }, NULL                 \
		}                                      \
	}
#define EventsGetAllRegisteredPlayersResponse_init_zero \
	{                                               \
		{                                       \
			{ NULL }, NULL                  \
		}                                       \
	}
#define EventsGetTimerStateResponse_init_zero { 0, 0, 0, 0, 0, 0, 0 }
#define GamesGetSessionOverviewResponse_init_zero                                                                         \
	{ 0,                                                                                                              \
	  0,                                                                                                              \
	  false,                                                                                                          \
	  0,                                                                                                              \
	  0,                                                                                                              \
	  { PlayerInSession_init_zero, PlayerInSession_init_zero, PlayerInSession_init_zero, PlayerInSession_init_zero }, \
	  false,                                                                                                          \
	  SessionState_init_zero,                                                                                         \
	  false,                                                                                                          \
	  EventsGetTimerStateResponse_init_zero }
#define PlayersGetPlayerStatsPayload_init_zero \
	{                                      \
		0,                             \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define PlayersGetPlayerStatsResponse_init_zero                                                              \
	{                                                                                                    \
		{ { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, { { NULL }, NULL }, 0, 0, false, \
			PlayerWinSummary_init_zero, { { NULL }, NULL }, { { NULL }, NULL }, false,           \
			RiichiSummary_init_zero, false, DoraSummary_init_zero,                               \
		{                                                                                            \
			{ NULL }, NULL                                                                       \
		}                                                                                            \
	}
#define GamesAddRoundPayload_init_zero { { { NULL }, NULL }, false, Round_init_zero }
#define GamesAddRoundResponse_init_zero { { { NULL }, NULL }, 0, 0, 0, 0, 0, 0, 0, false, _RoundOutcome_MIN }
#define GamesPreviewRoundPayload_init_zero { { { NULL }, NULL }, false, Round_init_zero }
#define GamesPreviewRoundResponse_init_zero { false, RoundState_init_zero }
#define GamesAddOnlineReplayPayload_init_zero \
	{                                     \
		0,                            \
		{                             \
			{ NULL }, NULL        \
		}                             \
	}
#define GamesAddOnlineReplayResponse_init_zero \
	{                                      \
		false, GameResult_init_zero,   \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define PlayersGetLastResultsPayload_init_zero { 0, 0 }
#define PlayersGetLastResultsResponse_init_zero \
	{                                       \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define PlayersGetLastRoundPayload_init_zero { 0, 0 }
#define PlayersGetLastRoundResponse_init_zero { false, RoundState_init_zero }
#define PlayersGetAllRoundsResponse_init_zero \
	{                                     \
		{                             \
			{ NULL }, NULL        \
		}                             \
	}
#define PlayersGetLastRoundByHashResponse_init_zero { false, RoundState_init_zero }
#define EventsGetEventForEditPayload_init_zero { 0 }
#define EventsGetEventForEditResponse_init_zero { 0, false, EventData_init_zero, 0 }
#define EventsUpdateEventPayload_init_zero { 0, false, EventData_init_zero }
#define EventsGetTablesStatePayload_init_zero { 0, 0 }
#define EventsGetTablesStateResponse_init_zero \
	{                                      \
		{                              \
			{ NULL }, NULL         \
		}                              \
	}
#define EventsRegisterPlayerPayload_init_zero { 0, 0 }
#define EventsUnregisterPlayerPayload_init_zero { 0, 0 }
#define EventsUpdatePlayerSeatingFlagPayload_init_zero { 0, 0, 0 }
#define EventsGetAchievementsPayload_init_zero { { { NULL }, NULL }, 0 }
#define EventsGetAchievementsResponse_init_zero \
	{                                       \
		{ { NULL }, NULL },             \
		{                               \
			{ NULL }, NULL          \
		}                               \
	}
#define EventsUpdatePlayersLocalIdsPayload_init_zero \
	{                                            \
		0,                                   \
		{                                    \
			{ NULL }, NULL               \
		}                                    \
	}
#define EventsUpdatePlayerReplacementPayload_init_zero { 0, 0, 0 }
#define EventsUpdatePlayersTeamsPayload_init_zero \
	{                                         \
		0,                                \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define GamesStartGamePayload_init_zero \
	{                               \
		0,                      \
		{                       \
			{ NULL }, NULL  \
		}                       \
	}
#define GamesDropLastRoundPayload_init_zero \
	{                                   \
		{ { NULL }, NULL },         \
		{                           \
			{ NULL }, NULL      \
		}                           \
	}
#define GamesAddPenaltyPayload_init_zero \
	{                                \
		0, 0, 0,                 \
		{                        \
			{ NULL }, NULL   \
		}                        \
	}
#define GamesAddPenaltyGamePayload_init_zero \
	{                                    \
		0,                           \
		{                            \
			{ NULL }, NULL       \
		}                            \
	}
#define PlayersGetPlayerPayload_init_zero { 0 }
#define PlayersGetPlayerResponse_init_zero { false, Player_init_zero }
#define EventsGetCurrentSeatingResponse_init_zero \
	{                                         \
		{                                 \
			{ NULL }, NULL            \
		}                                 \
	}
#define SeatingMakeShuffledSeatingPayload_init_zero { 0, 0, 0 }
#define SeatingGenerateSwissSeatingPayload_init_zero { 0, 0 }
#define SeatingGenerateSwissSeatingResponse_init_zero \
	{                                             \
		{                                     \
			{ NULL }, NULL                \
		}                                     \
	}
#define SeatingMakeIntervalSeatingPayload_init_zero { 0, 0 }
#define SeatingMakePrescriptedSeatingPayload_init_zero { 0, 0 }
#define SeatingGetNextPrescriptedSeatingResponse_init_zero \
	{                                                  \
		{                                          \
			{ NULL }, NULL                     \
		}                                          \
	}
#define EventsGetPrescriptedEventConfigResponse_init_zero \
	{                                                 \
		0, 0, { { NULL }, NULL },                 \
		{                                         \
			{ NULL }, NULL                    \
		}                                         \
	}
#define EventsUpdatePrescriptedEventConfigPayload_init_zero \
	{                                                   \
		0, 0,                                       \
		{                                           \
			{ NULL }, NULL                      \
		}                                           \
	}
#define EventsGetStartingTimerResponse_init_zero { 0 }
#define ClearStatCachePayload_init_zero { 0 }
#define TypedGamesAddOnlineReplayPayload_init_zero \
	{                                          \
		0, 0, 0, 0, { { NULL }, NULL },    \
		{                                  \
			{ NULL }, NULL             \
		}                                  \
	}
#define CallRefereePayload_init_zero { 0, 0 }
#define PenaltiesResponse_init_zero    \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define CancelPenaltyPayload_init_zero \
	{                              \
		0,                     \
		{                      \
			{ NULL }, NULL \
		}                      \
	}
#define AddExtraTimePayload_init_zero { { { NULL }, NULL }, 0 }
#define GetCurrentStatePayload_init_zero { 0, 0 }
#define GetCurrentStateResponse_init_zero                                                                             \
	{ 0,                                                                                                          \
	  { CurrentSession_init_zero, CurrentSession_init_zero, CurrentSession_init_zero, CurrentSession_init_zero }, \
	  false,                                                                                                      \
	  GameConfig_init_zero }
#define ChomboResponse_init_zero       \
	{                              \
		{ { NULL }, NULL },    \
		{                      \
			{ NULL }, NULL \
		}                      \
	}

/* Field tags (for use in manual encoding/decoding) */
#define EventsGetRulesetsResponse_rulesets_tag 1
#define EventsGetRulesetsResponse_ruleset_ids_tag 2
#define EventsGetRulesetsResponse_ruleset_titles_tag 3
#define EventsGetEventsPayload_limit_tag 1
#define EventsGetEventsPayload_offset_tag 2
#define EventsGetEventsPayload_filter_unlisted_tag 3
#define EventsGetEventsPayload_filter_tag 4
#define EventsGetEventsResponse_total_tag 1
#define EventsGetEventsResponse_events_tag 2
#define EventsGetEventsByIdPayload_ids_tag 1
#define EventsGetEventsByIdResponse_events_tag 1
#define PlayersGetMyEventsResponse_events_tag 1
#define EventsGetRatingTablePayload_event_id_list_tag 1
#define EventsGetRatingTablePayload_order_by_tag 2
#define EventsGetRatingTablePayload_order_tag 3
#define EventsGetRatingTablePayload_only_min_games_tag 5
#define EventsGetRatingTableResponse_list_tag 1
#define EventsGetLastGamesPayload_event_id_list_tag 1
#define EventsGetLastGamesPayload_limit_tag 2
#define EventsGetLastGamesPayload_offset_tag 3
#define EventsGetLastGamesPayload_order_by_tag 4
#define EventsGetLastGamesPayload_order_tag 5
#define EventsGetLastGamesResponse_games_tag 1
#define EventsGetLastGamesResponse_players_tag 2
#define EventsGetLastGamesResponse_total_games_tag 3
#define EventsGetGameResponse_game_tag 1
#define EventsGetGameResponse_players_tag 2
#define EventsGetGamesSeriesResponse_results_tag 1
#define PlayersGetCurrentSessionsPayload_player_id_tag 1
#define PlayersGetCurrentSessionsPayload_event_id_tag 2
#define PlayersGetCurrentSessionsResponse_sessions_tag 1
#define EventsGetAllRegisteredPlayersPayload_event_ids_tag 1
#define EventsGetAllRegisteredPlayersResponse_players_tag 1
#define EventsGetTimerStateResponse_started_tag 1
#define EventsGetTimerStateResponse_finished_tag 2
#define EventsGetTimerStateResponse_time_remaining_tag 3
#define EventsGetTimerStateResponse_waiting_for_timer_tag 4
#define EventsGetTimerStateResponse_have_autostart_tag 5
#define EventsGetTimerStateResponse_autostart_timer_tag 6
#define EventsGetTimerStateResponse_hide_seating_after_tag 8
#define CurrentSession_session_hash_tag 1
#define CurrentSession_status_tag 2
#define CurrentSession_table_index_tag 3
#define CurrentSession_players_tag 4
#define CurrentSession_timer_state_tag 5
#define GamesGetSessionOverviewResponse_id_tag 1
#define GamesGetSessionOverviewResponse_event_id_tag 2
#define GamesGetSessionOverviewResponse_table_index_tag 3
#define GamesGetSessionOverviewResponse_players_tag 4
#define GamesGetSessionOverviewResponse_state_tag 5
#define GamesGetSessionOverviewResponse_timer_state_tag 6
#define PlayersGetPlayerStatsPayload_player_id_tag 1
#define PlayersGetPlayerStatsPayload_event_id_list_tag 2
#define PlayersGetPlayerStatsResponse_rating_history_tag 1
#define PlayersGetPlayerStatsResponse_score_history_tag 2
#define PlayersGetPlayerStatsResponse_players_info_tag 3
#define PlayersGetPlayerStatsResponse_places_summary_tag 4
#define PlayersGetPlayerStatsResponse_total_played_games_tag 5
#define PlayersGetPlayerStatsResponse_total_played_rounds_tag 6
#define PlayersGetPlayerStatsResponse_win_summary_tag 7
#define PlayersGetPlayerStatsResponse_hands_value_summary_tag 8
#define PlayersGetPlayerStatsResponse_yaku_summary_tag 9
#define PlayersGetPlayerStatsResponse_riichi_summary_tag 10
#define PlayersGetPlayerStatsResponse_dora_stat_tag 11
#define PlayersGetPlayerStatsResponse_last_update_tag 12
#define GamesAddRoundPayload_session_hash_tag 1
#define GamesAddRoundPayload_round_data_tag 2
#define GamesAddRoundResponse_scores_tag 1
#define GamesAddRoundResponse_round_tag 3
#define GamesAddRoundResponse_honba_tag 4
#define GamesAddRoundResponse_riichi_bets_tag 5
#define GamesAddRoundResponse_prematurely_finished_tag 6
#define GamesAddRoundResponse_round_just_changed_tag 7
#define GamesAddRoundResponse_is_finished_tag 8
#define GamesAddRoundResponse_last_hand_started_tag 9
#define GamesAddRoundResponse_last_outcome_tag 10
#define GamesPreviewRoundPayload_session_hash_tag 1
#define GamesPreviewRoundPayload_round_data_tag 2
#define GamesPreviewRoundResponse_state_tag 1
#define GamesAddOnlineReplayPayload_event_id_tag 1
#define GamesAddOnlineReplayPayload_link_tag 2
#define GamesAddOnlineReplayResponse_game_tag 1
#define GamesAddOnlineReplayResponse_players_tag 2
#define PlayersGetLastResultsPayload_player_id_tag 1
#define PlayersGetLastResultsPayload_event_id_tag 2
#define PlayersGetLastResultsResponse_results_tag 1
#define PlayersGetLastRoundPayload_player_id_tag 1
#define PlayersGetLastRoundPayload_event_id_tag 2
#define PlayersGetLastRoundResponse_round_tag 1
#define PlayersGetAllRoundsResponse_rounds_tag 1
#define PlayersGetLastRoundByHashResponse_round_tag 1
#define EventsGetEventForEditPayload_id_tag 1
#define EventsGetEventForEditResponse_id_tag 1
#define EventsGetEventForEditResponse_event_tag 2
#define EventsGetEventForEditResponse_finished_tag 3
#define EventsUpdateEventPayload_id_tag 1
#define EventsUpdateEventPayload_event_tag 2
#define EventsGetTablesStatePayload_event_id_tag 1
#define EventsGetTablesStatePayload_omit_last_round_tag 2
#define EventsGetTablesStateResponse_tables_tag 1
#define EventsRegisterPlayerPayload_player_id_tag 1
#define EventsRegisterPlayerPayload_event_id_tag 2
#define EventsUnregisterPlayerPayload_player_id_tag 1
#define EventsUnregisterPlayerPayload_event_id_tag 2
#define EventsUpdatePlayerSeatingFlagPayload_player_id_tag 1
#define EventsUpdatePlayerSeatingFlagPayload_event_id_tag 2
#define EventsUpdatePlayerSeatingFlagPayload_ignore_seating_tag 3
#define EventsGetAchievementsPayload_achievements_list_tag 2
#define EventsGetAchievementsPayload_event_id_tag 3
#define EventsGetAchievementsResponse_achievements_tag 1
#define EventsGetAchievementsResponse_last_update_tag 2
#define EventsUpdatePlayersLocalIdsPayload_event_id_tag 1
#define EventsUpdatePlayersLocalIdsPayload_ids_to_local_ids_tag 2
#define EventsUpdatePlayerReplacementPayload_player_id_tag 1
#define EventsUpdatePlayerReplacementPayload_event_id_tag 2
#define EventsUpdatePlayerReplacementPayload_replacement_id_tag 3
#define EventsUpdatePlayersTeamsPayload_event_id_tag 1
#define EventsUpdatePlayersTeamsPayload_ids_to_team_names_tag 2
#define GamesStartGamePayload_event_id_tag 1
#define GamesStartGamePayload_players_tag 2
#define GamesDropLastRoundPayload_session_hash_tag 1
#define GamesDropLastRoundPayload_intermediate_results_tag 2
#define GamesAddPenaltyPayload_event_id_tag 1
#define GamesAddPenaltyPayload_player_id_tag 2
#define GamesAddPenaltyPayload_amount_tag 3
#define GamesAddPenaltyPayload_reason_tag 4
#define GamesAddPenaltyGamePayload_event_id_tag 1
#define GamesAddPenaltyGamePayload_players_tag 2
#define PlayersGetPlayerPayload_id_tag 1
#define PlayersGetPlayerResponse_players_tag 1
#define EventsGetCurrentSeatingResponse_seating_tag 1
#define SeatingMakeShuffledSeatingPayload_event_id_tag 1
#define SeatingMakeShuffledSeatingPayload_groups_count_tag 2
#define SeatingMakeShuffledSeatingPayload_seed_tag 3
#define SeatingGenerateSwissSeatingPayload_event_id_tag 1
#define SeatingGenerateSwissSeatingPayload_substitute_replacement_players_tag 2
#define SeatingGenerateSwissSeatingResponse_tables_tag 1
#define SeatingMakeIntervalSeatingPayload_event_id_tag 1
#define SeatingMakeIntervalSeatingPayload_step_tag 2
#define SeatingMakePrescriptedSeatingPayload_event_id_tag 1
#define SeatingMakePrescriptedSeatingPayload_randomize_at_tables_tag 2
#define SeatingGetNextPrescriptedSeatingResponse_tables_tag 1
#define EventsGetPrescriptedEventConfigResponse_event_id_tag 1
#define EventsGetPrescriptedEventConfigResponse_next_session_index_tag 2
#define EventsGetPrescriptedEventConfigResponse_prescript_tag 3
#define EventsGetPrescriptedEventConfigResponse_errors_tag 4
#define EventsUpdatePrescriptedEventConfigPayload_event_id_tag 1
#define EventsUpdatePrescriptedEventConfigPayload_next_session_index_tag 2
#define EventsUpdatePrescriptedEventConfigPayload_prescript_tag 3
#define EventsGetStartingTimerResponse_timer_tag 1
#define ClearStatCachePayload_player_id_tag 1
#define TypedGamesAddOnlineReplayPayload_event_id_tag 1
#define TypedGamesAddOnlineReplayPayload_platform_id_tag 2
#define TypedGamesAddOnlineReplayPayload_content_type_tag 3
#define TypedGamesAddOnlineReplayPayload_log_timestamp_tag 4
#define TypedGamesAddOnlineReplayPayload_replay_hash_tag 5
#define TypedGamesAddOnlineReplayPayload_content_tag 6
#define CallRefereePayload_table_index_tag 1
#define CallRefereePayload_event_id_tag 2
#define PenaltiesResponse_penalties_tag 1
#define PenaltiesResponse_referees_tag 2
#define CancelPenaltyPayload_penalty_id_tag 1
#define CancelPenaltyPayload_reason_tag 2
#define AddExtraTimePayload_session_hash_list_tag 1
#define AddExtraTimePayload_extra_time_tag 2
#define GetCurrentStatePayload_event_id_tag 1
#define GetCurrentStatePayload_player_id_tag 2
#define GetCurrentStateResponse_sessions_tag 1
#define GetCurrentStateResponse_config_tag 2
#define ChomboResponse_chombos_tag 1
#define ChomboResponse_players_tag 2

/* Struct field encoding specification for nanopb */
#define EventsGetRulesetsPayload_FIELDLIST(X, a)

#define EventsGetRulesetsPayload_CALLBACK NULL
#define EventsGetRulesetsPayload_DEFAULT NULL

#define EventsGetRulesetsResponse_FIELDLIST(X, a)        \
	X(a, CALLBACK, REPEATED, MESSAGE, rulesets, 1)   \
	X(a, CALLBACK, REPEATED, STRING, ruleset_ids, 2) \
	X(a, CALLBACK, REPEATED, STRING, ruleset_titles, 3)
#define EventsGetRulesetsResponse_CALLBACK pb_default_field_callback
#define EventsGetRulesetsResponse_DEFAULT NULL
#define EventsGetRulesetsResponse_rulesets_MSGTYPE RulesetConfig

#define EventsGetEventsPayload_FIELDLIST(X, a)           \
	X(a, STATIC, SINGULAR, INT32, limit, 1)          \
	X(a, STATIC, SINGULAR, INT32, offset, 2)         \
	X(a, STATIC, SINGULAR, BOOL, filter_unlisted, 3) \
	X(a, CALLBACK, SINGULAR, STRING, filter, 4)
#define EventsGetEventsPayload_CALLBACK pb_default_field_callback
#define EventsGetEventsPayload_DEFAULT NULL

#define EventsGetEventsResponse_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, total, 1) \
	X(a, CALLBACK, REPEATED, MESSAGE, events, 2)
#define EventsGetEventsResponse_CALLBACK pb_default_field_callback
#define EventsGetEventsResponse_DEFAULT NULL
#define EventsGetEventsResponse_events_MSGTYPE Event

#define EventsGetEventsByIdPayload_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, INT32, ids, 1)
#define EventsGetEventsByIdPayload_CALLBACK pb_default_field_callback
#define EventsGetEventsByIdPayload_DEFAULT NULL

#define EventsGetEventsByIdResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, events, 1)
#define EventsGetEventsByIdResponse_CALLBACK pb_default_field_callback
#define EventsGetEventsByIdResponse_DEFAULT NULL
#define EventsGetEventsByIdResponse_events_MSGTYPE Event

#define PlayersGetMyEventsPayload_FIELDLIST(X, a)

#define PlayersGetMyEventsPayload_CALLBACK NULL
#define PlayersGetMyEventsPayload_DEFAULT NULL

#define PlayersGetMyEventsResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, events, 1)
#define PlayersGetMyEventsResponse_CALLBACK pb_default_field_callback
#define PlayersGetMyEventsResponse_DEFAULT NULL
#define PlayersGetMyEventsResponse_events_MSGTYPE MyEvent

#define EventsGetRatingTablePayload_FIELDLIST(X, a)       \
	X(a, CALLBACK, REPEATED, INT32, event_id_list, 1) \
	X(a, CALLBACK, SINGULAR, STRING, order_by, 2)     \
	X(a, CALLBACK, SINGULAR, STRING, order, 3)        \
	X(a, STATIC, OPTIONAL, BOOL, only_min_games, 5)
#define EventsGetRatingTablePayload_CALLBACK pb_default_field_callback
#define EventsGetRatingTablePayload_DEFAULT NULL

#define EventsGetRatingTableResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, list, 1)
#define EventsGetRatingTableResponse_CALLBACK pb_default_field_callback
#define EventsGetRatingTableResponse_DEFAULT NULL
#define EventsGetRatingTableResponse_list_MSGTYPE PlayerInRating

#define EventsGetLastGamesPayload_FIELDLIST(X, a)         \
	X(a, CALLBACK, REPEATED, INT32, event_id_list, 1) \
	X(a, STATIC, SINGULAR, INT32, limit, 2)           \
	X(a, STATIC, SINGULAR, INT32, offset, 3)          \
	X(a, CALLBACK, OPTIONAL, STRING, order_by, 4)     \
	X(a, CALLBACK, OPTIONAL, STRING, order, 5)
#define EventsGetLastGamesPayload_CALLBACK pb_default_field_callback
#define EventsGetLastGamesPayload_DEFAULT NULL

#define EventsGetLastGamesResponse_FIELDLIST(X, a)    \
	X(a, CALLBACK, REPEATED, MESSAGE, games, 1)   \
	X(a, CALLBACK, REPEATED, MESSAGE, players, 2) \
	X(a, STATIC, SINGULAR, INT32, total_games, 3)
#define EventsGetLastGamesResponse_CALLBACK pb_default_field_callback
#define EventsGetLastGamesResponse_DEFAULT NULL
#define EventsGetLastGamesResponse_games_MSGTYPE GameResult
#define EventsGetLastGamesResponse_players_MSGTYPE Player

#define EventsGetGameResponse_FIELDLIST(X, a)    \
	X(a, STATIC, OPTIONAL, MESSAGE, game, 1) \
	X(a, CALLBACK, REPEATED, MESSAGE, players, 2)
#define EventsGetGameResponse_CALLBACK pb_default_field_callback
#define EventsGetGameResponse_DEFAULT NULL
#define EventsGetGameResponse_game_MSGTYPE GameResult
#define EventsGetGameResponse_players_MSGTYPE Player

#define EventsGetGamesSeriesResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, results, 1)
#define EventsGetGamesSeriesResponse_CALLBACK pb_default_field_callback
#define EventsGetGamesSeriesResponse_DEFAULT NULL
#define EventsGetGamesSeriesResponse_results_MSGTYPE SeriesResult

#define PlayersGetCurrentSessionsPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, player_id, 1)      \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)
#define PlayersGetCurrentSessionsPayload_CALLBACK NULL
#define PlayersGetCurrentSessionsPayload_DEFAULT NULL

#define CurrentSession_FIELDLIST(X, a)                  \
	X(a, STATIC, SINGULAR, STRING, session_hash, 1) \
	X(a, STATIC, SINGULAR, STRING, status, 2)       \
	X(a, STATIC, OPTIONAL, INT32, table_index, 3)   \
	X(a, STATIC, REPEATED, MESSAGE, players, 4)     \
	X(a, STATIC, OPTIONAL, MESSAGE, timer_state, 5)
#define CurrentSession_CALLBACK NULL
#define CurrentSession_DEFAULT NULL
#define CurrentSession_players_MSGTYPE PlayerInSession
#define CurrentSession_timer_state_MSGTYPE EventsGetTimerStateResponse

#define PlayersGetCurrentSessionsResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, sessions, 1)
#define PlayersGetCurrentSessionsResponse_CALLBACK pb_default_field_callback
#define PlayersGetCurrentSessionsResponse_DEFAULT NULL
#define PlayersGetCurrentSessionsResponse_sessions_MSGTYPE CurrentSession

#define EventsGetAllRegisteredPlayersPayload_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, INT32, event_ids, 1)
#define EventsGetAllRegisteredPlayersPayload_CALLBACK pb_default_field_callback
#define EventsGetAllRegisteredPlayersPayload_DEFAULT NULL

#define EventsGetAllRegisteredPlayersResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, players, 1)
#define EventsGetAllRegisteredPlayersResponse_CALLBACK pb_default_field_callback
#define EventsGetAllRegisteredPlayersResponse_DEFAULT NULL
#define EventsGetAllRegisteredPlayersResponse_players_MSGTYPE RegisteredPlayer

#define EventsGetTimerStateResponse_FIELDLIST(X, a)        \
	X(a, STATIC, SINGULAR, BOOL, started, 1)           \
	X(a, STATIC, SINGULAR, BOOL, finished, 2)          \
	X(a, STATIC, SINGULAR, INT32, time_remaining, 3)   \
	X(a, STATIC, SINGULAR, BOOL, waiting_for_timer, 4) \
	X(a, STATIC, SINGULAR, BOOL, have_autostart, 5)    \
	X(a, STATIC, SINGULAR, BOOL, autostart_timer, 6)   \
	X(a, STATIC, SINGULAR, INT32, hide_seating_after, 8)
#define EventsGetTimerStateResponse_CALLBACK NULL
#define EventsGetTimerStateResponse_DEFAULT NULL

#define GamesGetSessionOverviewResponse_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, id, 1)            \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)      \
	X(a, STATIC, OPTIONAL, INT32, table_index, 3)   \
	X(a, STATIC, REPEATED, MESSAGE, players, 4)     \
	X(a, STATIC, OPTIONAL, MESSAGE, state, 5)       \
	X(a, STATIC, OPTIONAL, MESSAGE, timer_state, 6)
#define GamesGetSessionOverviewResponse_CALLBACK NULL
#define GamesGetSessionOverviewResponse_DEFAULT NULL
#define GamesGetSessionOverviewResponse_players_MSGTYPE PlayerInSession
#define GamesGetSessionOverviewResponse_state_MSGTYPE SessionState
#define GamesGetSessionOverviewResponse_timer_state_MSGTYPE EventsGetTimerStateResponse

#define PlayersGetPlayerStatsPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, player_id, 1)  \
	X(a, CALLBACK, REPEATED, INT32, event_id_list, 2)
#define PlayersGetPlayerStatsPayload_CALLBACK pb_default_field_callback
#define PlayersGetPlayerStatsPayload_DEFAULT NULL

#define PlayersGetPlayerStatsResponse_FIELDLIST(X, a)             \
	X(a, CALLBACK, REPEATED, INT32, rating_history, 1)        \
	X(a, CALLBACK, REPEATED, MESSAGE, score_history, 2)       \
	X(a, CALLBACK, REPEATED, MESSAGE, players_info, 3)        \
	X(a, CALLBACK, REPEATED, MESSAGE, places_summary, 4)      \
	X(a, STATIC, SINGULAR, INT32, total_played_games, 5)      \
	X(a, STATIC, SINGULAR, INT32, total_played_rounds, 6)     \
	X(a, STATIC, OPTIONAL, MESSAGE, win_summary, 7)           \
	X(a, CALLBACK, REPEATED, MESSAGE, hands_value_summary, 8) \
	X(a, CALLBACK, REPEATED, MESSAGE, yaku_summary, 9)        \
	X(a, STATIC, OPTIONAL, MESSAGE, riichi_summary, 10)       \
	X(a, STATIC, OPTIONAL, MESSAGE, dora_stat, 11)            \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 12)
#define PlayersGetPlayerStatsResponse_CALLBACK pb_default_field_callback
#define PlayersGetPlayerStatsResponse_DEFAULT NULL
#define PlayersGetPlayerStatsResponse_score_history_MSGTYPE SessionHistoryResultTable
#define PlayersGetPlayerStatsResponse_players_info_MSGTYPE Player
#define PlayersGetPlayerStatsResponse_places_summary_MSGTYPE PlacesSummaryItem
#define PlayersGetPlayerStatsResponse_win_summary_MSGTYPE PlayerWinSummary
#define PlayersGetPlayerStatsResponse_hands_value_summary_MSGTYPE HandValueStat
#define PlayersGetPlayerStatsResponse_yaku_summary_MSGTYPE YakuStat
#define PlayersGetPlayerStatsResponse_riichi_summary_MSGTYPE RiichiSummary
#define PlayersGetPlayerStatsResponse_dora_stat_MSGTYPE DoraSummary

#define GamesAddRoundPayload_FIELDLIST(X, a)              \
	X(a, CALLBACK, SINGULAR, STRING, session_hash, 1) \
	X(a, STATIC, OPTIONAL, MESSAGE, round_data, 2)
#define GamesAddRoundPayload_CALLBACK pb_default_field_callback
#define GamesAddRoundPayload_DEFAULT NULL
#define GamesAddRoundPayload_round_data_MSGTYPE Round

#define GamesAddRoundResponse_FIELDLIST(X, a)                 \
	X(a, CALLBACK, REPEATED, MESSAGE, scores, 1)          \
	X(a, STATIC, SINGULAR, INT32, round, 3)               \
	X(a, STATIC, SINGULAR, INT32, honba, 4)               \
	X(a, STATIC, SINGULAR, INT32, riichi_bets, 5)         \
	X(a, STATIC, SINGULAR, BOOL, prematurely_finished, 6) \
	X(a, STATIC, SINGULAR, BOOL, round_just_changed, 7)   \
	X(a, STATIC, SINGULAR, BOOL, is_finished, 8)          \
	X(a, STATIC, SINGULAR, BOOL, last_hand_started, 9)    \
	X(a, STATIC, OPTIONAL, UENUM, last_outcome, 10)
#define GamesAddRoundResponse_CALLBACK pb_default_field_callback
#define GamesAddRoundResponse_DEFAULT NULL
#define GamesAddRoundResponse_scores_MSGTYPE IntermediateResultOfSession

#define GamesPreviewRoundPayload_FIELDLIST(X, a)          \
	X(a, CALLBACK, SINGULAR, STRING, session_hash, 1) \
	X(a, STATIC, OPTIONAL, MESSAGE, round_data, 2)
#define GamesPreviewRoundPayload_CALLBACK pb_default_field_callback
#define GamesPreviewRoundPayload_DEFAULT NULL
#define GamesPreviewRoundPayload_round_data_MSGTYPE Round

#define GamesPreviewRoundResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, state, 1)
#define GamesPreviewRoundResponse_CALLBACK NULL
#define GamesPreviewRoundResponse_DEFAULT NULL
#define GamesPreviewRoundResponse_state_MSGTYPE RoundState

#define GamesAddOnlineReplayPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)  \
	X(a, CALLBACK, SINGULAR, STRING, link, 2)
#define GamesAddOnlineReplayPayload_CALLBACK pb_default_field_callback
#define GamesAddOnlineReplayPayload_DEFAULT NULL

#define GamesAddOnlineReplayResponse_FIELDLIST(X, a) \
	X(a, STATIC, OPTIONAL, MESSAGE, game, 1)     \
	X(a, CALLBACK, REPEATED, MESSAGE, players, 2)
#define GamesAddOnlineReplayResponse_CALLBACK pb_default_field_callback
#define GamesAddOnlineReplayResponse_DEFAULT NULL
#define GamesAddOnlineReplayResponse_game_MSGTYPE GameResult
#define GamesAddOnlineReplayResponse_players_MSGTYPE Player

#define PlayersGetLastResultsPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, player_id, 1)  \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)
#define PlayersGetLastResultsPayload_CALLBACK NULL
#define PlayersGetLastResultsPayload_DEFAULT NULL

#define PlayersGetLastResultsResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, results, 1)
#define PlayersGetLastResultsResponse_CALLBACK pb_default_field_callback
#define PlayersGetLastResultsResponse_DEFAULT NULL
#define PlayersGetLastResultsResponse_results_MSGTYPE SessionHistoryResult

#define PlayersGetLastRoundPayload_FIELDLIST(X, a)  \
	X(a, STATIC, SINGULAR, INT32, player_id, 1) \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)
#define PlayersGetLastRoundPayload_CALLBACK NULL
#define PlayersGetLastRoundPayload_DEFAULT NULL

#define PlayersGetLastRoundResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, round, 1)
#define PlayersGetLastRoundResponse_CALLBACK NULL
#define PlayersGetLastRoundResponse_DEFAULT NULL
#define PlayersGetLastRoundResponse_round_MSGTYPE RoundState

#define PlayersGetAllRoundsResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, rounds, 1)
#define PlayersGetAllRoundsResponse_CALLBACK pb_default_field_callback
#define PlayersGetAllRoundsResponse_DEFAULT NULL
#define PlayersGetAllRoundsResponse_rounds_MSGTYPE RoundState

#define PlayersGetLastRoundByHashResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, round, 1)
#define PlayersGetLastRoundByHashResponse_CALLBACK NULL
#define PlayersGetLastRoundByHashResponse_DEFAULT NULL
#define PlayersGetLastRoundByHashResponse_round_MSGTYPE RoundState

#define EventsGetEventForEditPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, id, 1)
#define EventsGetEventForEditPayload_CALLBACK NULL
#define EventsGetEventForEditPayload_DEFAULT NULL

#define EventsGetEventForEditResponse_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, id, 1)          \
	X(a, STATIC, OPTIONAL, MESSAGE, event, 2)     \
	X(a, STATIC, SINGULAR, BOOL, finished, 3)
#define EventsGetEventForEditResponse_CALLBACK NULL
#define EventsGetEventForEditResponse_DEFAULT NULL
#define EventsGetEventForEditResponse_event_MSGTYPE EventData

#define EventsUpdateEventPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, id, 1)     \
	X(a, STATIC, OPTIONAL, MESSAGE, event, 2)
#define EventsUpdateEventPayload_CALLBACK NULL
#define EventsUpdateEventPayload_DEFAULT NULL
#define EventsUpdateEventPayload_event_MSGTYPE EventData

#define EventsGetTablesStatePayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)  \
	X(a, STATIC, SINGULAR, BOOL, omit_last_round, 2)
#define EventsGetTablesStatePayload_CALLBACK NULL
#define EventsGetTablesStatePayload_DEFAULT NULL

#define EventsGetTablesStateResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, tables, 1)
#define EventsGetTablesStateResponse_CALLBACK pb_default_field_callback
#define EventsGetTablesStateResponse_DEFAULT NULL
#define EventsGetTablesStateResponse_tables_MSGTYPE TableState

#define EventsRegisterPlayerPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, player_id, 1) \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)
#define EventsRegisterPlayerPayload_CALLBACK NULL
#define EventsRegisterPlayerPayload_DEFAULT NULL

#define EventsUnregisterPlayerPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, player_id, 1)   \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)
#define EventsUnregisterPlayerPayload_CALLBACK NULL
#define EventsUnregisterPlayerPayload_DEFAULT NULL

#define EventsUpdatePlayerSeatingFlagPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, player_id, 1)          \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)           \
	X(a, STATIC, SINGULAR, BOOL, ignore_seating, 3)
#define EventsUpdatePlayerSeatingFlagPayload_CALLBACK NULL
#define EventsUpdatePlayerSeatingFlagPayload_DEFAULT NULL

#define EventsGetAchievementsPayload_FIELDLIST(X, a)           \
	X(a, CALLBACK, REPEATED, STRING, achievements_list, 2) \
	X(a, STATIC, SINGULAR, INT32, event_id, 3)
#define EventsGetAchievementsPayload_CALLBACK pb_default_field_callback
#define EventsGetAchievementsPayload_DEFAULT NULL

#define EventsGetAchievementsResponse_FIELDLIST(X, a)      \
	X(a, CALLBACK, REPEATED, MESSAGE, achievements, 1) \
	X(a, CALLBACK, SINGULAR, STRING, last_update, 2)
#define EventsGetAchievementsResponse_CALLBACK pb_default_field_callback
#define EventsGetAchievementsResponse_DEFAULT NULL
#define EventsGetAchievementsResponse_achievements_MSGTYPE Achievement

#define EventsUpdatePlayersLocalIdsPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)         \
	X(a, CALLBACK, REPEATED, MESSAGE, ids_to_local_ids, 2)
#define EventsUpdatePlayersLocalIdsPayload_CALLBACK pb_default_field_callback
#define EventsUpdatePlayersLocalIdsPayload_DEFAULT NULL
#define EventsUpdatePlayersLocalIdsPayload_ids_to_local_ids_MSGTYPE LocalIdMapping

#define EventsUpdatePlayerReplacementPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, player_id, 1)          \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)           \
	X(a, STATIC, SINGULAR, INT32, replacement_id, 3)
#define EventsUpdatePlayerReplacementPayload_CALLBACK NULL
#define EventsUpdatePlayerReplacementPayload_DEFAULT NULL

#define EventsUpdatePlayersTeamsPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)      \
	X(a, CALLBACK, REPEATED, MESSAGE, ids_to_team_names, 2)
#define EventsUpdatePlayersTeamsPayload_CALLBACK pb_default_field_callback
#define EventsUpdatePlayersTeamsPayload_DEFAULT NULL
#define EventsUpdatePlayersTeamsPayload_ids_to_team_names_MSGTYPE TeamMapping

#define GamesStartGamePayload_FIELDLIST(X, a)      \
	X(a, STATIC, SINGULAR, INT32, event_id, 1) \
	X(a, CALLBACK, REPEATED, INT32, players, 2)
#define GamesStartGamePayload_CALLBACK pb_default_field_callback
#define GamesStartGamePayload_DEFAULT NULL

#define GamesDropLastRoundPayload_FIELDLIST(X, a)         \
	X(a, CALLBACK, SINGULAR, STRING, session_hash, 1) \
	X(a, CALLBACK, REPEATED, MESSAGE, intermediate_results, 2)
#define GamesDropLastRoundPayload_CALLBACK pb_default_field_callback
#define GamesDropLastRoundPayload_DEFAULT NULL
#define GamesDropLastRoundPayload_intermediate_results_MSGTYPE IntermediateResultOfSession

#define GamesAddPenaltyPayload_FIELDLIST(X, a)      \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)  \
	X(a, STATIC, SINGULAR, INT32, player_id, 2) \
	X(a, STATIC, SINGULAR, INT32, amount, 3)    \
	X(a, CALLBACK, SINGULAR, STRING, reason, 4)
#define GamesAddPenaltyPayload_CALLBACK pb_default_field_callback
#define GamesAddPenaltyPayload_DEFAULT NULL

#define GamesAddPenaltyGamePayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1) \
	X(a, CALLBACK, REPEATED, INT32, players, 2)
#define GamesAddPenaltyGamePayload_CALLBACK pb_default_field_callback
#define GamesAddPenaltyGamePayload_DEFAULT NULL

#define PlayersGetPlayerPayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, id, 1)
#define PlayersGetPlayerPayload_CALLBACK NULL
#define PlayersGetPlayerPayload_DEFAULT NULL

#define PlayersGetPlayerResponse_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, players, 1)
#define PlayersGetPlayerResponse_CALLBACK NULL
#define PlayersGetPlayerResponse_DEFAULT NULL
#define PlayersGetPlayerResponse_players_MSGTYPE Player

#define EventsGetCurrentSeatingResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, seating, 1)
#define EventsGetCurrentSeatingResponse_CALLBACK pb_default_field_callback
#define EventsGetCurrentSeatingResponse_DEFAULT NULL
#define EventsGetCurrentSeatingResponse_seating_MSGTYPE PlayerSeating

#define SeatingMakeShuffledSeatingPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)        \
	X(a, STATIC, SINGULAR, INT32, groups_count, 2)    \
	X(a, STATIC, SINGULAR, INT32, seed, 3)
#define SeatingMakeShuffledSeatingPayload_CALLBACK NULL
#define SeatingMakeShuffledSeatingPayload_DEFAULT NULL

#define SeatingGenerateSwissSeatingPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)         \
	X(a, STATIC, SINGULAR, BOOL, substitute_replacement_players, 2)
#define SeatingGenerateSwissSeatingPayload_CALLBACK NULL
#define SeatingGenerateSwissSeatingPayload_DEFAULT NULL

#define SeatingGenerateSwissSeatingResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, tables, 1)
#define SeatingGenerateSwissSeatingResponse_CALLBACK pb_default_field_callback
#define SeatingGenerateSwissSeatingResponse_DEFAULT NULL
#define SeatingGenerateSwissSeatingResponse_tables_MSGTYPE TableItemSwiss

#define SeatingMakeIntervalSeatingPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)        \
	X(a, STATIC, SINGULAR, INT32, step, 2)
#define SeatingMakeIntervalSeatingPayload_CALLBACK NULL
#define SeatingMakeIntervalSeatingPayload_DEFAULT NULL

#define SeatingMakePrescriptedSeatingPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)           \
	X(a, STATIC, SINGULAR, BOOL, randomize_at_tables, 2)
#define SeatingMakePrescriptedSeatingPayload_CALLBACK NULL
#define SeatingMakePrescriptedSeatingPayload_DEFAULT NULL

#define SeatingGetNextPrescriptedSeatingResponse_FIELDLIST(X, a) X(a, CALLBACK, REPEATED, MESSAGE, tables, 1)
#define SeatingGetNextPrescriptedSeatingResponse_CALLBACK pb_default_field_callback
#define SeatingGetNextPrescriptedSeatingResponse_DEFAULT NULL
#define SeatingGetNextPrescriptedSeatingResponse_tables_MSGTYPE PrescriptedTable

#define EventsGetPrescriptedEventConfigResponse_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)              \
	X(a, STATIC, SINGULAR, INT32, next_session_index, 2)    \
	X(a, CALLBACK, OPTIONAL, STRING, prescript, 3)          \
	X(a, CALLBACK, REPEATED, STRING, errors, 4)
#define EventsGetPrescriptedEventConfigResponse_CALLBACK pb_default_field_callback
#define EventsGetPrescriptedEventConfigResponse_DEFAULT NULL

#define EventsUpdatePrescriptedEventConfigPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)                \
	X(a, STATIC, SINGULAR, INT32, next_session_index, 2)      \
	X(a, CALLBACK, SINGULAR, STRING, prescript, 3)
#define EventsUpdatePrescriptedEventConfigPayload_CALLBACK pb_default_field_callback
#define EventsUpdatePrescriptedEventConfigPayload_DEFAULT NULL

#define EventsGetStartingTimerResponse_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, timer, 1)
#define EventsGetStartingTimerResponse_CALLBACK NULL
#define EventsGetStartingTimerResponse_DEFAULT NULL

#define ClearStatCachePayload_FIELDLIST(X, a) X(a, STATIC, SINGULAR, INT32, player_id, 1)
#define ClearStatCachePayload_CALLBACK NULL
#define ClearStatCachePayload_DEFAULT NULL

#define TypedGamesAddOnlineReplayPayload_FIELDLIST(X, a) \
	X(a, STATIC, SINGULAR, INT32, event_id, 1)       \
	X(a, STATIC, SINGULAR, INT32, platform_id, 2)    \
	X(a, STATIC, SINGULAR, INT32, content_type, 3)   \
	X(a, STATIC, SINGULAR, INT32, log_timestamp, 4)  \
	X(a, CALLBACK, SINGULAR, STRING, replay_hash, 5) \
	X(a, CALLBACK, SINGULAR, STRING, content, 6)
#define TypedGamesAddOnlineReplayPayload_CALLBACK pb_default_field_callback
#define TypedGamesAddOnlineReplayPayload_DEFAULT NULL

#define CallRefereePayload_FIELDLIST(X, a)            \
	X(a, STATIC, SINGULAR, INT32, table_index, 1) \
	X(a, STATIC, SINGULAR, INT32, event_id, 2)
#define CallRefereePayload_CALLBACK NULL
#define CallRefereePayload_DEFAULT NULL

#define PenaltiesResponse_FIELDLIST(X, a)               \
	X(a, CALLBACK, REPEATED, MESSAGE, penalties, 1) \
	X(a, CALLBACK, REPEATED, MESSAGE, referees, 2)
#define PenaltiesResponse_CALLBACK pb_default_field_callback
#define PenaltiesResponse_DEFAULT NULL
#define PenaltiesResponse_penalties_MSGTYPE Penalty
#define PenaltiesResponse_referees_MSGTYPE Player

#define CancelPenaltyPayload_FIELDLIST(X, a)         \
	X(a, STATIC, SINGULAR, INT32, penalty_id, 1) \
	X(a, CALLBACK, OPTIONAL, STRING, reason, 2)
#define CancelPenaltyPayload_CALLBACK pb_default_field_callback
#define CancelPenaltyPayload_DEFAULT NULL

#define AddExtraTimePayload_FIELDLIST(X, a)                    \
	X(a, CALLBACK, REPEATED, STRING, session_hash_list, 1) \
	X(a, STATIC, SINGULAR, INT32, extra_time, 2)
#define AddExtraTimePayload_CALLBACK pb_default_field_callback
#define AddExtraTimePayload_DEFAULT NULL

#define GetCurrentStatePayload_FIELDLIST(X, a)     \
	X(a, STATIC, SINGULAR, INT32, event_id, 1) \
	X(a, STATIC, SINGULAR, INT32, player_id, 2)
#define GetCurrentStatePayload_CALLBACK NULL
#define GetCurrentStatePayload_DEFAULT NULL

#define GetCurrentStateResponse_FIELDLIST(X, a)      \
	X(a, STATIC, REPEATED, MESSAGE, sessions, 1) \
	X(a, STATIC, OPTIONAL, MESSAGE, config, 2)
#define GetCurrentStateResponse_CALLBACK NULL
#define GetCurrentStateResponse_DEFAULT NULL
#define GetCurrentStateResponse_sessions_MSGTYPE CurrentSession
#define GetCurrentStateResponse_config_MSGTYPE GameConfig

#define ChomboResponse_FIELDLIST(X, a)                \
	X(a, CALLBACK, REPEATED, MESSAGE, chombos, 1) \
	X(a, CALLBACK, REPEATED, MESSAGE, players, 2)
#define ChomboResponse_CALLBACK pb_default_field_callback
#define ChomboResponse_DEFAULT NULL
#define ChomboResponse_chombos_MSGTYPE Chombo
#define ChomboResponse_players_MSGTYPE Player

extern const pb_msgdesc_t EventsGetRulesetsPayload_msg;
extern const pb_msgdesc_t EventsGetRulesetsResponse_msg;
extern const pb_msgdesc_t EventsGetEventsPayload_msg;
extern const pb_msgdesc_t EventsGetEventsResponse_msg;
extern const pb_msgdesc_t EventsGetEventsByIdPayload_msg;
extern const pb_msgdesc_t EventsGetEventsByIdResponse_msg;
extern const pb_msgdesc_t PlayersGetMyEventsPayload_msg;
extern const pb_msgdesc_t PlayersGetMyEventsResponse_msg;
extern const pb_msgdesc_t EventsGetRatingTablePayload_msg;
extern const pb_msgdesc_t EventsGetRatingTableResponse_msg;
extern const pb_msgdesc_t EventsGetLastGamesPayload_msg;
extern const pb_msgdesc_t EventsGetLastGamesResponse_msg;
extern const pb_msgdesc_t EventsGetGameResponse_msg;
extern const pb_msgdesc_t EventsGetGamesSeriesResponse_msg;
extern const pb_msgdesc_t PlayersGetCurrentSessionsPayload_msg;
extern const pb_msgdesc_t CurrentSession_msg;
extern const pb_msgdesc_t PlayersGetCurrentSessionsResponse_msg;
extern const pb_msgdesc_t EventsGetAllRegisteredPlayersPayload_msg;
extern const pb_msgdesc_t EventsGetAllRegisteredPlayersResponse_msg;
extern const pb_msgdesc_t EventsGetTimerStateResponse_msg;
extern const pb_msgdesc_t GamesGetSessionOverviewResponse_msg;
extern const pb_msgdesc_t PlayersGetPlayerStatsPayload_msg;
extern const pb_msgdesc_t PlayersGetPlayerStatsResponse_msg;
extern const pb_msgdesc_t GamesAddRoundPayload_msg;
extern const pb_msgdesc_t GamesAddRoundResponse_msg;
extern const pb_msgdesc_t GamesPreviewRoundPayload_msg;
extern const pb_msgdesc_t GamesPreviewRoundResponse_msg;
extern const pb_msgdesc_t GamesAddOnlineReplayPayload_msg;
extern const pb_msgdesc_t GamesAddOnlineReplayResponse_msg;
extern const pb_msgdesc_t PlayersGetLastResultsPayload_msg;
extern const pb_msgdesc_t PlayersGetLastResultsResponse_msg;
extern const pb_msgdesc_t PlayersGetLastRoundPayload_msg;
extern const pb_msgdesc_t PlayersGetLastRoundResponse_msg;
extern const pb_msgdesc_t PlayersGetAllRoundsResponse_msg;
extern const pb_msgdesc_t PlayersGetLastRoundByHashResponse_msg;
extern const pb_msgdesc_t EventsGetEventForEditPayload_msg;
extern const pb_msgdesc_t EventsGetEventForEditResponse_msg;
extern const pb_msgdesc_t EventsUpdateEventPayload_msg;
extern const pb_msgdesc_t EventsGetTablesStatePayload_msg;
extern const pb_msgdesc_t EventsGetTablesStateResponse_msg;
extern const pb_msgdesc_t EventsRegisterPlayerPayload_msg;
extern const pb_msgdesc_t EventsUnregisterPlayerPayload_msg;
extern const pb_msgdesc_t EventsUpdatePlayerSeatingFlagPayload_msg;
extern const pb_msgdesc_t EventsGetAchievementsPayload_msg;
extern const pb_msgdesc_t EventsGetAchievementsResponse_msg;
extern const pb_msgdesc_t EventsUpdatePlayersLocalIdsPayload_msg;
extern const pb_msgdesc_t EventsUpdatePlayerReplacementPayload_msg;
extern const pb_msgdesc_t EventsUpdatePlayersTeamsPayload_msg;
extern const pb_msgdesc_t GamesStartGamePayload_msg;
extern const pb_msgdesc_t GamesDropLastRoundPayload_msg;
extern const pb_msgdesc_t GamesAddPenaltyPayload_msg;
extern const pb_msgdesc_t GamesAddPenaltyGamePayload_msg;
extern const pb_msgdesc_t PlayersGetPlayerPayload_msg;
extern const pb_msgdesc_t PlayersGetPlayerResponse_msg;
extern const pb_msgdesc_t EventsGetCurrentSeatingResponse_msg;
extern const pb_msgdesc_t SeatingMakeShuffledSeatingPayload_msg;
extern const pb_msgdesc_t SeatingGenerateSwissSeatingPayload_msg;
extern const pb_msgdesc_t SeatingGenerateSwissSeatingResponse_msg;
extern const pb_msgdesc_t SeatingMakeIntervalSeatingPayload_msg;
extern const pb_msgdesc_t SeatingMakePrescriptedSeatingPayload_msg;
extern const pb_msgdesc_t SeatingGetNextPrescriptedSeatingResponse_msg;
extern const pb_msgdesc_t EventsGetPrescriptedEventConfigResponse_msg;
extern const pb_msgdesc_t EventsUpdatePrescriptedEventConfigPayload_msg;
extern const pb_msgdesc_t EventsGetStartingTimerResponse_msg;
extern const pb_msgdesc_t ClearStatCachePayload_msg;
extern const pb_msgdesc_t TypedGamesAddOnlineReplayPayload_msg;
extern const pb_msgdesc_t CallRefereePayload_msg;
extern const pb_msgdesc_t PenaltiesResponse_msg;
extern const pb_msgdesc_t CancelPenaltyPayload_msg;
extern const pb_msgdesc_t AddExtraTimePayload_msg;
extern const pb_msgdesc_t GetCurrentStatePayload_msg;
extern const pb_msgdesc_t GetCurrentStateResponse_msg;
extern const pb_msgdesc_t ChomboResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EventsGetRulesetsPayload_fields &EventsGetRulesetsPayload_msg
#define EventsGetRulesetsResponse_fields &EventsGetRulesetsResponse_msg
#define EventsGetEventsPayload_fields &EventsGetEventsPayload_msg
#define EventsGetEventsResponse_fields &EventsGetEventsResponse_msg
#define EventsGetEventsByIdPayload_fields &EventsGetEventsByIdPayload_msg
#define EventsGetEventsByIdResponse_fields &EventsGetEventsByIdResponse_msg
#define PlayersGetMyEventsPayload_fields &PlayersGetMyEventsPayload_msg
#define PlayersGetMyEventsResponse_fields &PlayersGetMyEventsResponse_msg
#define EventsGetRatingTablePayload_fields &EventsGetRatingTablePayload_msg
#define EventsGetRatingTableResponse_fields &EventsGetRatingTableResponse_msg
#define EventsGetLastGamesPayload_fields &EventsGetLastGamesPayload_msg
#define EventsGetLastGamesResponse_fields &EventsGetLastGamesResponse_msg
#define EventsGetGameResponse_fields &EventsGetGameResponse_msg
#define EventsGetGamesSeriesResponse_fields &EventsGetGamesSeriesResponse_msg
#define PlayersGetCurrentSessionsPayload_fields &PlayersGetCurrentSessionsPayload_msg
#define CurrentSession_fields &CurrentSession_msg
#define PlayersGetCurrentSessionsResponse_fields &PlayersGetCurrentSessionsResponse_msg
#define EventsGetAllRegisteredPlayersPayload_fields &EventsGetAllRegisteredPlayersPayload_msg
#define EventsGetAllRegisteredPlayersResponse_fields &EventsGetAllRegisteredPlayersResponse_msg
#define EventsGetTimerStateResponse_fields &EventsGetTimerStateResponse_msg
#define GamesGetSessionOverviewResponse_fields &GamesGetSessionOverviewResponse_msg
#define PlayersGetPlayerStatsPayload_fields &PlayersGetPlayerStatsPayload_msg
#define PlayersGetPlayerStatsResponse_fields &PlayersGetPlayerStatsResponse_msg
#define GamesAddRoundPayload_fields &GamesAddRoundPayload_msg
#define GamesAddRoundResponse_fields &GamesAddRoundResponse_msg
#define GamesPreviewRoundPayload_fields &GamesPreviewRoundPayload_msg
#define GamesPreviewRoundResponse_fields &GamesPreviewRoundResponse_msg
#define GamesAddOnlineReplayPayload_fields &GamesAddOnlineReplayPayload_msg
#define GamesAddOnlineReplayResponse_fields &GamesAddOnlineReplayResponse_msg
#define PlayersGetLastResultsPayload_fields &PlayersGetLastResultsPayload_msg
#define PlayersGetLastResultsResponse_fields &PlayersGetLastResultsResponse_msg
#define PlayersGetLastRoundPayload_fields &PlayersGetLastRoundPayload_msg
#define PlayersGetLastRoundResponse_fields &PlayersGetLastRoundResponse_msg
#define PlayersGetAllRoundsResponse_fields &PlayersGetAllRoundsResponse_msg
#define PlayersGetLastRoundByHashResponse_fields &PlayersGetLastRoundByHashResponse_msg
#define EventsGetEventForEditPayload_fields &EventsGetEventForEditPayload_msg
#define EventsGetEventForEditResponse_fields &EventsGetEventForEditResponse_msg
#define EventsUpdateEventPayload_fields &EventsUpdateEventPayload_msg
#define EventsGetTablesStatePayload_fields &EventsGetTablesStatePayload_msg
#define EventsGetTablesStateResponse_fields &EventsGetTablesStateResponse_msg
#define EventsRegisterPlayerPayload_fields &EventsRegisterPlayerPayload_msg
#define EventsUnregisterPlayerPayload_fields &EventsUnregisterPlayerPayload_msg
#define EventsUpdatePlayerSeatingFlagPayload_fields &EventsUpdatePlayerSeatingFlagPayload_msg
#define EventsGetAchievementsPayload_fields &EventsGetAchievementsPayload_msg
#define EventsGetAchievementsResponse_fields &EventsGetAchievementsResponse_msg
#define EventsUpdatePlayersLocalIdsPayload_fields &EventsUpdatePlayersLocalIdsPayload_msg
#define EventsUpdatePlayerReplacementPayload_fields &EventsUpdatePlayerReplacementPayload_msg
#define EventsUpdatePlayersTeamsPayload_fields &EventsUpdatePlayersTeamsPayload_msg
#define GamesStartGamePayload_fields &GamesStartGamePayload_msg
#define GamesDropLastRoundPayload_fields &GamesDropLastRoundPayload_msg
#define GamesAddPenaltyPayload_fields &GamesAddPenaltyPayload_msg
#define GamesAddPenaltyGamePayload_fields &GamesAddPenaltyGamePayload_msg
#define PlayersGetPlayerPayload_fields &PlayersGetPlayerPayload_msg
#define PlayersGetPlayerResponse_fields &PlayersGetPlayerResponse_msg
#define EventsGetCurrentSeatingResponse_fields &EventsGetCurrentSeatingResponse_msg
#define SeatingMakeShuffledSeatingPayload_fields &SeatingMakeShuffledSeatingPayload_msg
#define SeatingGenerateSwissSeatingPayload_fields &SeatingGenerateSwissSeatingPayload_msg
#define SeatingGenerateSwissSeatingResponse_fields &SeatingGenerateSwissSeatingResponse_msg
#define SeatingMakeIntervalSeatingPayload_fields &SeatingMakeIntervalSeatingPayload_msg
#define SeatingMakePrescriptedSeatingPayload_fields &SeatingMakePrescriptedSeatingPayload_msg
#define SeatingGetNextPrescriptedSeatingResponse_fields &SeatingGetNextPrescriptedSeatingResponse_msg
#define EventsGetPrescriptedEventConfigResponse_fields &EventsGetPrescriptedEventConfigResponse_msg
#define EventsUpdatePrescriptedEventConfigPayload_fields &EventsUpdatePrescriptedEventConfigPayload_msg
#define EventsGetStartingTimerResponse_fields &EventsGetStartingTimerResponse_msg
#define ClearStatCachePayload_fields &ClearStatCachePayload_msg
#define TypedGamesAddOnlineReplayPayload_fields &TypedGamesAddOnlineReplayPayload_msg
#define CallRefereePayload_fields &CallRefereePayload_msg
#define PenaltiesResponse_fields &PenaltiesResponse_msg
#define CancelPenaltyPayload_fields &CancelPenaltyPayload_msg
#define AddExtraTimePayload_fields &AddExtraTimePayload_msg
#define GetCurrentStatePayload_fields &GetCurrentStatePayload_msg
#define GetCurrentStateResponse_fields &GetCurrentStateResponse_msg
#define ChomboResponse_fields &ChomboResponse_msg

/* Maximum encoded size of messages (where known) */
/* EventsGetRulesetsResponse_size depends on runtime parameters */
/* EventsGetEventsPayload_size depends on runtime parameters */
/* EventsGetEventsResponse_size depends on runtime parameters */
/* EventsGetEventsByIdPayload_size depends on runtime parameters */
/* EventsGetEventsByIdResponse_size depends on runtime parameters */
/* PlayersGetMyEventsResponse_size depends on runtime parameters */
/* EventsGetRatingTablePayload_size depends on runtime parameters */
/* EventsGetRatingTableResponse_size depends on runtime parameters */
/* EventsGetLastGamesPayload_size depends on runtime parameters */
/* EventsGetLastGamesResponse_size depends on runtime parameters */
/* EventsGetGameResponse_size depends on runtime parameters */
/* EventsGetGamesSeriesResponse_size depends on runtime parameters */
/* PlayersGetCurrentSessionsResponse_size depends on runtime parameters */
/* EventsGetAllRegisteredPlayersPayload_size depends on runtime parameters */
/* EventsGetAllRegisteredPlayersResponse_size depends on runtime parameters */
/* PlayersGetPlayerStatsPayload_size depends on runtime parameters */
/* PlayersGetPlayerStatsResponse_size depends on runtime parameters */
/* GamesAddRoundPayload_size depends on runtime parameters */
/* GamesAddRoundResponse_size depends on runtime parameters */
/* GamesPreviewRoundPayload_size depends on runtime parameters */
/* GamesAddOnlineReplayPayload_size depends on runtime parameters */
/* GamesAddOnlineReplayResponse_size depends on runtime parameters */
/* PlayersGetLastResultsResponse_size depends on runtime parameters */
/* PlayersGetAllRoundsResponse_size depends on runtime parameters */
/* EventsGetTablesStateResponse_size depends on runtime parameters */
/* EventsGetAchievementsPayload_size depends on runtime parameters */
/* EventsGetAchievementsResponse_size depends on runtime parameters */
/* EventsUpdatePlayersLocalIdsPayload_size depends on runtime parameters */
/* EventsUpdatePlayersTeamsPayload_size depends on runtime parameters */
/* GamesStartGamePayload_size depends on runtime parameters */
/* GamesDropLastRoundPayload_size depends on runtime parameters */
/* GamesAddPenaltyPayload_size depends on runtime parameters */
/* GamesAddPenaltyGamePayload_size depends on runtime parameters */
/* EventsGetCurrentSeatingResponse_size depends on runtime parameters */
/* SeatingGenerateSwissSeatingResponse_size depends on runtime parameters */
/* SeatingGetNextPrescriptedSeatingResponse_size depends on runtime parameters */
/* EventsGetPrescriptedEventConfigResponse_size depends on runtime parameters */
/* EventsUpdatePrescriptedEventConfigPayload_size depends on runtime parameters */
/* TypedGamesAddOnlineReplayPayload_size depends on runtime parameters */
/* PenaltiesResponse_size depends on runtime parameters */
/* CancelPenaltyPayload_size depends on runtime parameters */
/* AddExtraTimePayload_size depends on runtime parameters */
/* ChomboResponse_size depends on runtime parameters */
#define CallRefereePayload_size 22
#define ClearStatCachePayload_size 11
#define EventsGetEventForEditPayload_size 11
#define EventsGetRulesetsPayload_size 0
#define EventsGetStartingTimerResponse_size 11
#define EventsGetTablesStatePayload_size 13
#define EventsGetTimerStateResponse_size 32
#define EventsRegisterPlayerPayload_size 22
#define EventsUnregisterPlayerPayload_size 22
#define EventsUpdatePlayerReplacementPayload_size 33
#define EventsUpdatePlayerSeatingFlagPayload_size 24
#define GetCurrentStatePayload_size 22
#define PlayersGetCurrentSessionsPayload_size 22
#define PlayersGetLastResultsPayload_size 22
#define PlayersGetLastRoundPayload_size 22
#define PlayersGetMyEventsPayload_size 0
#define PlayersGetPlayerPayload_size 11
#define SeatingGenerateSwissSeatingPayload_size 13
#define SeatingMakeIntervalSeatingPayload_size 22
#define SeatingMakePrescriptedSeatingPayload_size 13
#define SeatingMakeShuffledSeatingPayload_size 33
#if defined(PlayerInSession_size)
#define CurrentSession_size (331 + 4 * PlayerInSession_size)
#endif
#if defined(PlayerInSession_size) && defined(SessionState_size)
#define GamesGetSessionOverviewResponse_size (97 + 4 * PlayerInSession_size + SessionState_size)
#endif
#if defined(RoundState_size)
#define GamesPreviewRoundResponse_size (6 + RoundState_size)
#define PlayersGetLastRoundByHashResponse_size (6 + RoundState_size)
#define PlayersGetLastRoundResponse_size (6 + RoundState_size)
#endif
#if defined(EventData_size)
#define EventsGetEventForEditResponse_size (19 + EventData_size)
#define EventsUpdateEventPayload_size (17 + EventData_size)
#endif
#if defined(Player_size)
#define PlayersGetPlayerResponse_size (6 + Player_size)
#endif
#if defined(PlayerInSession_size) && defined(GameConfig_size)
#define GetCurrentStateResponse_size (1354 + 4 * 4 * PlayerInSession_size + GameConfig_size)
#define PROTO_MIMIR_PB_H_MAX_SIZE GetCurrentStateResponse_size
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
