/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/nanopb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(NanoPBOptions, NanoPBOptions, 2)

/* Definition for extension field nanopb_fileopt */
typedef struct _nanopb_fileopt_extmsg {
	NanoPBOptions nanopb_fileopt;
} nanopb_fileopt_extmsg;
#define nanopb_fileopt_extmsg_FIELDLIST(X, a) X(a, STATIC, REQUIRED, MESSAGE, nanopb_fileopt, 1010)
#define nanopb_fileopt_extmsg_CALLBACK NULL
#define nanopb_fileopt_extmsg_DEFAULT NULL
#define nanopb_fileopt_extmsg_nanopb_fileopt_MSGTYPE NanoPBOptions
pb_byte_t nanopb_fileopt_extmsg_default[] = { 0x00 };
PB_BIND(nanopb_fileopt_extmsg, nanopb_fileopt_extmsg, 2)
const pb_extension_type_t nanopb_fileopt = { NULL, NULL, &nanopb_fileopt_extmsg_msg };

/* Definition for extension field nanopb_msgopt */
typedef struct _nanopb_msgopt_extmsg {
	NanoPBOptions nanopb_msgopt;
} nanopb_msgopt_extmsg;
#define nanopb_msgopt_extmsg_FIELDLIST(X, a) X(a, STATIC, REQUIRED, MESSAGE, nanopb_msgopt, 1010)
#define nanopb_msgopt_extmsg_CALLBACK NULL
#define nanopb_msgopt_extmsg_DEFAULT NULL
#define nanopb_msgopt_extmsg_nanopb_msgopt_MSGTYPE NanoPBOptions
pb_byte_t nanopb_msgopt_extmsg_default[] = { 0x00 };
PB_BIND(nanopb_msgopt_extmsg, nanopb_msgopt_extmsg, 2)
const pb_extension_type_t nanopb_msgopt = { NULL, NULL, &nanopb_msgopt_extmsg_msg };

/* Definition for extension field nanopb_enumopt */
typedef struct _nanopb_enumopt_extmsg {
	NanoPBOptions nanopb_enumopt;
} nanopb_enumopt_extmsg;
#define nanopb_enumopt_extmsg_FIELDLIST(X, a) X(a, STATIC, REQUIRED, MESSAGE, nanopb_enumopt, 1010)
#define nanopb_enumopt_extmsg_CALLBACK NULL
#define nanopb_enumopt_extmsg_DEFAULT NULL
#define nanopb_enumopt_extmsg_nanopb_enumopt_MSGTYPE NanoPBOptions
pb_byte_t nanopb_enumopt_extmsg_default[] = { 0x00 };
PB_BIND(nanopb_enumopt_extmsg, nanopb_enumopt_extmsg, 2)
const pb_extension_type_t nanopb_enumopt = { NULL, NULL, &nanopb_enumopt_extmsg_msg };

/* Definition for extension field nanopbo */
typedef struct _nanopbo_extmsg {
	NanoPBOptions nanopbo;
} nanopbo_extmsg;
#define nanopbo_extmsg_FIELDLIST(X, a) X(a, STATIC, REQUIRED, MESSAGE, nanopbo, 1010)
#define nanopbo_extmsg_CALLBACK NULL
#define nanopbo_extmsg_DEFAULT NULL
#define nanopbo_extmsg_nanopbo_MSGTYPE NanoPBOptions
pb_byte_t nanopbo_extmsg_default[] = { 0x00 };
PB_BIND(nanopbo_extmsg, nanopbo_extmsg, 2)
const pb_extension_type_t nanopbo = { NULL, NULL, &nanopbo_extmsg_msg };
