/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: atoms.proto */

#ifndef PROTOBUF_C_atoms_2eproto__INCLUDED
#define PROTOBUF_C_atoms_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Common__EventAdmin Common__EventAdmin;
typedef struct Common__EventReferee Common__EventReferee;
typedef struct Common__Person Common__Person;
typedef struct Common__PersonEx Common__PersonEx;
typedef struct Common__Country Common__Country;
typedef struct Common__Event Common__Event;
typedef struct Common__MyEvent Common__MyEvent;
typedef struct Common__GameConfig Common__GameConfig;
typedef struct Common__Player Common__Player;
typedef struct Common__FinalResultOfSession Common__FinalResultOfSession;
typedef struct Common__RonResult Common__RonResult;
typedef struct Common__MultironWin Common__MultironWin;
typedef struct Common__MultironResult Common__MultironResult;
typedef struct Common__TsumoResult Common__TsumoResult;
typedef struct Common__DrawResult Common__DrawResult;
typedef struct Common__AbortResult Common__AbortResult;
typedef struct Common__ChomboResult Common__ChomboResult;
typedef struct Common__NagashiResult Common__NagashiResult;
typedef struct Common__Round Common__Round;
typedef struct Common__PlayerPlaceInSeries Common__PlayerPlaceInSeries;
typedef struct Common__SeriesResult Common__SeriesResult;
typedef struct Common__ReplacementPlayer Common__ReplacementPlayer;
typedef struct Common__PlayerInSession Common__PlayerInSession;
typedef struct Common__SessionHistoryResult Common__SessionHistoryResult;
typedef struct Common__SessionHistoryResultTable Common__SessionHistoryResultTable;
typedef struct Common__PlacesSummaryItem Common__PlacesSummaryItem;
typedef struct Common__PlayerWinSummary Common__PlayerWinSummary;
typedef struct Common__HandValueStat Common__HandValueStat;
typedef struct Common__YakuStat Common__YakuStat;
typedef struct Common__RiichiSummary Common__RiichiSummary;
typedef struct Common__DoraSummary Common__DoraSummary;
typedef struct Common__IntermediateResultOfSession Common__IntermediateResultOfSession;
typedef struct Common__Achievement Common__Achievement;
typedef struct Common__LocalIdMapping Common__LocalIdMapping;
typedef struct Common__TeamMapping Common__TeamMapping;
typedef struct Common__PlayerSeating Common__PlayerSeating;
typedef struct Common__PlayerSeatingSwiss Common__PlayerSeatingSwiss;
typedef struct Common__TableItemSwiss Common__TableItemSwiss;
typedef struct Common__Chombo Common__Chombo;
typedef struct Common__SessionState Common__SessionState;
typedef struct Common__Uma Common__Uma;
typedef struct Common__ComplexUma Common__ComplexUma;
typedef struct Common__RulesetConfig Common__RulesetConfig;
typedef struct Common__MajsoulSearchEx Common__MajsoulSearchEx;
typedef struct Common__MajsoulPersonMapping Common__MajsoulPersonMapping;
typedef struct Common__GenericSuccessResponse Common__GenericSuccessResponse;
typedef struct Common__GenericEventPayload Common__GenericEventPayload;
typedef struct Common__GenericSessionPayload Common__GenericSessionPayload;


/* --- enums --- */

typedef enum _Common__EventType {
  COMMON__EVENT_TYPE__EVENT_TYPE_UNSPECIFIED = 0,
  COMMON__EVENT_TYPE__EVENT_TYPE_TOURNAMENT = 1,
  COMMON__EVENT_TYPE__EVENT_TYPE_LOCAL = 2,
  COMMON__EVENT_TYPE__EVENT_TYPE_ONLINE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMON__EVENT_TYPE)
} Common__EventType;
typedef enum _Common__TournamentGamesStatus {
  /*
   * for non-tournament events
   */
  COMMON__TOURNAMENT_GAMES_STATUS__TOURNAMENT_GAMES_STATUS_UNSPECIFIED = 0,
  COMMON__TOURNAMENT_GAMES_STATUS__TOURNAMENT_GAMES_STATUS_SEATING_READY = 1,
  COMMON__TOURNAMENT_GAMES_STATUS__TOURNAMENT_GAMES_STATUS_STARTED = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMON__TOURNAMENT_GAMES_STATUS)
} Common__TournamentGamesStatus;
typedef enum _Common__RoundOutcome {
  COMMON__ROUND_OUTCOME__ROUND_OUTCOME_UNSPECIFIED = 0,
  COMMON__ROUND_OUTCOME__ROUND_OUTCOME_RON = 1,
  COMMON__ROUND_OUTCOME__ROUND_OUTCOME_TSUMO = 2,
  COMMON__ROUND_OUTCOME__ROUND_OUTCOME_DRAW = 3,
  COMMON__ROUND_OUTCOME__ROUND_OUTCOME_ABORT = 4,
  COMMON__ROUND_OUTCOME__ROUND_OUTCOME_CHOMBO = 5,
  COMMON__ROUND_OUTCOME__ROUND_OUTCOME_NAGASHI = 6,
  COMMON__ROUND_OUTCOME__ROUND_OUTCOME_MULTIRON = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMON__ROUND_OUTCOME)
} Common__RoundOutcome;
typedef enum _Common__SessionStatus {
  COMMON__SESSION_STATUS__SESSION_STATUS_UNSPECIFIED = 0,
  COMMON__SESSION_STATUS__SESSION_STATUS_INPROGRESS = 1,
  COMMON__SESSION_STATUS__SESSION_STATUS_PREFINISHED = 2,
  COMMON__SESSION_STATUS__SESSION_STATUS_FINISHED = 3,
  COMMON__SESSION_STATUS__SESSION_STATUS_CANCELLED = 4,
  COMMON__SESSION_STATUS__SESSION_STATUS_PLANNED = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMON__SESSION_STATUS)
} Common__SessionStatus;
typedef enum _Common__UmaType {
  COMMON__UMA_TYPE__UMA_TYPE_UNSPECIFIED = 0,
  COMMON__UMA_TYPE__UMA_TYPE_UMA_SIMPLE = 1,
  COMMON__UMA_TYPE__UMA_TYPE_UMA_COMPLEX = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMON__UMA_TYPE)
} Common__UmaType;
typedef enum _Common__EndingPolicy {
  COMMON__ENDING_POLICY__ENDING_POLICY_EP_UNSPECIFIED = 0,
  COMMON__ENDING_POLICY__ENDING_POLICY_EP_ONE_MORE_HAND = 1,
  COMMON__ENDING_POLICY__ENDING_POLICY_EP_END_AFTER_HAND = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMON__ENDING_POLICY)
} Common__EndingPolicy;
typedef enum _Common__PlatformType {
  COMMON__PLATFORM_TYPE__PLATFORM_TYPE_UNSPECIFIED = 0,
  COMMON__PLATFORM_TYPE__PLATFORM_TYPE_TENHOUNET = 1,
  COMMON__PLATFORM_TYPE__PLATFORM_TYPE_MAHJONGSOUL = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMON__PLATFORM_TYPE)
} Common__PlatformType;

/* --- messages --- */

struct  Common__EventAdmin
{
  ProtobufCMessage base;
  int32_t rule_id;
  int32_t person_id;
  char *person_name;
  protobuf_c_boolean has_avatar;
  char *last_update;
};
#define COMMON__EVENT_ADMIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__event_admin__descriptor) \
, 0, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  Common__EventReferee
{
  ProtobufCMessage base;
  int32_t rule_id;
  int32_t person_id;
  char *person_name;
  protobuf_c_boolean has_avatar;
  char *last_update;
};
#define COMMON__EVENT_REFEREE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__event_referee__descriptor) \
, 0, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  Common__Person
{
  ProtobufCMessage base;
  int32_t id;
  char *city;
  char *tenhou_id;
  char *title;
  protobuf_c_boolean has_avatar;
  char *last_update;
};
#define COMMON__PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__person__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  Common__PersonEx
{
  ProtobufCMessage base;
  int32_t id;
  char *city;
  char *tenhou_id;
  char *title;
  char *country;
  char *email;
  char *phone;
  protobuf_c_boolean has_avatar;
  char *last_update;
  char *ms_nickname;
  int32_t ms_account_id;
  char *telegram_id;
  char *notifications;
};
#define COMMON__PERSON_EX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__person_ex__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Common__Country
{
  ProtobufCMessage base;
  char *code;
  char *name;
};
#define COMMON__COUNTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__country__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Common__Event
{
  ProtobufCMessage base;
  int32_t id;
  char *title;
  char *description;
  protobuf_c_boolean finished;
  protobuf_c_boolean is_listed;
  protobuf_c_boolean is_rating_shown;
  protobuf_c_boolean tournament_started;
  Common__EventType type;
  protobuf_c_boolean is_prescripted;
  protobuf_c_boolean is_team;
  protobuf_c_boolean has_series;
  protobuf_c_boolean with_chips;
  int32_t min_games_count;
  protobuf_c_boolean achievements_shown;
  protobuf_c_boolean with_yakitori;
  Common__PlatformType platform_id;
};
#define COMMON__EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__event__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, COMMON__EVENT_TYPE__EVENT_TYPE_UNSPECIFIED, 0, 0, 0, 0, 0, 0, 0, COMMON__PLATFORM_TYPE__PLATFORM_TYPE_UNSPECIFIED }


struct  Common__MyEvent
{
  ProtobufCMessage base;
  int32_t id;
  char *title;
  char *description;
  protobuf_c_boolean is_online;
};
#define COMMON__MY_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__my_event__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Common__GameConfig
{
  ProtobufCMessage base;
  char *ruleset_title;
  char *event_title;
  char *event_description;
  char *event_stat_host;
  protobuf_c_boolean use_timer;
  protobuf_c_boolean use_penalty;
  /*
   * minutes
   */
  int32_t game_duration;
  char *timezone;
  protobuf_c_boolean is_online;
  protobuf_c_boolean is_team;
  protobuf_c_boolean auto_seating;
  protobuf_c_boolean sync_start;
  protobuf_c_boolean sync_end;
  protobuf_c_boolean sort_by_games;
  protobuf_c_boolean allow_player_append;
  int32_t series_length;
  int32_t min_games_count;
  Common__TournamentGamesStatus games_status;
  protobuf_c_boolean hide_results;
  protobuf_c_boolean hide_add_replay_button;
  protobuf_c_boolean is_prescripted;
  protobuf_c_boolean is_finished;
  Common__RulesetConfig *ruleset_config;
  int32_t lobby_id;
  protobuf_c_boolean allow_view_other_tables;
};
#define COMMON__GAME_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__game_config__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0, 0, 0, COMMON__TOURNAMENT_GAMES_STATUS__TOURNAMENT_GAMES_STATUS_UNSPECIFIED, 0, 0, 0, 0, NULL, 0, 0 }


struct  Common__Player
{
  ProtobufCMessage base;
  int32_t id;
  char *title;
  char *tenhou_id;
  protobuf_c_boolean has_avatar;
  char *last_update;
};
#define COMMON__PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__player__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  Common__FinalResultOfSession
{
  ProtobufCMessage base;
  int32_t player_id;
  int32_t score;
  float rating_delta;
  int32_t place;
};
#define COMMON__FINAL_RESULT_OF_SESSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__final_result_of_session__descriptor) \
, 0, 0, 0, 0 }


struct  Common__RonResult
{
  ProtobufCMessage base;
  int32_t round_index;
  int32_t honba;
  int32_t winner_id;
  int32_t loser_id;
  int32_t pao_player_id;
  int32_t han;
  int32_t fu;
  /*
   * yaku ids
   */
  size_t n_yaku;
  int32_t *yaku;
  /*
   * player ids
   */
  size_t n_riichi_bets;
  int32_t *riichi_bets;
  int32_t dora;
  int32_t uradora;
  int32_t kandora;
  int32_t kanuradora;
  protobuf_c_boolean open_hand;
};
#define COMMON__RON_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__ron_result__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0, 0, 0, 0, 0 }


struct  Common__MultironWin
{
  ProtobufCMessage base;
  int32_t winner_id;
  int32_t pao_player_id;
  int32_t han;
  int32_t fu;
  /*
   * yaku ids
   */
  size_t n_yaku;
  int32_t *yaku;
  int32_t dora;
  int32_t uradora;
  int32_t kandora;
  int32_t kanuradora;
  protobuf_c_boolean open_hand;
};
#define COMMON__MULTIRON_WIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__multiron_win__descriptor) \
, 0, 0, 0, 0, 0,NULL, 0, 0, 0, 0, 0 }


struct  Common__MultironResult
{
  ProtobufCMessage base;
  int32_t round_index;
  int32_t honba;
  int32_t loser_id;
  /*
   * count of players who won
   */
  int32_t multi_ron;
  size_t n_wins;
  Common__MultironWin **wins;
  /*
   * player ids
   */
  size_t n_riichi_bets;
  int32_t *riichi_bets;
};
#define COMMON__MULTIRON_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__multiron_result__descriptor) \
, 0, 0, 0, 0, 0,NULL, 0,NULL }


struct  Common__TsumoResult
{
  ProtobufCMessage base;
  int32_t round_index;
  int32_t honba;
  int32_t winner_id;
  int32_t pao_player_id;
  int32_t han;
  int32_t fu;
  /*
   * yaku ids
   */
  size_t n_yaku;
  int32_t *yaku;
  /*
   * player ids
   */
  size_t n_riichi_bets;
  int32_t *riichi_bets;
  int32_t dora;
  int32_t uradora;
  int32_t kandora;
  int32_t kanuradora;
  protobuf_c_boolean open_hand;
};
#define COMMON__TSUMO_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__tsumo_result__descriptor) \
, 0, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0, 0, 0, 0, 0 }


struct  Common__DrawResult
{
  ProtobufCMessage base;
  int32_t round_index;
  int32_t honba;
  /*
   * player ids
   */
  size_t n_riichi_bets;
  int32_t *riichi_bets;
  /*
   * player ids
   */
  size_t n_tempai;
  int32_t *tempai;
};
#define COMMON__DRAW_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__draw_result__descriptor) \
, 0, 0, 0,NULL, 0,NULL }


struct  Common__AbortResult
{
  ProtobufCMessage base;
  int32_t round_index;
  int32_t honba;
  /*
   * player ids
   */
  size_t n_riichi_bets;
  int32_t *riichi_bets;
};
#define COMMON__ABORT_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__abort_result__descriptor) \
, 0, 0, 0,NULL }


struct  Common__ChomboResult
{
  ProtobufCMessage base;
  int32_t round_index;
  int32_t honba;
  int32_t loser_id;
};
#define COMMON__CHOMBO_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__chombo_result__descriptor) \
, 0, 0, 0 }


struct  Common__NagashiResult
{
  ProtobufCMessage base;
  int32_t round_index;
  int32_t honba;
  /*
   * player ids
   */
  size_t n_riichi_bets;
  int32_t *riichi_bets;
  /*
   * player ids
   */
  size_t n_tempai;
  int32_t *tempai;
  /*
   * player ids
   */
  size_t n_nagashi;
  int32_t *nagashi;
};
#define COMMON__NAGASHI_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__nagashi_result__descriptor) \
, 0, 0, 0,NULL, 0,NULL, 0,NULL }


typedef enum {
  COMMON__ROUND__OUTCOME__NOT_SET = 0,
  COMMON__ROUND__OUTCOME_RON = 1,
  COMMON__ROUND__OUTCOME_TSUMO = 2,
  COMMON__ROUND__OUTCOME_MULTIRON = 3,
  COMMON__ROUND__OUTCOME_DRAW = 4,
  COMMON__ROUND__OUTCOME_ABORT = 5,
  COMMON__ROUND__OUTCOME_CHOMBO = 6,
  COMMON__ROUND__OUTCOME_NAGASHI = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COMMON__ROUND__OUTCOME__CASE)
} Common__Round__OutcomeCase;

struct  Common__Round
{
  ProtobufCMessage base;
  Common__Round__OutcomeCase outcome_case;
  union {
    Common__AbortResult *abort;
    Common__ChomboResult *chombo;
    Common__DrawResult *draw;
    Common__MultironResult *multiron;
    Common__NagashiResult *nagashi;
    Common__RonResult *ron;
    Common__TsumoResult *tsumo;
  };
};
#define COMMON__ROUND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__round__descriptor) \
, COMMON__ROUND__OUTCOME__NOT_SET, {0} }


struct  Common__PlayerPlaceInSeries
{
  ProtobufCMessage base;
  char *session_hash;
  int32_t place;
};
#define COMMON__PLAYER_PLACE_IN_SERIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__player_place_in_series__descriptor) \
, (char *)protobuf_c_empty_string, 0 }


struct  Common__SeriesResult
{
  ProtobufCMessage base;
  Common__Player *player;
  size_t n_best_series;
  Common__PlayerPlaceInSeries **best_series;
  float best_series_scores;
  int32_t best_series_places;
  /*
   * formatted numeric string
   */
  char *best_series_avg_place;
  size_t n_current_series;
  Common__PlayerPlaceInSeries **current_series;
  float current_series_scores;
  int32_t current_series_places;
  /*
   * formatted numeric string
   */
  char *current_series_avg_place;
};
#define COMMON__SERIES_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__series_result__descriptor) \
, NULL, 0,NULL, 0, 0, (char *)protobuf_c_empty_string, 0,NULL, 0, 0, (char *)protobuf_c_empty_string }


struct  Common__ReplacementPlayer
{
  ProtobufCMessage base;
  int32_t id;
  char *title;
  protobuf_c_boolean has_avatar;
  char *last_update;
};
#define COMMON__REPLACEMENT_PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__replacement_player__descriptor) \
, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  Common__PlayerInSession
{
  ProtobufCMessage base;
  int32_t id;
  char *title;
  int32_t score;
  /*
   *optional ReplacementPlayer replaced_by = 4;
   */
  float rating_delta;
  protobuf_c_boolean has_avatar;
  char *last_update;
  protobuf_c_boolean yakitori;
};
#define COMMON__PLAYER_IN_SESSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__player_in_session__descriptor) \
, 0, (char *)protobuf_c_empty_string, 0, 0, 0, (char *)protobuf_c_empty_string, 0 }


struct  Common__SessionHistoryResult
{
  ProtobufCMessage base;
  char *session_hash;
  int32_t event_id;
  int32_t player_id;
  int32_t score;
  float rating_delta;
  int32_t place;
  char *title;
  protobuf_c_boolean has_avatar;
  char *last_update;
};
#define COMMON__SESSION_HISTORY_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__session_history_result__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  Common__SessionHistoryResultTable
{
  ProtobufCMessage base;
  size_t n_tables;
  Common__SessionHistoryResult **tables;
};
#define COMMON__SESSION_HISTORY_RESULT_TABLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__session_history_result_table__descriptor) \
, 0,NULL }


struct  Common__PlacesSummaryItem
{
  ProtobufCMessage base;
  int32_t place;
  /*
   * count of games finished on this particular place
   */
  int32_t count;
};
#define COMMON__PLACES_SUMMARY_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__places_summary_item__descriptor) \
, 0, 0 }


struct  Common__PlayerWinSummary
{
  ProtobufCMessage base;
  int32_t ron;
  int32_t tsumo;
  int32_t chombo;
  int32_t feed;
  int32_t tsumofeed;
  int32_t wins_with_open;
  int32_t wins_with_riichi;
  int32_t wins_with_dama;
  int32_t unforced_feed_to_open;
  int32_t unforced_feed_to_riichi;
  int32_t unforced_feed_to_dama;
  int32_t draw;
  int32_t draw_tempai;
  int32_t points_won;
  int32_t points_lost_ron;
  int32_t points_lost_tsumo;
};
#define COMMON__PLAYER_WIN_SUMMARY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__player_win_summary__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  Common__HandValueStat
{
  ProtobufCMessage base;
  int32_t han_count;
  /*
   * count of hands with this value
   */
  int32_t count;
};
#define COMMON__HAND_VALUE_STAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__hand_value_stat__descriptor) \
, 0, 0 }


struct  Common__YakuStat
{
  ProtobufCMessage base;
  int32_t yaku_id;
  /*
   * count of hands contained this yaku
   */
  int32_t count;
};
#define COMMON__YAKU_STAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__yaku_stat__descriptor) \
, 0, 0 }


struct  Common__RiichiSummary
{
  ProtobufCMessage base;
  int32_t riichi_won;
  int32_t riichi_lost;
  int32_t feed_under_riichi;
};
#define COMMON__RIICHI_SUMMARY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__riichi_summary__descriptor) \
, 0, 0, 0 }


struct  Common__DoraSummary
{
  ProtobufCMessage base;
  int32_t count;
  float average;
};
#define COMMON__DORA_SUMMARY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__dora_summary__descriptor) \
, 0, 0 }


struct  Common__IntermediateResultOfSession
{
  ProtobufCMessage base;
  int32_t player_id;
  int32_t score;
  int32_t chombo_count;
};
#define COMMON__INTERMEDIATE_RESULT_OF_SESSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__intermediate_result_of_session__descriptor) \
, 0, 0, 0 }


struct  Common__Achievement
{
  ProtobufCMessage base;
  char *achievement_id;
  /*
   * JSON stringified data
   */
  char *achievement_data;
};
#define COMMON__ACHIEVEMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__achievement__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Common__LocalIdMapping
{
  ProtobufCMessage base;
  int32_t player_id;
  int32_t local_id;
};
#define COMMON__LOCAL_ID_MAPPING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__local_id_mapping__descriptor) \
, 0, 0 }


struct  Common__TeamMapping
{
  ProtobufCMessage base;
  int32_t player_id;
  char *team_name;
};
#define COMMON__TEAM_MAPPING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__team_mapping__descriptor) \
, 0, (char *)protobuf_c_empty_string }


struct  Common__PlayerSeating
{
  ProtobufCMessage base;
  /*
   * order at the table
   */
  int32_t order;
  int32_t player_id;
  int32_t session_id;
  int32_t table_index;
  float rating;
  char *player_title;
  protobuf_c_boolean has_avatar;
  char *last_update;
};
#define COMMON__PLAYER_SEATING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__player_seating__descriptor) \
, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  Common__PlayerSeatingSwiss
{
  ProtobufCMessage base;
  int32_t player_id;
  float rating;
};
#define COMMON__PLAYER_SEATING_SWISS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__player_seating_swiss__descriptor) \
, 0, 0 }


struct  Common__TableItemSwiss
{
  ProtobufCMessage base;
  /*
   * should be 4 elements
   */
  size_t n_players;
  Common__PlayerSeatingSwiss **players;
};
#define COMMON__TABLE_ITEM_SWISS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__table_item_swiss__descriptor) \
, 0,NULL }


struct  Common__Chombo
{
  ProtobufCMessage base;
  int32_t player_id;
  float amount;
};
#define COMMON__CHOMBO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__chombo__descriptor) \
, 0, 0 }


struct  Common__SessionState
{
  ProtobufCMessage base;
  int32_t dealer;
  int32_t round_index;
  int32_t riichi_count;
  int32_t honba_count;
  size_t n_scores;
  Common__IntermediateResultOfSession **scores;
  protobuf_c_boolean finished;
  protobuf_c_boolean last_hand_started;
  size_t n_chombo;
  Common__Chombo **chombo;
};
#define COMMON__SESSION_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__session_state__descriptor) \
, 0, 0, 0, 0, 0,NULL, 0, 0, 0,NULL }


struct  Common__Uma
{
  ProtobufCMessage base;
  int32_t place1;
  int32_t place2;
  int32_t place3;
  int32_t place4;
};
#define COMMON__UMA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__uma__descriptor) \
, 0, 0, 0, 0 }


struct  Common__ComplexUma
{
  ProtobufCMessage base;
  Common__Uma *neg1;
  Common__Uma *neg3;
  Common__Uma *otherwise;
};
#define COMMON__COMPLEX_UMA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__complex_uma__descriptor) \
, NULL, NULL, NULL }


struct  Common__RulesetConfig
{
  ProtobufCMessage base;
  Common__ComplexUma *complex_uma;
  Common__EndingPolicy ending_policy;
  Common__Uma *uma;
  Common__UmaType uma_type;
  protobuf_c_boolean doubleron_honba_atamahane;
  protobuf_c_boolean doubleron_riichi_atamahane;
  protobuf_c_boolean equalize_uma;
  protobuf_c_boolean extra_chombo_payments;
  protobuf_c_boolean play_additional_rounds;
  protobuf_c_boolean riichi_goes_to_winner;
  protobuf_c_boolean tonpuusen;
  protobuf_c_boolean with_abortives;
  protobuf_c_boolean with_atamahane;
  protobuf_c_boolean with_buttobi;
  protobuf_c_boolean with_kazoe;
  protobuf_c_boolean with_kiriage_mangan;
  protobuf_c_boolean with_kuitan;
  protobuf_c_boolean with_leading_dealer_game_over;
  protobuf_c_boolean with_multi_yakumans;
  protobuf_c_boolean with_nagashi_mangan;
  protobuf_c_boolean with_winning_dealer_honba_skipped;
  int32_t chips_value;
  int32_t chombo_amount;
  int32_t game_expiration_time;
  int32_t goal_points;
  int32_t max_penalty;
  int32_t min_penalty;
  int32_t oka;
  int32_t penalty_step;
  int32_t replacement_player_fixed_points;
  int32_t replacement_player_override_uma;
  int32_t start_points;
  int32_t start_rating;
  size_t n_allowed_yaku;
  int32_t *allowed_yaku;
  size_t n_yaku_with_pao;
  int32_t *yaku_with_pao;
  protobuf_c_boolean with_yakitori;
  int32_t yakitori_penalty;
  protobuf_c_boolean chombo_ends_game;
  int32_t honba_value;
  size_t n_double_yakuman;
  int32_t *double_yakuman;
};
#define COMMON__RULESET_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__ruleset_config__descriptor) \
, NULL, COMMON__ENDING_POLICY__ENDING_POLICY_EP_UNSPECIFIED, NULL, COMMON__UMA_TYPE__UMA_TYPE_UNSPECIFIED, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0, 0, 0, 0, 0,NULL }


struct  Common__MajsoulSearchEx
{
  ProtobufCMessage base;
  char *nickname;
  int32_t account_id;
};
#define COMMON__MAJSOUL_SEARCH_EX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__majsoul_search_ex__descriptor) \
, (char *)protobuf_c_empty_string, 0 }


struct  Common__MajsoulPersonMapping
{
  ProtobufCMessage base;
  int32_t person_id;
  char *nickname;
};
#define COMMON__MAJSOUL_PERSON_MAPPING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__majsoul_person_mapping__descriptor) \
, 0, (char *)protobuf_c_empty_string }


struct  Common__GenericSuccessResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
};
#define COMMON__GENERIC_SUCCESS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__generic_success_response__descriptor) \
, 0 }


struct  Common__GenericEventPayload
{
  ProtobufCMessage base;
  int32_t event_id;
};
#define COMMON__GENERIC_EVENT_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__generic_event_payload__descriptor) \
, 0 }


struct  Common__GenericSessionPayload
{
  ProtobufCMessage base;
  char *session_hash;
};
#define COMMON__GENERIC_SESSION_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__generic_session_payload__descriptor) \
, (char *)protobuf_c_empty_string }


/* Common__EventAdmin methods */
void   common__event_admin__init
                     (Common__EventAdmin         *message);
size_t common__event_admin__get_packed_size
                     (const Common__EventAdmin   *message);
size_t common__event_admin__pack
                     (const Common__EventAdmin   *message,
                      uint8_t             *out);
size_t common__event_admin__pack_to_buffer
                     (const Common__EventAdmin   *message,
                      ProtobufCBuffer     *buffer);
Common__EventAdmin *
       common__event_admin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__event_admin__free_unpacked
                     (Common__EventAdmin *message,
                      ProtobufCAllocator *allocator);
/* Common__EventReferee methods */
void   common__event_referee__init
                     (Common__EventReferee         *message);
size_t common__event_referee__get_packed_size
                     (const Common__EventReferee   *message);
size_t common__event_referee__pack
                     (const Common__EventReferee   *message,
                      uint8_t             *out);
size_t common__event_referee__pack_to_buffer
                     (const Common__EventReferee   *message,
                      ProtobufCBuffer     *buffer);
Common__EventReferee *
       common__event_referee__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__event_referee__free_unpacked
                     (Common__EventReferee *message,
                      ProtobufCAllocator *allocator);
/* Common__Person methods */
void   common__person__init
                     (Common__Person         *message);
size_t common__person__get_packed_size
                     (const Common__Person   *message);
size_t common__person__pack
                     (const Common__Person   *message,
                      uint8_t             *out);
size_t common__person__pack_to_buffer
                     (const Common__Person   *message,
                      ProtobufCBuffer     *buffer);
Common__Person *
       common__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__person__free_unpacked
                     (Common__Person *message,
                      ProtobufCAllocator *allocator);
/* Common__PersonEx methods */
void   common__person_ex__init
                     (Common__PersonEx         *message);
size_t common__person_ex__get_packed_size
                     (const Common__PersonEx   *message);
size_t common__person_ex__pack
                     (const Common__PersonEx   *message,
                      uint8_t             *out);
size_t common__person_ex__pack_to_buffer
                     (const Common__PersonEx   *message,
                      ProtobufCBuffer     *buffer);
Common__PersonEx *
       common__person_ex__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__person_ex__free_unpacked
                     (Common__PersonEx *message,
                      ProtobufCAllocator *allocator);
/* Common__Country methods */
void   common__country__init
                     (Common__Country         *message);
size_t common__country__get_packed_size
                     (const Common__Country   *message);
size_t common__country__pack
                     (const Common__Country   *message,
                      uint8_t             *out);
size_t common__country__pack_to_buffer
                     (const Common__Country   *message,
                      ProtobufCBuffer     *buffer);
Common__Country *
       common__country__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__country__free_unpacked
                     (Common__Country *message,
                      ProtobufCAllocator *allocator);
/* Common__Event methods */
void   common__event__init
                     (Common__Event         *message);
size_t common__event__get_packed_size
                     (const Common__Event   *message);
size_t common__event__pack
                     (const Common__Event   *message,
                      uint8_t             *out);
size_t common__event__pack_to_buffer
                     (const Common__Event   *message,
                      ProtobufCBuffer     *buffer);
Common__Event *
       common__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__event__free_unpacked
                     (Common__Event *message,
                      ProtobufCAllocator *allocator);
/* Common__MyEvent methods */
void   common__my_event__init
                     (Common__MyEvent         *message);
size_t common__my_event__get_packed_size
                     (const Common__MyEvent   *message);
size_t common__my_event__pack
                     (const Common__MyEvent   *message,
                      uint8_t             *out);
size_t common__my_event__pack_to_buffer
                     (const Common__MyEvent   *message,
                      ProtobufCBuffer     *buffer);
Common__MyEvent *
       common__my_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__my_event__free_unpacked
                     (Common__MyEvent *message,
                      ProtobufCAllocator *allocator);
/* Common__GameConfig methods */
void   common__game_config__init
                     (Common__GameConfig         *message);
size_t common__game_config__get_packed_size
                     (const Common__GameConfig   *message);
size_t common__game_config__pack
                     (const Common__GameConfig   *message,
                      uint8_t             *out);
size_t common__game_config__pack_to_buffer
                     (const Common__GameConfig   *message,
                      ProtobufCBuffer     *buffer);
Common__GameConfig *
       common__game_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__game_config__free_unpacked
                     (Common__GameConfig *message,
                      ProtobufCAllocator *allocator);
/* Common__Player methods */
void   common__player__init
                     (Common__Player         *message);
size_t common__player__get_packed_size
                     (const Common__Player   *message);
size_t common__player__pack
                     (const Common__Player   *message,
                      uint8_t             *out);
size_t common__player__pack_to_buffer
                     (const Common__Player   *message,
                      ProtobufCBuffer     *buffer);
Common__Player *
       common__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__player__free_unpacked
                     (Common__Player *message,
                      ProtobufCAllocator *allocator);
/* Common__FinalResultOfSession methods */
void   common__final_result_of_session__init
                     (Common__FinalResultOfSession         *message);
size_t common__final_result_of_session__get_packed_size
                     (const Common__FinalResultOfSession   *message);
size_t common__final_result_of_session__pack
                     (const Common__FinalResultOfSession   *message,
                      uint8_t             *out);
size_t common__final_result_of_session__pack_to_buffer
                     (const Common__FinalResultOfSession   *message,
                      ProtobufCBuffer     *buffer);
Common__FinalResultOfSession *
       common__final_result_of_session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__final_result_of_session__free_unpacked
                     (Common__FinalResultOfSession *message,
                      ProtobufCAllocator *allocator);
/* Common__RonResult methods */
void   common__ron_result__init
                     (Common__RonResult         *message);
size_t common__ron_result__get_packed_size
                     (const Common__RonResult   *message);
size_t common__ron_result__pack
                     (const Common__RonResult   *message,
                      uint8_t             *out);
size_t common__ron_result__pack_to_buffer
                     (const Common__RonResult   *message,
                      ProtobufCBuffer     *buffer);
Common__RonResult *
       common__ron_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__ron_result__free_unpacked
                     (Common__RonResult *message,
                      ProtobufCAllocator *allocator);
/* Common__MultironWin methods */
void   common__multiron_win__init
                     (Common__MultironWin         *message);
size_t common__multiron_win__get_packed_size
                     (const Common__MultironWin   *message);
size_t common__multiron_win__pack
                     (const Common__MultironWin   *message,
                      uint8_t             *out);
size_t common__multiron_win__pack_to_buffer
                     (const Common__MultironWin   *message,
                      ProtobufCBuffer     *buffer);
Common__MultironWin *
       common__multiron_win__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__multiron_win__free_unpacked
                     (Common__MultironWin *message,
                      ProtobufCAllocator *allocator);
/* Common__MultironResult methods */
void   common__multiron_result__init
                     (Common__MultironResult         *message);
size_t common__multiron_result__get_packed_size
                     (const Common__MultironResult   *message);
size_t common__multiron_result__pack
                     (const Common__MultironResult   *message,
                      uint8_t             *out);
size_t common__multiron_result__pack_to_buffer
                     (const Common__MultironResult   *message,
                      ProtobufCBuffer     *buffer);
Common__MultironResult *
       common__multiron_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__multiron_result__free_unpacked
                     (Common__MultironResult *message,
                      ProtobufCAllocator *allocator);
/* Common__TsumoResult methods */
void   common__tsumo_result__init
                     (Common__TsumoResult         *message);
size_t common__tsumo_result__get_packed_size
                     (const Common__TsumoResult   *message);
size_t common__tsumo_result__pack
                     (const Common__TsumoResult   *message,
                      uint8_t             *out);
size_t common__tsumo_result__pack_to_buffer
                     (const Common__TsumoResult   *message,
                      ProtobufCBuffer     *buffer);
Common__TsumoResult *
       common__tsumo_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__tsumo_result__free_unpacked
                     (Common__TsumoResult *message,
                      ProtobufCAllocator *allocator);
/* Common__DrawResult methods */
void   common__draw_result__init
                     (Common__DrawResult         *message);
size_t common__draw_result__get_packed_size
                     (const Common__DrawResult   *message);
size_t common__draw_result__pack
                     (const Common__DrawResult   *message,
                      uint8_t             *out);
size_t common__draw_result__pack_to_buffer
                     (const Common__DrawResult   *message,
                      ProtobufCBuffer     *buffer);
Common__DrawResult *
       common__draw_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__draw_result__free_unpacked
                     (Common__DrawResult *message,
                      ProtobufCAllocator *allocator);
/* Common__AbortResult methods */
void   common__abort_result__init
                     (Common__AbortResult         *message);
size_t common__abort_result__get_packed_size
                     (const Common__AbortResult   *message);
size_t common__abort_result__pack
                     (const Common__AbortResult   *message,
                      uint8_t             *out);
size_t common__abort_result__pack_to_buffer
                     (const Common__AbortResult   *message,
                      ProtobufCBuffer     *buffer);
Common__AbortResult *
       common__abort_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__abort_result__free_unpacked
                     (Common__AbortResult *message,
                      ProtobufCAllocator *allocator);
/* Common__ChomboResult methods */
void   common__chombo_result__init
                     (Common__ChomboResult         *message);
size_t common__chombo_result__get_packed_size
                     (const Common__ChomboResult   *message);
size_t common__chombo_result__pack
                     (const Common__ChomboResult   *message,
                      uint8_t             *out);
size_t common__chombo_result__pack_to_buffer
                     (const Common__ChomboResult   *message,
                      ProtobufCBuffer     *buffer);
Common__ChomboResult *
       common__chombo_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__chombo_result__free_unpacked
                     (Common__ChomboResult *message,
                      ProtobufCAllocator *allocator);
/* Common__NagashiResult methods */
void   common__nagashi_result__init
                     (Common__NagashiResult         *message);
size_t common__nagashi_result__get_packed_size
                     (const Common__NagashiResult   *message);
size_t common__nagashi_result__pack
                     (const Common__NagashiResult   *message,
                      uint8_t             *out);
size_t common__nagashi_result__pack_to_buffer
                     (const Common__NagashiResult   *message,
                      ProtobufCBuffer     *buffer);
Common__NagashiResult *
       common__nagashi_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__nagashi_result__free_unpacked
                     (Common__NagashiResult *message,
                      ProtobufCAllocator *allocator);
/* Common__Round methods */
void   common__round__init
                     (Common__Round         *message);
size_t common__round__get_packed_size
                     (const Common__Round   *message);
size_t common__round__pack
                     (const Common__Round   *message,
                      uint8_t             *out);
size_t common__round__pack_to_buffer
                     (const Common__Round   *message,
                      ProtobufCBuffer     *buffer);
Common__Round *
       common__round__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__round__free_unpacked
                     (Common__Round *message,
                      ProtobufCAllocator *allocator);
/* Common__PlayerPlaceInSeries methods */
void   common__player_place_in_series__init
                     (Common__PlayerPlaceInSeries         *message);
size_t common__player_place_in_series__get_packed_size
                     (const Common__PlayerPlaceInSeries   *message);
size_t common__player_place_in_series__pack
                     (const Common__PlayerPlaceInSeries   *message,
                      uint8_t             *out);
size_t common__player_place_in_series__pack_to_buffer
                     (const Common__PlayerPlaceInSeries   *message,
                      ProtobufCBuffer     *buffer);
Common__PlayerPlaceInSeries *
       common__player_place_in_series__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__player_place_in_series__free_unpacked
                     (Common__PlayerPlaceInSeries *message,
                      ProtobufCAllocator *allocator);
/* Common__SeriesResult methods */
void   common__series_result__init
                     (Common__SeriesResult         *message);
size_t common__series_result__get_packed_size
                     (const Common__SeriesResult   *message);
size_t common__series_result__pack
                     (const Common__SeriesResult   *message,
                      uint8_t             *out);
size_t common__series_result__pack_to_buffer
                     (const Common__SeriesResult   *message,
                      ProtobufCBuffer     *buffer);
Common__SeriesResult *
       common__series_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__series_result__free_unpacked
                     (Common__SeriesResult *message,
                      ProtobufCAllocator *allocator);
/* Common__ReplacementPlayer methods */
void   common__replacement_player__init
                     (Common__ReplacementPlayer         *message);
size_t common__replacement_player__get_packed_size
                     (const Common__ReplacementPlayer   *message);
size_t common__replacement_player__pack
                     (const Common__ReplacementPlayer   *message,
                      uint8_t             *out);
size_t common__replacement_player__pack_to_buffer
                     (const Common__ReplacementPlayer   *message,
                      ProtobufCBuffer     *buffer);
Common__ReplacementPlayer *
       common__replacement_player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__replacement_player__free_unpacked
                     (Common__ReplacementPlayer *message,
                      ProtobufCAllocator *allocator);
/* Common__PlayerInSession methods */
void   common__player_in_session__init
                     (Common__PlayerInSession         *message);
size_t common__player_in_session__get_packed_size
                     (const Common__PlayerInSession   *message);
size_t common__player_in_session__pack
                     (const Common__PlayerInSession   *message,
                      uint8_t             *out);
size_t common__player_in_session__pack_to_buffer
                     (const Common__PlayerInSession   *message,
                      ProtobufCBuffer     *buffer);
Common__PlayerInSession *
       common__player_in_session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__player_in_session__free_unpacked
                     (Common__PlayerInSession *message,
                      ProtobufCAllocator *allocator);
/* Common__SessionHistoryResult methods */
void   common__session_history_result__init
                     (Common__SessionHistoryResult         *message);
size_t common__session_history_result__get_packed_size
                     (const Common__SessionHistoryResult   *message);
size_t common__session_history_result__pack
                     (const Common__SessionHistoryResult   *message,
                      uint8_t             *out);
size_t common__session_history_result__pack_to_buffer
                     (const Common__SessionHistoryResult   *message,
                      ProtobufCBuffer     *buffer);
Common__SessionHistoryResult *
       common__session_history_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__session_history_result__free_unpacked
                     (Common__SessionHistoryResult *message,
                      ProtobufCAllocator *allocator);
/* Common__SessionHistoryResultTable methods */
void   common__session_history_result_table__init
                     (Common__SessionHistoryResultTable         *message);
size_t common__session_history_result_table__get_packed_size
                     (const Common__SessionHistoryResultTable   *message);
size_t common__session_history_result_table__pack
                     (const Common__SessionHistoryResultTable   *message,
                      uint8_t             *out);
size_t common__session_history_result_table__pack_to_buffer
                     (const Common__SessionHistoryResultTable   *message,
                      ProtobufCBuffer     *buffer);
Common__SessionHistoryResultTable *
       common__session_history_result_table__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__session_history_result_table__free_unpacked
                     (Common__SessionHistoryResultTable *message,
                      ProtobufCAllocator *allocator);
/* Common__PlacesSummaryItem methods */
void   common__places_summary_item__init
                     (Common__PlacesSummaryItem         *message);
size_t common__places_summary_item__get_packed_size
                     (const Common__PlacesSummaryItem   *message);
size_t common__places_summary_item__pack
                     (const Common__PlacesSummaryItem   *message,
                      uint8_t             *out);
size_t common__places_summary_item__pack_to_buffer
                     (const Common__PlacesSummaryItem   *message,
                      ProtobufCBuffer     *buffer);
Common__PlacesSummaryItem *
       common__places_summary_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__places_summary_item__free_unpacked
                     (Common__PlacesSummaryItem *message,
                      ProtobufCAllocator *allocator);
/* Common__PlayerWinSummary methods */
void   common__player_win_summary__init
                     (Common__PlayerWinSummary         *message);
size_t common__player_win_summary__get_packed_size
                     (const Common__PlayerWinSummary   *message);
size_t common__player_win_summary__pack
                     (const Common__PlayerWinSummary   *message,
                      uint8_t             *out);
size_t common__player_win_summary__pack_to_buffer
                     (const Common__PlayerWinSummary   *message,
                      ProtobufCBuffer     *buffer);
Common__PlayerWinSummary *
       common__player_win_summary__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__player_win_summary__free_unpacked
                     (Common__PlayerWinSummary *message,
                      ProtobufCAllocator *allocator);
/* Common__HandValueStat methods */
void   common__hand_value_stat__init
                     (Common__HandValueStat         *message);
size_t common__hand_value_stat__get_packed_size
                     (const Common__HandValueStat   *message);
size_t common__hand_value_stat__pack
                     (const Common__HandValueStat   *message,
                      uint8_t             *out);
size_t common__hand_value_stat__pack_to_buffer
                     (const Common__HandValueStat   *message,
                      ProtobufCBuffer     *buffer);
Common__HandValueStat *
       common__hand_value_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__hand_value_stat__free_unpacked
                     (Common__HandValueStat *message,
                      ProtobufCAllocator *allocator);
/* Common__YakuStat methods */
void   common__yaku_stat__init
                     (Common__YakuStat         *message);
size_t common__yaku_stat__get_packed_size
                     (const Common__YakuStat   *message);
size_t common__yaku_stat__pack
                     (const Common__YakuStat   *message,
                      uint8_t             *out);
size_t common__yaku_stat__pack_to_buffer
                     (const Common__YakuStat   *message,
                      ProtobufCBuffer     *buffer);
Common__YakuStat *
       common__yaku_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__yaku_stat__free_unpacked
                     (Common__YakuStat *message,
                      ProtobufCAllocator *allocator);
/* Common__RiichiSummary methods */
void   common__riichi_summary__init
                     (Common__RiichiSummary         *message);
size_t common__riichi_summary__get_packed_size
                     (const Common__RiichiSummary   *message);
size_t common__riichi_summary__pack
                     (const Common__RiichiSummary   *message,
                      uint8_t             *out);
size_t common__riichi_summary__pack_to_buffer
                     (const Common__RiichiSummary   *message,
                      ProtobufCBuffer     *buffer);
Common__RiichiSummary *
       common__riichi_summary__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__riichi_summary__free_unpacked
                     (Common__RiichiSummary *message,
                      ProtobufCAllocator *allocator);
/* Common__DoraSummary methods */
void   common__dora_summary__init
                     (Common__DoraSummary         *message);
size_t common__dora_summary__get_packed_size
                     (const Common__DoraSummary   *message);
size_t common__dora_summary__pack
                     (const Common__DoraSummary   *message,
                      uint8_t             *out);
size_t common__dora_summary__pack_to_buffer
                     (const Common__DoraSummary   *message,
                      ProtobufCBuffer     *buffer);
Common__DoraSummary *
       common__dora_summary__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__dora_summary__free_unpacked
                     (Common__DoraSummary *message,
                      ProtobufCAllocator *allocator);
/* Common__IntermediateResultOfSession methods */
void   common__intermediate_result_of_session__init
                     (Common__IntermediateResultOfSession         *message);
size_t common__intermediate_result_of_session__get_packed_size
                     (const Common__IntermediateResultOfSession   *message);
size_t common__intermediate_result_of_session__pack
                     (const Common__IntermediateResultOfSession   *message,
                      uint8_t             *out);
size_t common__intermediate_result_of_session__pack_to_buffer
                     (const Common__IntermediateResultOfSession   *message,
                      ProtobufCBuffer     *buffer);
Common__IntermediateResultOfSession *
       common__intermediate_result_of_session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__intermediate_result_of_session__free_unpacked
                     (Common__IntermediateResultOfSession *message,
                      ProtobufCAllocator *allocator);
/* Common__Achievement methods */
void   common__achievement__init
                     (Common__Achievement         *message);
size_t common__achievement__get_packed_size
                     (const Common__Achievement   *message);
size_t common__achievement__pack
                     (const Common__Achievement   *message,
                      uint8_t             *out);
size_t common__achievement__pack_to_buffer
                     (const Common__Achievement   *message,
                      ProtobufCBuffer     *buffer);
Common__Achievement *
       common__achievement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__achievement__free_unpacked
                     (Common__Achievement *message,
                      ProtobufCAllocator *allocator);
/* Common__LocalIdMapping methods */
void   common__local_id_mapping__init
                     (Common__LocalIdMapping         *message);
size_t common__local_id_mapping__get_packed_size
                     (const Common__LocalIdMapping   *message);
size_t common__local_id_mapping__pack
                     (const Common__LocalIdMapping   *message,
                      uint8_t             *out);
size_t common__local_id_mapping__pack_to_buffer
                     (const Common__LocalIdMapping   *message,
                      ProtobufCBuffer     *buffer);
Common__LocalIdMapping *
       common__local_id_mapping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__local_id_mapping__free_unpacked
                     (Common__LocalIdMapping *message,
                      ProtobufCAllocator *allocator);
/* Common__TeamMapping methods */
void   common__team_mapping__init
                     (Common__TeamMapping         *message);
size_t common__team_mapping__get_packed_size
                     (const Common__TeamMapping   *message);
size_t common__team_mapping__pack
                     (const Common__TeamMapping   *message,
                      uint8_t             *out);
size_t common__team_mapping__pack_to_buffer
                     (const Common__TeamMapping   *message,
                      ProtobufCBuffer     *buffer);
Common__TeamMapping *
       common__team_mapping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__team_mapping__free_unpacked
                     (Common__TeamMapping *message,
                      ProtobufCAllocator *allocator);
/* Common__PlayerSeating methods */
void   common__player_seating__init
                     (Common__PlayerSeating         *message);
size_t common__player_seating__get_packed_size
                     (const Common__PlayerSeating   *message);
size_t common__player_seating__pack
                     (const Common__PlayerSeating   *message,
                      uint8_t             *out);
size_t common__player_seating__pack_to_buffer
                     (const Common__PlayerSeating   *message,
                      ProtobufCBuffer     *buffer);
Common__PlayerSeating *
       common__player_seating__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__player_seating__free_unpacked
                     (Common__PlayerSeating *message,
                      ProtobufCAllocator *allocator);
/* Common__PlayerSeatingSwiss methods */
void   common__player_seating_swiss__init
                     (Common__PlayerSeatingSwiss         *message);
size_t common__player_seating_swiss__get_packed_size
                     (const Common__PlayerSeatingSwiss   *message);
size_t common__player_seating_swiss__pack
                     (const Common__PlayerSeatingSwiss   *message,
                      uint8_t             *out);
size_t common__player_seating_swiss__pack_to_buffer
                     (const Common__PlayerSeatingSwiss   *message,
                      ProtobufCBuffer     *buffer);
Common__PlayerSeatingSwiss *
       common__player_seating_swiss__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__player_seating_swiss__free_unpacked
                     (Common__PlayerSeatingSwiss *message,
                      ProtobufCAllocator *allocator);
/* Common__TableItemSwiss methods */
void   common__table_item_swiss__init
                     (Common__TableItemSwiss         *message);
size_t common__table_item_swiss__get_packed_size
                     (const Common__TableItemSwiss   *message);
size_t common__table_item_swiss__pack
                     (const Common__TableItemSwiss   *message,
                      uint8_t             *out);
size_t common__table_item_swiss__pack_to_buffer
                     (const Common__TableItemSwiss   *message,
                      ProtobufCBuffer     *buffer);
Common__TableItemSwiss *
       common__table_item_swiss__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__table_item_swiss__free_unpacked
                     (Common__TableItemSwiss *message,
                      ProtobufCAllocator *allocator);
/* Common__Chombo methods */
void   common__chombo__init
                     (Common__Chombo         *message);
size_t common__chombo__get_packed_size
                     (const Common__Chombo   *message);
size_t common__chombo__pack
                     (const Common__Chombo   *message,
                      uint8_t             *out);
size_t common__chombo__pack_to_buffer
                     (const Common__Chombo   *message,
                      ProtobufCBuffer     *buffer);
Common__Chombo *
       common__chombo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__chombo__free_unpacked
                     (Common__Chombo *message,
                      ProtobufCAllocator *allocator);
/* Common__SessionState methods */
void   common__session_state__init
                     (Common__SessionState         *message);
size_t common__session_state__get_packed_size
                     (const Common__SessionState   *message);
size_t common__session_state__pack
                     (const Common__SessionState   *message,
                      uint8_t             *out);
size_t common__session_state__pack_to_buffer
                     (const Common__SessionState   *message,
                      ProtobufCBuffer     *buffer);
Common__SessionState *
       common__session_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__session_state__free_unpacked
                     (Common__SessionState *message,
                      ProtobufCAllocator *allocator);
/* Common__Uma methods */
void   common__uma__init
                     (Common__Uma         *message);
size_t common__uma__get_packed_size
                     (const Common__Uma   *message);
size_t common__uma__pack
                     (const Common__Uma   *message,
                      uint8_t             *out);
size_t common__uma__pack_to_buffer
                     (const Common__Uma   *message,
                      ProtobufCBuffer     *buffer);
Common__Uma *
       common__uma__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__uma__free_unpacked
                     (Common__Uma *message,
                      ProtobufCAllocator *allocator);
/* Common__ComplexUma methods */
void   common__complex_uma__init
                     (Common__ComplexUma         *message);
size_t common__complex_uma__get_packed_size
                     (const Common__ComplexUma   *message);
size_t common__complex_uma__pack
                     (const Common__ComplexUma   *message,
                      uint8_t             *out);
size_t common__complex_uma__pack_to_buffer
                     (const Common__ComplexUma   *message,
                      ProtobufCBuffer     *buffer);
Common__ComplexUma *
       common__complex_uma__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__complex_uma__free_unpacked
                     (Common__ComplexUma *message,
                      ProtobufCAllocator *allocator);
/* Common__RulesetConfig methods */
void   common__ruleset_config__init
                     (Common__RulesetConfig         *message);
size_t common__ruleset_config__get_packed_size
                     (const Common__RulesetConfig   *message);
size_t common__ruleset_config__pack
                     (const Common__RulesetConfig   *message,
                      uint8_t             *out);
size_t common__ruleset_config__pack_to_buffer
                     (const Common__RulesetConfig   *message,
                      ProtobufCBuffer     *buffer);
Common__RulesetConfig *
       common__ruleset_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__ruleset_config__free_unpacked
                     (Common__RulesetConfig *message,
                      ProtobufCAllocator *allocator);
/* Common__MajsoulSearchEx methods */
void   common__majsoul_search_ex__init
                     (Common__MajsoulSearchEx         *message);
size_t common__majsoul_search_ex__get_packed_size
                     (const Common__MajsoulSearchEx   *message);
size_t common__majsoul_search_ex__pack
                     (const Common__MajsoulSearchEx   *message,
                      uint8_t             *out);
size_t common__majsoul_search_ex__pack_to_buffer
                     (const Common__MajsoulSearchEx   *message,
                      ProtobufCBuffer     *buffer);
Common__MajsoulSearchEx *
       common__majsoul_search_ex__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__majsoul_search_ex__free_unpacked
                     (Common__MajsoulSearchEx *message,
                      ProtobufCAllocator *allocator);
/* Common__MajsoulPersonMapping methods */
void   common__majsoul_person_mapping__init
                     (Common__MajsoulPersonMapping         *message);
size_t common__majsoul_person_mapping__get_packed_size
                     (const Common__MajsoulPersonMapping   *message);
size_t common__majsoul_person_mapping__pack
                     (const Common__MajsoulPersonMapping   *message,
                      uint8_t             *out);
size_t common__majsoul_person_mapping__pack_to_buffer
                     (const Common__MajsoulPersonMapping   *message,
                      ProtobufCBuffer     *buffer);
Common__MajsoulPersonMapping *
       common__majsoul_person_mapping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__majsoul_person_mapping__free_unpacked
                     (Common__MajsoulPersonMapping *message,
                      ProtobufCAllocator *allocator);
/* Common__GenericSuccessResponse methods */
void   common__generic_success_response__init
                     (Common__GenericSuccessResponse         *message);
size_t common__generic_success_response__get_packed_size
                     (const Common__GenericSuccessResponse   *message);
size_t common__generic_success_response__pack
                     (const Common__GenericSuccessResponse   *message,
                      uint8_t             *out);
size_t common__generic_success_response__pack_to_buffer
                     (const Common__GenericSuccessResponse   *message,
                      ProtobufCBuffer     *buffer);
Common__GenericSuccessResponse *
       common__generic_success_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__generic_success_response__free_unpacked
                     (Common__GenericSuccessResponse *message,
                      ProtobufCAllocator *allocator);
/* Common__GenericEventPayload methods */
void   common__generic_event_payload__init
                     (Common__GenericEventPayload         *message);
size_t common__generic_event_payload__get_packed_size
                     (const Common__GenericEventPayload   *message);
size_t common__generic_event_payload__pack
                     (const Common__GenericEventPayload   *message,
                      uint8_t             *out);
size_t common__generic_event_payload__pack_to_buffer
                     (const Common__GenericEventPayload   *message,
                      ProtobufCBuffer     *buffer);
Common__GenericEventPayload *
       common__generic_event_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__generic_event_payload__free_unpacked
                     (Common__GenericEventPayload *message,
                      ProtobufCAllocator *allocator);
/* Common__GenericSessionPayload methods */
void   common__generic_session_payload__init
                     (Common__GenericSessionPayload         *message);
size_t common__generic_session_payload__get_packed_size
                     (const Common__GenericSessionPayload   *message);
size_t common__generic_session_payload__pack
                     (const Common__GenericSessionPayload   *message,
                      uint8_t             *out);
size_t common__generic_session_payload__pack_to_buffer
                     (const Common__GenericSessionPayload   *message,
                      ProtobufCBuffer     *buffer);
Common__GenericSessionPayload *
       common__generic_session_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__generic_session_payload__free_unpacked
                     (Common__GenericSessionPayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Common__EventAdmin_Closure)
                 (const Common__EventAdmin *message,
                  void *closure_data);
typedef void (*Common__EventReferee_Closure)
                 (const Common__EventReferee *message,
                  void *closure_data);
typedef void (*Common__Person_Closure)
                 (const Common__Person *message,
                  void *closure_data);
typedef void (*Common__PersonEx_Closure)
                 (const Common__PersonEx *message,
                  void *closure_data);
typedef void (*Common__Country_Closure)
                 (const Common__Country *message,
                  void *closure_data);
typedef void (*Common__Event_Closure)
                 (const Common__Event *message,
                  void *closure_data);
typedef void (*Common__MyEvent_Closure)
                 (const Common__MyEvent *message,
                  void *closure_data);
typedef void (*Common__GameConfig_Closure)
                 (const Common__GameConfig *message,
                  void *closure_data);
typedef void (*Common__Player_Closure)
                 (const Common__Player *message,
                  void *closure_data);
typedef void (*Common__FinalResultOfSession_Closure)
                 (const Common__FinalResultOfSession *message,
                  void *closure_data);
typedef void (*Common__RonResult_Closure)
                 (const Common__RonResult *message,
                  void *closure_data);
typedef void (*Common__MultironWin_Closure)
                 (const Common__MultironWin *message,
                  void *closure_data);
typedef void (*Common__MultironResult_Closure)
                 (const Common__MultironResult *message,
                  void *closure_data);
typedef void (*Common__TsumoResult_Closure)
                 (const Common__TsumoResult *message,
                  void *closure_data);
typedef void (*Common__DrawResult_Closure)
                 (const Common__DrawResult *message,
                  void *closure_data);
typedef void (*Common__AbortResult_Closure)
                 (const Common__AbortResult *message,
                  void *closure_data);
typedef void (*Common__ChomboResult_Closure)
                 (const Common__ChomboResult *message,
                  void *closure_data);
typedef void (*Common__NagashiResult_Closure)
                 (const Common__NagashiResult *message,
                  void *closure_data);
typedef void (*Common__Round_Closure)
                 (const Common__Round *message,
                  void *closure_data);
typedef void (*Common__PlayerPlaceInSeries_Closure)
                 (const Common__PlayerPlaceInSeries *message,
                  void *closure_data);
typedef void (*Common__SeriesResult_Closure)
                 (const Common__SeriesResult *message,
                  void *closure_data);
typedef void (*Common__ReplacementPlayer_Closure)
                 (const Common__ReplacementPlayer *message,
                  void *closure_data);
typedef void (*Common__PlayerInSession_Closure)
                 (const Common__PlayerInSession *message,
                  void *closure_data);
typedef void (*Common__SessionHistoryResult_Closure)
                 (const Common__SessionHistoryResult *message,
                  void *closure_data);
typedef void (*Common__SessionHistoryResultTable_Closure)
                 (const Common__SessionHistoryResultTable *message,
                  void *closure_data);
typedef void (*Common__PlacesSummaryItem_Closure)
                 (const Common__PlacesSummaryItem *message,
                  void *closure_data);
typedef void (*Common__PlayerWinSummary_Closure)
                 (const Common__PlayerWinSummary *message,
                  void *closure_data);
typedef void (*Common__HandValueStat_Closure)
                 (const Common__HandValueStat *message,
                  void *closure_data);
typedef void (*Common__YakuStat_Closure)
                 (const Common__YakuStat *message,
                  void *closure_data);
typedef void (*Common__RiichiSummary_Closure)
                 (const Common__RiichiSummary *message,
                  void *closure_data);
typedef void (*Common__DoraSummary_Closure)
                 (const Common__DoraSummary *message,
                  void *closure_data);
typedef void (*Common__IntermediateResultOfSession_Closure)
                 (const Common__IntermediateResultOfSession *message,
                  void *closure_data);
typedef void (*Common__Achievement_Closure)
                 (const Common__Achievement *message,
                  void *closure_data);
typedef void (*Common__LocalIdMapping_Closure)
                 (const Common__LocalIdMapping *message,
                  void *closure_data);
typedef void (*Common__TeamMapping_Closure)
                 (const Common__TeamMapping *message,
                  void *closure_data);
typedef void (*Common__PlayerSeating_Closure)
                 (const Common__PlayerSeating *message,
                  void *closure_data);
typedef void (*Common__PlayerSeatingSwiss_Closure)
                 (const Common__PlayerSeatingSwiss *message,
                  void *closure_data);
typedef void (*Common__TableItemSwiss_Closure)
                 (const Common__TableItemSwiss *message,
                  void *closure_data);
typedef void (*Common__Chombo_Closure)
                 (const Common__Chombo *message,
                  void *closure_data);
typedef void (*Common__SessionState_Closure)
                 (const Common__SessionState *message,
                  void *closure_data);
typedef void (*Common__Uma_Closure)
                 (const Common__Uma *message,
                  void *closure_data);
typedef void (*Common__ComplexUma_Closure)
                 (const Common__ComplexUma *message,
                  void *closure_data);
typedef void (*Common__RulesetConfig_Closure)
                 (const Common__RulesetConfig *message,
                  void *closure_data);
typedef void (*Common__MajsoulSearchEx_Closure)
                 (const Common__MajsoulSearchEx *message,
                  void *closure_data);
typedef void (*Common__MajsoulPersonMapping_Closure)
                 (const Common__MajsoulPersonMapping *message,
                  void *closure_data);
typedef void (*Common__GenericSuccessResponse_Closure)
                 (const Common__GenericSuccessResponse *message,
                  void *closure_data);
typedef void (*Common__GenericEventPayload_Closure)
                 (const Common__GenericEventPayload *message,
                  void *closure_data);
typedef void (*Common__GenericSessionPayload_Closure)
                 (const Common__GenericSessionPayload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    common__event_type__descriptor;
extern const ProtobufCEnumDescriptor    common__tournament_games_status__descriptor;
extern const ProtobufCEnumDescriptor    common__round_outcome__descriptor;
extern const ProtobufCEnumDescriptor    common__session_status__descriptor;
extern const ProtobufCEnumDescriptor    common__uma_type__descriptor;
extern const ProtobufCEnumDescriptor    common__ending_policy__descriptor;
extern const ProtobufCEnumDescriptor    common__platform_type__descriptor;
extern const ProtobufCMessageDescriptor common__event_admin__descriptor;
extern const ProtobufCMessageDescriptor common__event_referee__descriptor;
extern const ProtobufCMessageDescriptor common__person__descriptor;
extern const ProtobufCMessageDescriptor common__person_ex__descriptor;
extern const ProtobufCMessageDescriptor common__country__descriptor;
extern const ProtobufCMessageDescriptor common__event__descriptor;
extern const ProtobufCMessageDescriptor common__my_event__descriptor;
extern const ProtobufCMessageDescriptor common__game_config__descriptor;
extern const ProtobufCMessageDescriptor common__player__descriptor;
extern const ProtobufCMessageDescriptor common__final_result_of_session__descriptor;
extern const ProtobufCMessageDescriptor common__ron_result__descriptor;
extern const ProtobufCMessageDescriptor common__multiron_win__descriptor;
extern const ProtobufCMessageDescriptor common__multiron_result__descriptor;
extern const ProtobufCMessageDescriptor common__tsumo_result__descriptor;
extern const ProtobufCMessageDescriptor common__draw_result__descriptor;
extern const ProtobufCMessageDescriptor common__abort_result__descriptor;
extern const ProtobufCMessageDescriptor common__chombo_result__descriptor;
extern const ProtobufCMessageDescriptor common__nagashi_result__descriptor;
extern const ProtobufCMessageDescriptor common__round__descriptor;
extern const ProtobufCMessageDescriptor common__player_place_in_series__descriptor;
extern const ProtobufCMessageDescriptor common__series_result__descriptor;
extern const ProtobufCMessageDescriptor common__replacement_player__descriptor;
extern const ProtobufCMessageDescriptor common__player_in_session__descriptor;
extern const ProtobufCMessageDescriptor common__session_history_result__descriptor;
extern const ProtobufCMessageDescriptor common__session_history_result_table__descriptor;
extern const ProtobufCMessageDescriptor common__places_summary_item__descriptor;
extern const ProtobufCMessageDescriptor common__player_win_summary__descriptor;
extern const ProtobufCMessageDescriptor common__hand_value_stat__descriptor;
extern const ProtobufCMessageDescriptor common__yaku_stat__descriptor;
extern const ProtobufCMessageDescriptor common__riichi_summary__descriptor;
extern const ProtobufCMessageDescriptor common__dora_summary__descriptor;
extern const ProtobufCMessageDescriptor common__intermediate_result_of_session__descriptor;
extern const ProtobufCMessageDescriptor common__achievement__descriptor;
extern const ProtobufCMessageDescriptor common__local_id_mapping__descriptor;
extern const ProtobufCMessageDescriptor common__team_mapping__descriptor;
extern const ProtobufCMessageDescriptor common__player_seating__descriptor;
extern const ProtobufCMessageDescriptor common__player_seating_swiss__descriptor;
extern const ProtobufCMessageDescriptor common__table_item_swiss__descriptor;
extern const ProtobufCMessageDescriptor common__chombo__descriptor;
extern const ProtobufCMessageDescriptor common__session_state__descriptor;
extern const ProtobufCMessageDescriptor common__uma__descriptor;
extern const ProtobufCMessageDescriptor common__complex_uma__descriptor;
extern const ProtobufCMessageDescriptor common__ruleset_config__descriptor;
extern const ProtobufCMessageDescriptor common__majsoul_search_ex__descriptor;
extern const ProtobufCMessageDescriptor common__majsoul_person_mapping__descriptor;
extern const ProtobufCMessageDescriptor common__generic_success_response__descriptor;
extern const ProtobufCMessageDescriptor common__generic_event_payload__descriptor;
extern const ProtobufCMessageDescriptor common__generic_session_payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_atoms_2eproto__INCLUDED */
