/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/mimir.proto */

#ifndef PROTOBUF_C_proto_2fmimir_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fmimir_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "atoms.pb-c.h"

typedef struct Common__EventsGetTimerStateResponse Common__EventsGetTimerStateResponse;
typedef struct Common__CurrentSession Common__CurrentSession;
typedef struct Common__GetCurrentStateResponse Common__GetCurrentStateResponse;


/* --- enums --- */


/* --- messages --- */

struct  Common__EventsGetTimerStateResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean started;
  protobuf_c_boolean finished;
  int32_t time_remaining;
  protobuf_c_boolean waiting_for_timer;
  protobuf_c_boolean have_autostart;
  protobuf_c_boolean autostart_timer;
  int32_t hide_seating_after;
};
#define COMMON__EVENTS_GET_TIMER_STATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__events_get_timer_state_response__descriptor) \
, 0, 0, 0, 0, 0, 0, 0 }


struct  Common__CurrentSession
{
  ProtobufCMessage base;
  char *session_hash;
  char *status;
  int32_t table_index;
  size_t n_players;
  Common__PlayerInSession **players;
  Common__EventsGetTimerStateResponse *timer_state;
};
#define COMMON__CURRENT_SESSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__current_session__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0,NULL, NULL }


struct  Common__GetCurrentStateResponse
{
  ProtobufCMessage base;
  size_t n_sessions;
  Common__CurrentSession **sessions;
  Common__GameConfig *config;
};
#define COMMON__GET_CURRENT_STATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&common__get_current_state_response__descriptor) \
, 0,NULL, NULL }


/* Common__EventsGetTimerStateResponse methods */
void   common__events_get_timer_state_response__init
                     (Common__EventsGetTimerStateResponse         *message);
size_t common__events_get_timer_state_response__get_packed_size
                     (const Common__EventsGetTimerStateResponse   *message);
size_t common__events_get_timer_state_response__pack
                     (const Common__EventsGetTimerStateResponse   *message,
                      uint8_t             *out);
size_t common__events_get_timer_state_response__pack_to_buffer
                     (const Common__EventsGetTimerStateResponse   *message,
                      ProtobufCBuffer     *buffer);
Common__EventsGetTimerStateResponse *
       common__events_get_timer_state_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__events_get_timer_state_response__free_unpacked
                     (Common__EventsGetTimerStateResponse *message,
                      ProtobufCAllocator *allocator);
/* Common__CurrentSession methods */
void   common__current_session__init
                     (Common__CurrentSession         *message);
size_t common__current_session__get_packed_size
                     (const Common__CurrentSession   *message);
size_t common__current_session__pack
                     (const Common__CurrentSession   *message,
                      uint8_t             *out);
size_t common__current_session__pack_to_buffer
                     (const Common__CurrentSession   *message,
                      ProtobufCBuffer     *buffer);
Common__CurrentSession *
       common__current_session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__current_session__free_unpacked
                     (Common__CurrentSession *message,
                      ProtobufCAllocator *allocator);
/* Common__GetCurrentStateResponse methods */
void   common__get_current_state_response__init
                     (Common__GetCurrentStateResponse         *message);
size_t common__get_current_state_response__get_packed_size
                     (const Common__GetCurrentStateResponse   *message);
size_t common__get_current_state_response__pack
                     (const Common__GetCurrentStateResponse   *message,
                      uint8_t             *out);
size_t common__get_current_state_response__pack_to_buffer
                     (const Common__GetCurrentStateResponse   *message,
                      ProtobufCBuffer     *buffer);
Common__GetCurrentStateResponse *
       common__get_current_state_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   common__get_current_state_response__free_unpacked
                     (Common__GetCurrentStateResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Common__EventsGetTimerStateResponse_Closure)
                 (const Common__EventsGetTimerStateResponse *message,
                  void *closure_data);
typedef void (*Common__CurrentSession_Closure)
                 (const Common__CurrentSession *message,
                  void *closure_data);
typedef void (*Common__GetCurrentStateResponse_Closure)
                 (const Common__GetCurrentStateResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor common__events_get_timer_state_response__descriptor;
extern const ProtobufCMessageDescriptor common__current_session__descriptor;
extern const ProtobufCMessageDescriptor common__get_current_state_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fmimir_2eproto__INCLUDED */
