/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/mimir.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mimir.pb-c.h"
void   common__events_get_timer_state_response__init
                     (Common__EventsGetTimerStateResponse         *message)
{
  static const Common__EventsGetTimerStateResponse init_value = COMMON__EVENTS_GET_TIMER_STATE_RESPONSE__INIT;
  *message = init_value;
}
size_t common__events_get_timer_state_response__get_packed_size
                     (const Common__EventsGetTimerStateResponse *message)
{
  assert(message->base.descriptor == &common__events_get_timer_state_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t common__events_get_timer_state_response__pack
                     (const Common__EventsGetTimerStateResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &common__events_get_timer_state_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t common__events_get_timer_state_response__pack_to_buffer
                     (const Common__EventsGetTimerStateResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &common__events_get_timer_state_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Common__EventsGetTimerStateResponse *
       common__events_get_timer_state_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Common__EventsGetTimerStateResponse *)
     protobuf_c_message_unpack (&common__events_get_timer_state_response__descriptor,
                                allocator, len, data);
}
void   common__events_get_timer_state_response__free_unpacked
                     (Common__EventsGetTimerStateResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &common__events_get_timer_state_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   common__current_session__init
                     (Common__CurrentSession         *message)
{
  static const Common__CurrentSession init_value = COMMON__CURRENT_SESSION__INIT;
  *message = init_value;
}
size_t common__current_session__get_packed_size
                     (const Common__CurrentSession *message)
{
  assert(message->base.descriptor == &common__current_session__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t common__current_session__pack
                     (const Common__CurrentSession *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &common__current_session__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t common__current_session__pack_to_buffer
                     (const Common__CurrentSession *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &common__current_session__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Common__CurrentSession *
       common__current_session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Common__CurrentSession *)
     protobuf_c_message_unpack (&common__current_session__descriptor,
                                allocator, len, data);
}
void   common__current_session__free_unpacked
                     (Common__CurrentSession *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &common__current_session__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   common__get_current_state_response__init
                     (Common__GetCurrentStateResponse         *message)
{
  static const Common__GetCurrentStateResponse init_value = COMMON__GET_CURRENT_STATE_RESPONSE__INIT;
  *message = init_value;
}
size_t common__get_current_state_response__get_packed_size
                     (const Common__GetCurrentStateResponse *message)
{
  assert(message->base.descriptor == &common__get_current_state_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t common__get_current_state_response__pack
                     (const Common__GetCurrentStateResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &common__get_current_state_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t common__get_current_state_response__pack_to_buffer
                     (const Common__GetCurrentStateResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &common__get_current_state_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Common__GetCurrentStateResponse *
       common__get_current_state_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Common__GetCurrentStateResponse *)
     protobuf_c_message_unpack (&common__get_current_state_response__descriptor,
                                allocator, len, data);
}
void   common__get_current_state_response__free_unpacked
                     (Common__GetCurrentStateResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &common__get_current_state_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor common__events_get_timer_state_response__field_descriptors[7] =
{
  {
    "started",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Common__EventsGetTimerStateResponse, started),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "finished",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Common__EventsGetTimerStateResponse, finished),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_remaining",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Common__EventsGetTimerStateResponse, time_remaining),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "waiting_for_timer",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Common__EventsGetTimerStateResponse, waiting_for_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "have_autostart",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Common__EventsGetTimerStateResponse, have_autostart),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autostart_timer",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Common__EventsGetTimerStateResponse, autostart_timer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hide_seating_after",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Common__EventsGetTimerStateResponse, hide_seating_after),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__events_get_timer_state_response__field_indices_by_name[] = {
  5,   /* field[5] = autostart_timer */
  1,   /* field[1] = finished */
  4,   /* field[4] = have_autostart */
  6,   /* field[6] = hide_seating_after */
  0,   /* field[0] = started */
  2,   /* field[2] = time_remaining */
  3,   /* field[3] = waiting_for_timer */
};
static const ProtobufCIntRange common__events_get_timer_state_response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor common__events_get_timer_state_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.EventsGetTimerStateResponse",
  "EventsGetTimerStateResponse",
  "Common__EventsGetTimerStateResponse",
  "common",
  sizeof(Common__EventsGetTimerStateResponse),
  7,
  common__events_get_timer_state_response__field_descriptors,
  common__events_get_timer_state_response__field_indices_by_name,
  2,  common__events_get_timer_state_response__number_ranges,
  (ProtobufCMessageInit) common__events_get_timer_state_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor common__current_session__field_descriptors[5] =
{
  {
    "session_hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Common__CurrentSession, session_hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Common__CurrentSession, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_index",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Common__CurrentSession, table_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "players",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Common__CurrentSession, n_players),
    offsetof(Common__CurrentSession, players),
    &common__player_in_session__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timer_state",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Common__CurrentSession, timer_state),
    &common__events_get_timer_state_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__current_session__field_indices_by_name[] = {
  3,   /* field[3] = players */
  0,   /* field[0] = session_hash */
  1,   /* field[1] = status */
  2,   /* field[2] = table_index */
  4,   /* field[4] = timer_state */
};
static const ProtobufCIntRange common__current_session__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor common__current_session__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.CurrentSession",
  "CurrentSession",
  "Common__CurrentSession",
  "common",
  sizeof(Common__CurrentSession),
  5,
  common__current_session__field_descriptors,
  common__current_session__field_indices_by_name,
  1,  common__current_session__number_ranges,
  (ProtobufCMessageInit) common__current_session__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor common__get_current_state_response__field_descriptors[2] =
{
  {
    "sessions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Common__GetCurrentStateResponse, n_sessions),
    offsetof(Common__GetCurrentStateResponse, sessions),
    &common__current_session__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Common__GetCurrentStateResponse, config),
    &common__game_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__get_current_state_response__field_indices_by_name[] = {
  1,   /* field[1] = config */
  0,   /* field[0] = sessions */
};
static const ProtobufCIntRange common__get_current_state_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor common__get_current_state_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.GetCurrentStateResponse",
  "GetCurrentStateResponse",
  "Common__GetCurrentStateResponse",
  "common",
  sizeof(Common__GetCurrentStateResponse),
  2,
  common__get_current_state_response__field_descriptors,
  common__get_current_state_response__field_indices_by_name,
  1,  common__get_current_state_response__number_ranges,
  (ProtobufCMessageInit) common__get_current_state_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
